services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lms-app
    environment:
      PORT: 8080
      JWT_SECRET: dev_jwt_secret_doi_khi_len_production
      DB_MASTER_HOST: postgres
      DB_MASTER_PORT: 5432
      DB_MASTER_USER: lms_user
      DB_MASTER_PASSWORD: qlsJWiklVEKPCic0cpjOjMbJ
      DB_MASTER_NAME: lms_db
      DB_REPLICA_HOST: postgres
      DB_REPLICA_PORT: 5432
      DB_REPLICA_USER: lms_user
      DB_REPLICA_PASSWORD: qlsJWiklVEKPCic0cpjOjMbJ
      DB_REPLICA_NAME: lms_db
      REDIS_ENABLED: "true"
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: 0lJc4VUTFmyV
      REDIS_DB: 0
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - lms-network

  postgres:
    image: postgres:15-alpine
    container_name: lms-postgres
    environment:
      POSTGRES_DB: lms_db
      POSTGRES_USER: lms_user
      POSTGRES_PASSWORD: qlsJWiklVEKPCic0cpjOjMbJ
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - lms-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lms_user -d lms_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: lms-redis
    command: redis-server --requirepass 0lJc4VUTFmyV
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - lms-network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "0lJc4VUTFmyV", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

  # One-shot: docker compose --profile tools run --rm seeder
  seeder:
    profiles:
      - tools
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_MASTER_HOST: postgres
      DB_MASTER_PORT: 5432
      DB_MASTER_USER: lms_user
      DB_MASTER_PASSWORD: qlsJWiklVEKPCic0cpjOjMbJ
      DB_MASTER_NAME: lms_db
      DB_REPLICA_HOST: postgres
      DB_REPLICA_PORT: 5432
      DB_REPLICA_USER: lms_user
      DB_REPLICA_PASSWORD: qlsJWiklVEKPCic0cpjOjMbJ
      DB_REPLICA_NAME: lms_db
      REDIS_ENABLED: "true"
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: 0lJc4VUTFmyV
      REDIS_DB: 0
    depends_on:
      postgres:
        condition: service_healthy
    entrypoint: ["./seeder", "-model", "Role"]
    networks:
      - lms-network

networks:
  lms-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
