services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lms-app
    ports:
      - "8080:8080"

  postgres:
    image: postgres:15-alpine
    container_name: lms-postgres
    environment:
      POSTGRES_DB: lms_db
      POSTGRES_USER: lms_user
      POSTGRES_PASSWORD: qlsJWiklVEKPCic0cpjOjMbJ
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - lms-network

  redis:
    image: redis:7-alpine
    container_name: lms-redis
    command: redis-server --requirepass 0lJc4VUTFmyV
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - lms-network

networks:
  lms-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
