// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: answer.proto

package prot

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MediaAnswer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	File          []byte                 `protobuf:"bytes,3,opt,name=file,proto3" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaAnswer) Reset() {
	*x = MediaAnswer{}
	mi := &file_answer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaAnswer) ProtoMessage() {}

func (x *MediaAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_answer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaAnswer.ProtoReflect.Descriptor instead.
func (*MediaAnswer) Descriptor() ([]byte, []int) {
	return file_answer_proto_rawDescGZIP(), []int{0}
}

func (x *MediaAnswer) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *MediaAnswer) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *MediaAnswer) GetFile() []byte {
	if x != nil {
		return x.File
	}
	return nil
}

type GroupAnswer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Media         *MediaAnswer           `protobuf:"bytes,3,opt,name=media,proto3" json:"media,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupAnswer) Reset() {
	*x = GroupAnswer{}
	mi := &file_answer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupAnswer) ProtoMessage() {}

func (x *GroupAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_answer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupAnswer.ProtoReflect.Descriptor instead.
func (*GroupAnswer) Descriptor() ([]byte, []int) {
	return file_answer_proto_rawDescGZIP(), []int{1}
}

func (x *GroupAnswer) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GroupAnswer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GroupAnswer) GetMedia() *MediaAnswer {
	if x != nil {
		return x.Media
	}
	return nil
}

type AnswerContent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Text            string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Point           float64                `protobuf:"fixed64,3,opt,name=point,proto3" json:"point,omitempty"`
	Media           *MediaAnswer           `protobuf:"bytes,4,opt,name=media,proto3" json:"media,omitempty"`
	IsCorrect       bool                   `protobuf:"varint,5,opt,name=is_correct,json=isCorrect,proto3" json:"is_correct,omitempty"`
	CorrectPosition int32                  `protobuf:"varint,6,opt,name=correct_position,json=correctPosition,proto3" json:"correct_position,omitempty"`
	GroupPosition   int32                  `protobuf:"varint,7,opt,name=group_position,json=groupPosition,proto3" json:"group_position,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AnswerContent) Reset() {
	*x = AnswerContent{}
	mi := &file_answer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnswerContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerContent) ProtoMessage() {}

func (x *AnswerContent) ProtoReflect() protoreflect.Message {
	mi := &file_answer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerContent.ProtoReflect.Descriptor instead.
func (*AnswerContent) Descriptor() ([]byte, []int) {
	return file_answer_proto_rawDescGZIP(), []int{2}
}

func (x *AnswerContent) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AnswerContent) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *AnswerContent) GetPoint() float64 {
	if x != nil {
		return x.Point
	}
	return 0
}

func (x *AnswerContent) GetMedia() *MediaAnswer {
	if x != nil {
		return x.Media
	}
	return nil
}

func (x *AnswerContent) GetIsCorrect() bool {
	if x != nil {
		return x.IsCorrect
	}
	return false
}

func (x *AnswerContent) GetCorrectPosition() int32 {
	if x != nil {
		return x.CorrectPosition
	}
	return 0
}

func (x *AnswerContent) GetGroupPosition() int32 {
	if x != nil {
		return x.GroupPosition
	}
	return 0
}

type SourceContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Media         *MediaAnswer           `protobuf:"bytes,2,opt,name=media,proto3" json:"media,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceContent) Reset() {
	*x = SourceContent{}
	mi := &file_answer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceContent) ProtoMessage() {}

func (x *SourceContent) ProtoReflect() protoreflect.Message {
	mi := &file_answer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceContent.ProtoReflect.Descriptor instead.
func (*SourceContent) Descriptor() ([]byte, []int) {
	return file_answer_proto_rawDescGZIP(), []int{3}
}

func (x *SourceContent) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SourceContent) GetMedia() *MediaAnswer {
	if x != nil {
		return x.Media
	}
	return nil
}

type AnswerSource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Content       *SourceContent         `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	GroupPosition int32                  `protobuf:"varint,3,opt,name=group_position,json=groupPosition,proto3" json:"group_position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnswerSource) Reset() {
	*x = AnswerSource{}
	mi := &file_answer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnswerSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerSource) ProtoMessage() {}

func (x *AnswerSource) ProtoReflect() protoreflect.Message {
	mi := &file_answer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerSource.ProtoReflect.Descriptor instead.
func (*AnswerSource) Descriptor() ([]byte, []int) {
	return file_answer_proto_rawDescGZIP(), []int{4}
}

func (x *AnswerSource) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AnswerSource) GetContent() *SourceContent {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *AnswerSource) GetGroupPosition() int32 {
	if x != nil {
		return x.GroupPosition
	}
	return 0
}

type AnswerTarget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Content       *AnswerContent         `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnswerTarget) Reset() {
	*x = AnswerTarget{}
	mi := &file_answer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnswerTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerTarget) ProtoMessage() {}

func (x *AnswerTarget) ProtoReflect() protoreflect.Message {
	mi := &file_answer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerTarget.ProtoReflect.Descriptor instead.
func (*AnswerTarget) Descriptor() ([]byte, []int) {
	return file_answer_proto_rawDescGZIP(), []int{5}
}

func (x *AnswerTarget) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AnswerTarget) GetContent() *AnswerContent {
	if x != nil {
		return x.Content
	}
	return nil
}

type AnswerCoordinates struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	W             int32                  `protobuf:"varint,3,opt,name=w,proto3" json:"w,omitempty"`
	H             int32                  `protobuf:"varint,4,opt,name=h,proto3" json:"h,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnswerCoordinates) Reset() {
	*x = AnswerCoordinates{}
	mi := &file_answer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnswerCoordinates) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerCoordinates) ProtoMessage() {}

func (x *AnswerCoordinates) ProtoReflect() protoreflect.Message {
	mi := &file_answer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerCoordinates.ProtoReflect.Descriptor instead.
func (*AnswerCoordinates) Descriptor() ([]byte, []int) {
	return file_answer_proto_rawDescGZIP(), []int{6}
}

func (x *AnswerCoordinates) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *AnswerCoordinates) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *AnswerCoordinates) GetW() int32 {
	if x != nil {
		return x.W
	}
	return 0
}

func (x *AnswerCoordinates) GetH() int32 {
	if x != nil {
		return x.H
	}
	return 0
}

type AnswerBlank struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Coordinates   *AnswerCoordinates     `protobuf:"bytes,2,opt,name=coordinates,proto3" json:"coordinates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnswerBlank) Reset() {
	*x = AnswerBlank{}
	mi := &file_answer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnswerBlank) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerBlank) ProtoMessage() {}

func (x *AnswerBlank) ProtoReflect() protoreflect.Message {
	mi := &file_answer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerBlank.ProtoReflect.Descriptor instead.
func (*AnswerBlank) Descriptor() ([]byte, []int) {
	return file_answer_proto_rawDescGZIP(), []int{7}
}

func (x *AnswerBlank) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AnswerBlank) GetCoordinates() *AnswerCoordinates {
	if x != nil {
		return x.Coordinates
	}
	return nil
}

type GroupPosition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Position      int32                  `protobuf:"varint,1,opt,name=position,proto3" json:"position,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	Media         *MediaAnswer           `protobuf:"bytes,4,opt,name=media,proto3" json:"media,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupPosition) Reset() {
	*x = GroupPosition{}
	mi := &file_answer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupPosition) ProtoMessage() {}

func (x *GroupPosition) ProtoReflect() protoreflect.Message {
	mi := &file_answer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupPosition.ProtoReflect.Descriptor instead.
func (*GroupPosition) Descriptor() ([]byte, []int) {
	return file_answer_proto_rawDescGZIP(), []int{8}
}

func (x *GroupPosition) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *GroupPosition) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GroupPosition) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *GroupPosition) GetMedia() *MediaAnswer {
	if x != nil {
		return x.Media
	}
	return nil
}

// Message đại diện cho một câu trả lời
type Answer struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                                   // ID câu trả lời
	QuestionId      int64                  `protobuf:"varint,2,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`                 // ID câu hỏi (int64 để phù hợp với model Go)
	Content         string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`                                          // Nội dung câu trả lời
	Group           *GroupAnswer           `protobuf:"bytes,4,opt,name=group,proto3" json:"group,omitempty"`                                              // Nhóm câu trả lời (nếu có)
	FileUrl         string                 `protobuf:"bytes,5,opt,name=file_url,json=fileUrl,proto3" json:"file_url,omitempty"`                           // URL của file (nếu có)
	IsCorrect       bool                   `protobuf:"varint,6,opt,name=is_correct,json=isCorrect,proto3" json:"is_correct,omitempty"`                    // Trạng thái đúng/sai
	Kind            string                 `protobuf:"bytes,7,opt,name=kind,proto3" json:"kind,omitempty"`                                                // Loại câu trả lời (enum)
	Point           float64                `protobuf:"fixed64,8,opt,name=point,proto3" json:"point,omitempty"`                                            // Điểm cho câu trả lời
	PositionX       int32                  `protobuf:"varint,9,opt,name=position_x,json=positionX,proto3" json:"position_x,omitempty"`                    // Vị trí X
	PositionY       int32                  `protobuf:"varint,10,opt,name=position_y,json=positionY,proto3" json:"position_y,omitempty"`                   // Vị trí Y
	PositionWidth   int32                  `protobuf:"varint,11,opt,name=position_width,json=positionWidth,proto3" json:"position_width,omitempty"`       // Chiều rộng
	PositionHeight  int32                  `protobuf:"varint,12,opt,name=position_height,json=positionHeight,proto3" json:"position_height,omitempty"`    // Chiều cao
	SortPosition    int32                  `protobuf:"varint,13,opt,name=sort_position,json=sortPosition,proto3" json:"sort_position,omitempty"`          // Vị trí sắp xếp
	CorrectPosition int32                  `protobuf:"varint,14,opt,name=correct_position,json=correctPosition,proto3" json:"correct_position,omitempty"` // Vị trí chính xác
	CreatedAt       string                 `protobuf:"bytes,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`                    // Thời gian tạo
	UpdatedAt       string                 `protobuf:"bytes,16,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Answer) Reset() {
	*x = Answer{}
	mi := &file_answer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Answer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Answer) ProtoMessage() {}

func (x *Answer) ProtoReflect() protoreflect.Message {
	mi := &file_answer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Answer.ProtoReflect.Descriptor instead.
func (*Answer) Descriptor() ([]byte, []int) {
	return file_answer_proto_rawDescGZIP(), []int{9}
}

func (x *Answer) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Answer) GetQuestionId() int64 {
	if x != nil {
		return x.QuestionId
	}
	return 0
}

func (x *Answer) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Answer) GetGroup() *GroupAnswer {
	if x != nil {
		return x.Group
	}
	return nil
}

func (x *Answer) GetFileUrl() string {
	if x != nil {
		return x.FileUrl
	}
	return ""
}

func (x *Answer) GetIsCorrect() bool {
	if x != nil {
		return x.IsCorrect
	}
	return false
}

func (x *Answer) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Answer) GetPoint() float64 {
	if x != nil {
		return x.Point
	}
	return 0
}

func (x *Answer) GetPositionX() int32 {
	if x != nil {
		return x.PositionX
	}
	return 0
}

func (x *Answer) GetPositionY() int32 {
	if x != nil {
		return x.PositionY
	}
	return 0
}

func (x *Answer) GetPositionWidth() int32 {
	if x != nil {
		return x.PositionWidth
	}
	return 0
}

func (x *Answer) GetPositionHeight() int32 {
	if x != nil {
		return x.PositionHeight
	}
	return 0
}

func (x *Answer) GetSortPosition() int32 {
	if x != nil {
		return x.SortPosition
	}
	return 0
}

func (x *Answer) GetCorrectPosition() int32 {
	if x != nil {
		return x.CorrectPosition
	}
	return 0
}

func (x *Answer) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Answer) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// Yêu cầu tạo Answer mới
type CreateAnswerRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	QuestionId      int64                  `protobuf:"varint,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`                 // ID câu hỏi (thay vì int32, dùng int64 cho phù hợp)
	Kind            string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`                                                // Loại câu trả lời
	Content         string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`                                          // Nội dung câu trả lời
	Group           *GroupAnswer           `protobuf:"bytes,4,opt,name=group,proto3" json:"group,omitempty"`                                              // Nhóm câu trả lời
	FileUrl         string                 `protobuf:"bytes,5,opt,name=file_url,json=fileUrl,proto3" json:"file_url,omitempty"`                           // URL của file (nếu có)
	IsCorrect       bool                   `protobuf:"varint,6,opt,name=is_correct,json=isCorrect,proto3" json:"is_correct,omitempty"`                    // Trạng thái đúng/sai
	Point           float64                `protobuf:"fixed64,7,opt,name=point,proto3" json:"point,omitempty"`                                            // Điểm cho câu trả lời
	PositionX       int32                  `protobuf:"varint,8,opt,name=position_x,json=positionX,proto3" json:"position_x,omitempty"`                    // Vị trí X
	PositionY       int32                  `protobuf:"varint,9,opt,name=position_y,json=positionY,proto3" json:"position_y,omitempty"`                    // Vị trí Y
	PositionWidth   int32                  `protobuf:"varint,10,opt,name=position_width,json=positionWidth,proto3" json:"position_width,omitempty"`       // Chiều rộng
	PositionHeight  int32                  `protobuf:"varint,11,opt,name=position_height,json=positionHeight,proto3" json:"position_height,omitempty"`    // Chiều cao
	SortPosition    int32                  `protobuf:"varint,12,opt,name=sort_position,json=sortPosition,proto3" json:"sort_position,omitempty"`          // Vị trí sắp xếp
	CorrectPosition int32                  `protobuf:"varint,13,opt,name=correct_position,json=correctPosition,proto3" json:"correct_position,omitempty"` // Vị trí chính xác
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateAnswerRequest) Reset() {
	*x = CreateAnswerRequest{}
	mi := &file_answer_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAnswerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAnswerRequest) ProtoMessage() {}

func (x *CreateAnswerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_answer_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAnswerRequest.ProtoReflect.Descriptor instead.
func (*CreateAnswerRequest) Descriptor() ([]byte, []int) {
	return file_answer_proto_rawDescGZIP(), []int{10}
}

func (x *CreateAnswerRequest) GetQuestionId() int64 {
	if x != nil {
		return x.QuestionId
	}
	return 0
}

func (x *CreateAnswerRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *CreateAnswerRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateAnswerRequest) GetGroup() *GroupAnswer {
	if x != nil {
		return x.Group
	}
	return nil
}

func (x *CreateAnswerRequest) GetFileUrl() string {
	if x != nil {
		return x.FileUrl
	}
	return ""
}

func (x *CreateAnswerRequest) GetIsCorrect() bool {
	if x != nil {
		return x.IsCorrect
	}
	return false
}

func (x *CreateAnswerRequest) GetPoint() float64 {
	if x != nil {
		return x.Point
	}
	return 0
}

func (x *CreateAnswerRequest) GetPositionX() int32 {
	if x != nil {
		return x.PositionX
	}
	return 0
}

func (x *CreateAnswerRequest) GetPositionY() int32 {
	if x != nil {
		return x.PositionY
	}
	return 0
}

func (x *CreateAnswerRequest) GetPositionWidth() int32 {
	if x != nil {
		return x.PositionWidth
	}
	return 0
}

func (x *CreateAnswerRequest) GetPositionHeight() int32 {
	if x != nil {
		return x.PositionHeight
	}
	return 0
}

func (x *CreateAnswerRequest) GetSortPosition() int32 {
	if x != nil {
		return x.SortPosition
	}
	return 0
}

func (x *CreateAnswerRequest) GetCorrectPosition() int32 {
	if x != nil {
		return x.CorrectPosition
	}
	return 0
}

// Yêu cầu cập nhật Answer
type UpdateAnswerRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                                   // ID câu trả lời
	QuestionId      int64                  `protobuf:"varint,2,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`                 // ID câu hỏi (sử dụng int64)
	Kind            string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`                                                // Loại câu trả lời
	Content         string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`                                          // Nội dung câu trả lời
	Group           *GroupAnswer           `protobuf:"bytes,5,opt,name=group,proto3" json:"group,omitempty"`                                              // Nhóm câu trả lời
	FileUrl         string                 `protobuf:"bytes,6,opt,name=file_url,json=fileUrl,proto3" json:"file_url,omitempty"`                           // URL của file (nếu có)
	IsCorrect       bool                   `protobuf:"varint,7,opt,name=is_correct,json=isCorrect,proto3" json:"is_correct,omitempty"`                    // Trạng thái đúng/sai
	Point           float64                `protobuf:"fixed64,8,opt,name=point,proto3" json:"point,omitempty"`                                            // Điểm cho câu trả lời
	PositionX       int32                  `protobuf:"varint,9,opt,name=position_x,json=positionX,proto3" json:"position_x,omitempty"`                    // Vị trí X
	PositionY       int32                  `protobuf:"varint,10,opt,name=position_y,json=positionY,proto3" json:"position_y,omitempty"`                   // Vị trí Y
	PositionWidth   int32                  `protobuf:"varint,11,opt,name=position_width,json=positionWidth,proto3" json:"position_width,omitempty"`       // Chiều rộng
	PositionHeight  int32                  `protobuf:"varint,12,opt,name=position_height,json=positionHeight,proto3" json:"position_height,omitempty"`    // Chiều cao
	SortPosition    int32                  `protobuf:"varint,13,opt,name=sort_position,json=sortPosition,proto3" json:"sort_position,omitempty"`          // Vị trí sắp xếp
	CorrectPosition int32                  `protobuf:"varint,14,opt,name=correct_position,json=correctPosition,proto3" json:"correct_position,omitempty"` // Vị trí chính xác
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateAnswerRequest) Reset() {
	*x = UpdateAnswerRequest{}
	mi := &file_answer_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAnswerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAnswerRequest) ProtoMessage() {}

func (x *UpdateAnswerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_answer_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAnswerRequest.ProtoReflect.Descriptor instead.
func (*UpdateAnswerRequest) Descriptor() ([]byte, []int) {
	return file_answer_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateAnswerRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateAnswerRequest) GetQuestionId() int64 {
	if x != nil {
		return x.QuestionId
	}
	return 0
}

func (x *UpdateAnswerRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *UpdateAnswerRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *UpdateAnswerRequest) GetGroup() *GroupAnswer {
	if x != nil {
		return x.Group
	}
	return nil
}

func (x *UpdateAnswerRequest) GetFileUrl() string {
	if x != nil {
		return x.FileUrl
	}
	return ""
}

func (x *UpdateAnswerRequest) GetIsCorrect() bool {
	if x != nil {
		return x.IsCorrect
	}
	return false
}

func (x *UpdateAnswerRequest) GetPoint() float64 {
	if x != nil {
		return x.Point
	}
	return 0
}

func (x *UpdateAnswerRequest) GetPositionX() int32 {
	if x != nil {
		return x.PositionX
	}
	return 0
}

func (x *UpdateAnswerRequest) GetPositionY() int32 {
	if x != nil {
		return x.PositionY
	}
	return 0
}

func (x *UpdateAnswerRequest) GetPositionWidth() int32 {
	if x != nil {
		return x.PositionWidth
	}
	return 0
}

func (x *UpdateAnswerRequest) GetPositionHeight() int32 {
	if x != nil {
		return x.PositionHeight
	}
	return 0
}

func (x *UpdateAnswerRequest) GetSortPosition() int32 {
	if x != nil {
		return x.SortPosition
	}
	return 0
}

func (x *UpdateAnswerRequest) GetCorrectPosition() int32 {
	if x != nil {
		return x.CorrectPosition
	}
	return 0
}

// Danh sách các Answer
type AnswerList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contents      []*Answer              `protobuf:"bytes,1,rep,name=contents,proto3" json:"contents,omitempty"` // Mảng câu trả lời
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnswerList) Reset() {
	*x = AnswerList{}
	mi := &file_answer_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnswerList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerList) ProtoMessage() {}

func (x *AnswerList) ProtoReflect() protoreflect.Message {
	mi := &file_answer_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerList.ProtoReflect.Descriptor instead.
func (*AnswerList) Descriptor() ([]byte, []int) {
	return file_answer_proto_rawDescGZIP(), []int{12}
}

func (x *AnswerList) GetContents() []*Answer {
	if x != nil {
		return x.Contents
	}
	return nil
}

var File_answer_proto protoreflect.FileDescriptor

const file_answer_proto_rawDesc = "" +
	"\n" +
	"\fanswer.proto\x12\x04prot\"G\n" +
	"\vMediaAnswer\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x12\n" +
	"\x04file\x18\x03 \x01(\fR\x04file\"Z\n" +
	"\vGroupAnswer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12'\n" +
	"\x05media\x18\x03 \x01(\v2\x11.prot.MediaAnswerR\x05media\"\xe3\x01\n" +
	"\rAnswerContent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x14\n" +
	"\x05point\x18\x03 \x01(\x01R\x05point\x12'\n" +
	"\x05media\x18\x04 \x01(\v2\x11.prot.MediaAnswerR\x05media\x12\x1d\n" +
	"\n" +
	"is_correct\x18\x05 \x01(\bR\tisCorrect\x12)\n" +
	"\x10correct_position\x18\x06 \x01(\x05R\x0fcorrectPosition\x12%\n" +
	"\x0egroup_position\x18\a \x01(\x05R\rgroupPosition\"L\n" +
	"\rSourceContent\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12'\n" +
	"\x05media\x18\x02 \x01(\v2\x11.prot.MediaAnswerR\x05media\"t\n" +
	"\fAnswerSource\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12-\n" +
	"\acontent\x18\x02 \x01(\v2\x13.prot.SourceContentR\acontent\x12%\n" +
	"\x0egroup_position\x18\x03 \x01(\x05R\rgroupPosition\"M\n" +
	"\fAnswerTarget\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12-\n" +
	"\acontent\x18\x02 \x01(\v2\x13.prot.AnswerContentR\acontent\"K\n" +
	"\x11AnswerCoordinates\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\x12\f\n" +
	"\x01w\x18\x03 \x01(\x05R\x01w\x12\f\n" +
	"\x01h\x18\x04 \x01(\x05R\x01h\"X\n" +
	"\vAnswerBlank\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x129\n" +
	"\vcoordinates\x18\x02 \x01(\v2\x17.prot.AnswerCoordinatesR\vcoordinates\"~\n" +
	"\rGroupPosition\x12\x1a\n" +
	"\bposition\x18\x01 \x01(\x05R\bposition\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12'\n" +
	"\x05media\x18\x04 \x01(\v2\x11.prot.MediaAnswerR\x05media\"\xfc\x03\n" +
	"\x06Answer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\vquestion_id\x18\x02 \x01(\x03R\n" +
	"questionId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12'\n" +
	"\x05group\x18\x04 \x01(\v2\x11.prot.GroupAnswerR\x05group\x12\x19\n" +
	"\bfile_url\x18\x05 \x01(\tR\afileUrl\x12\x1d\n" +
	"\n" +
	"is_correct\x18\x06 \x01(\bR\tisCorrect\x12\x12\n" +
	"\x04kind\x18\a \x01(\tR\x04kind\x12\x14\n" +
	"\x05point\x18\b \x01(\x01R\x05point\x12\x1d\n" +
	"\n" +
	"position_x\x18\t \x01(\x05R\tpositionX\x12\x1d\n" +
	"\n" +
	"position_y\x18\n" +
	" \x01(\x05R\tpositionY\x12%\n" +
	"\x0eposition_width\x18\v \x01(\x05R\rpositionWidth\x12'\n" +
	"\x0fposition_height\x18\f \x01(\x05R\x0epositionHeight\x12#\n" +
	"\rsort_position\x18\r \x01(\x05R\fsortPosition\x12)\n" +
	"\x10correct_position\x18\x0e \x01(\x05R\x0fcorrectPosition\x12\x1d\n" +
	"\n" +
	"created_at\x18\x0f \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x10 \x01(\tR\tupdatedAt\"\xbb\x03\n" +
	"\x13CreateAnswerRequest\x12\x1f\n" +
	"\vquestion_id\x18\x01 \x01(\x03R\n" +
	"questionId\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12'\n" +
	"\x05group\x18\x04 \x01(\v2\x11.prot.GroupAnswerR\x05group\x12\x19\n" +
	"\bfile_url\x18\x05 \x01(\tR\afileUrl\x12\x1d\n" +
	"\n" +
	"is_correct\x18\x06 \x01(\bR\tisCorrect\x12\x14\n" +
	"\x05point\x18\a \x01(\x01R\x05point\x12\x1d\n" +
	"\n" +
	"position_x\x18\b \x01(\x05R\tpositionX\x12\x1d\n" +
	"\n" +
	"position_y\x18\t \x01(\x05R\tpositionY\x12%\n" +
	"\x0eposition_width\x18\n" +
	" \x01(\x05R\rpositionWidth\x12'\n" +
	"\x0fposition_height\x18\v \x01(\x05R\x0epositionHeight\x12#\n" +
	"\rsort_position\x18\f \x01(\x05R\fsortPosition\x12)\n" +
	"\x10correct_position\x18\r \x01(\x05R\x0fcorrectPosition\"\xcb\x03\n" +
	"\x13UpdateAnswerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\vquestion_id\x18\x02 \x01(\x03R\n" +
	"questionId\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12'\n" +
	"\x05group\x18\x05 \x01(\v2\x11.prot.GroupAnswerR\x05group\x12\x19\n" +
	"\bfile_url\x18\x06 \x01(\tR\afileUrl\x12\x1d\n" +
	"\n" +
	"is_correct\x18\a \x01(\bR\tisCorrect\x12\x14\n" +
	"\x05point\x18\b \x01(\x01R\x05point\x12\x1d\n" +
	"\n" +
	"position_x\x18\t \x01(\x05R\tpositionX\x12\x1d\n" +
	"\n" +
	"position_y\x18\n" +
	" \x01(\x05R\tpositionY\x12%\n" +
	"\x0eposition_width\x18\v \x01(\x05R\rpositionWidth\x12'\n" +
	"\x0fposition_height\x18\f \x01(\x05R\x0epositionHeight\x12#\n" +
	"\rsort_position\x18\r \x01(\x05R\fsortPosition\x12)\n" +
	"\x10correct_position\x18\x0e \x01(\x05R\x0fcorrectPosition\"6\n" +
	"\n" +
	"AnswerList\x12(\n" +
	"\bcontents\x18\x01 \x03(\v2\f.prot.AnswerR\bcontentsB\x13Z\x11be-Clever School/admin/protb\x06proto3"

var (
	file_answer_proto_rawDescOnce sync.Once
	file_answer_proto_rawDescData []byte
)

func file_answer_proto_rawDescGZIP() []byte {
	file_answer_proto_rawDescOnce.Do(func() {
		file_answer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_answer_proto_rawDesc), len(file_answer_proto_rawDesc)))
	})
	return file_answer_proto_rawDescData
}

var file_answer_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_answer_proto_goTypes = []any{
	(*MediaAnswer)(nil),         // 0: prot.MediaAnswer
	(*GroupAnswer)(nil),         // 1: prot.GroupAnswer
	(*AnswerContent)(nil),       // 2: prot.AnswerContent
	(*SourceContent)(nil),       // 3: prot.SourceContent
	(*AnswerSource)(nil),        // 4: prot.AnswerSource
	(*AnswerTarget)(nil),        // 5: prot.AnswerTarget
	(*AnswerCoordinates)(nil),   // 6: prot.AnswerCoordinates
	(*AnswerBlank)(nil),         // 7: prot.AnswerBlank
	(*GroupPosition)(nil),       // 8: prot.GroupPosition
	(*Answer)(nil),              // 9: prot.Answer
	(*CreateAnswerRequest)(nil), // 10: prot.CreateAnswerRequest
	(*UpdateAnswerRequest)(nil), // 11: prot.UpdateAnswerRequest
	(*AnswerList)(nil),          // 12: prot.AnswerList
}
var file_answer_proto_depIdxs = []int32{
	0,  // 0: prot.GroupAnswer.media:type_name -> prot.MediaAnswer
	0,  // 1: prot.AnswerContent.media:type_name -> prot.MediaAnswer
	0,  // 2: prot.SourceContent.media:type_name -> prot.MediaAnswer
	3,  // 3: prot.AnswerSource.content:type_name -> prot.SourceContent
	2,  // 4: prot.AnswerTarget.content:type_name -> prot.AnswerContent
	6,  // 5: prot.AnswerBlank.coordinates:type_name -> prot.AnswerCoordinates
	0,  // 6: prot.GroupPosition.media:type_name -> prot.MediaAnswer
	1,  // 7: prot.Answer.group:type_name -> prot.GroupAnswer
	1,  // 8: prot.CreateAnswerRequest.group:type_name -> prot.GroupAnswer
	1,  // 9: prot.UpdateAnswerRequest.group:type_name -> prot.GroupAnswer
	9,  // 10: prot.AnswerList.contents:type_name -> prot.Answer
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_answer_proto_init() }
func file_answer_proto_init() {
	if File_answer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_answer_proto_rawDesc), len(file_answer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_answer_proto_goTypes,
		DependencyIndexes: file_answer_proto_depIdxs,
		MessageInfos:      file_answer_proto_msgTypes,
	}.Build()
	File_answer_proto = out.File
	file_answer_proto_goTypes = nil
	file_answer_proto_depIdxs = nil
}
