// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: chapter.proto

package prot

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Chapter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CourseId      int64                  `protobuf:"varint,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	SortPosition  string                 `protobuf:"bytes,5,opt,name=sort_position,json=sortPosition,proto3" json:"sort_position,omitempty"`
	Status        bool                   `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	Lessons       []*LessonInfo          `protobuf:"bytes,7,rep,name=lessons,proto3" json:"lessons,omitempty"`
	ObjectTitle   string                 `protobuf:"bytes,8,opt,name=object_title,json=objectTitle,proto3" json:"object_title,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ProgramId     int64                  `protobuf:"varint,11,opt,name=program_id,json=programId,proto3" json:"program_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chapter) Reset() {
	*x = Chapter{}
	mi := &file_chapter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chapter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chapter) ProtoMessage() {}

func (x *Chapter) ProtoReflect() protoreflect.Message {
	mi := &file_chapter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chapter.ProtoReflect.Descriptor instead.
func (*Chapter) Descriptor() ([]byte, []int) {
	return file_chapter_proto_rawDescGZIP(), []int{0}
}

func (x *Chapter) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Chapter) GetCourseId() int64 {
	if x != nil {
		return x.CourseId
	}
	return 0
}

func (x *Chapter) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Chapter) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Chapter) GetSortPosition() string {
	if x != nil {
		return x.SortPosition
	}
	return ""
}

func (x *Chapter) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *Chapter) GetLessons() []*LessonInfo {
	if x != nil {
		return x.Lessons
	}
	return nil
}

func (x *Chapter) GetObjectTitle() string {
	if x != nil {
		return x.ObjectTitle
	}
	return ""
}

func (x *Chapter) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Chapter) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Chapter) GetProgramId() int64 {
	if x != nil {
		return x.ProgramId
	}
	return 0
}

type GetChapterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChapterRequest) Reset() {
	*x = GetChapterRequest{}
	mi := &file_chapter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChapterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChapterRequest) ProtoMessage() {}

func (x *GetChapterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chapter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChapterRequest.ProtoReflect.Descriptor instead.
func (*GetChapterRequest) Descriptor() ([]byte, []int) {
	return file_chapter_proto_rawDescGZIP(), []int{1}
}

func (x *GetChapterRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ChapterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chapter       *Chapter               `protobuf:"bytes,1,opt,name=chapter,proto3" json:"chapter,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChapterResponse) Reset() {
	*x = ChapterResponse{}
	mi := &file_chapter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChapterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChapterResponse) ProtoMessage() {}

func (x *ChapterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chapter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChapterResponse.ProtoReflect.Descriptor instead.
func (*ChapterResponse) Descriptor() ([]byte, []int) {
	return file_chapter_proto_rawDescGZIP(), []int{2}
}

func (x *ChapterResponse) GetChapter() *Chapter {
	if x != nil {
		return x.Chapter
	}
	return nil
}

func (x *ChapterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListChaptersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChaptersRequest) Reset() {
	*x = ListChaptersRequest{}
	mi := &file_chapter_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChaptersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChaptersRequest) ProtoMessage() {}

func (x *ListChaptersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chapter_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChaptersRequest.ProtoReflect.Descriptor instead.
func (*ListChaptersRequest) Descriptor() ([]byte, []int) {
	return file_chapter_proto_rawDescGZIP(), []int{3}
}

type ChapterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CourseId      int64                  `protobuf:"varint,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	SortPosition  string                 `protobuf:"bytes,5,opt,name=sort_position,json=sortPosition,proto3" json:"sort_position,omitempty"`
	Status        bool                   `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	Lessons       []*LessonInfo          `protobuf:"bytes,7,rep,name=lessons,proto3" json:"lessons,omitempty"`
	ObjectTitle   string                 `protobuf:"bytes,8,opt,name=object_title,json=objectTitle,proto3" json:"object_title,omitempty"`
	ProgramId     int64                  `protobuf:"varint,9,opt,name=program_id,json=programId,proto3" json:"program_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChapterRequest) Reset() {
	*x = ChapterRequest{}
	mi := &file_chapter_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChapterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChapterRequest) ProtoMessage() {}

func (x *ChapterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chapter_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChapterRequest.ProtoReflect.Descriptor instead.
func (*ChapterRequest) Descriptor() ([]byte, []int) {
	return file_chapter_proto_rawDescGZIP(), []int{4}
}

func (x *ChapterRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ChapterRequest) GetCourseId() int64 {
	if x != nil {
		return x.CourseId
	}
	return 0
}

func (x *ChapterRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ChapterRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ChapterRequest) GetSortPosition() string {
	if x != nil {
		return x.SortPosition
	}
	return ""
}

func (x *ChapterRequest) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *ChapterRequest) GetLessons() []*LessonInfo {
	if x != nil {
		return x.Lessons
	}
	return nil
}

func (x *ChapterRequest) GetObjectTitle() string {
	if x != nil {
		return x.ObjectTitle
	}
	return ""
}

func (x *ChapterRequest) GetProgramId() int64 {
	if x != nil {
		return x.ProgramId
	}
	return 0
}

type ChapterIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChapterIDRequest) Reset() {
	*x = ChapterIDRequest{}
	mi := &file_chapter_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChapterIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChapterIDRequest) ProtoMessage() {}

func (x *ChapterIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chapter_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChapterIDRequest.ProtoReflect.Descriptor instead.
func (*ChapterIDRequest) Descriptor() ([]byte, []int) {
	return file_chapter_proto_rawDescGZIP(), []int{5}
}

func (x *ChapterIDRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ChaptersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chapters      []*Chapter             `protobuf:"bytes,1,rep,name=chapters,proto3" json:"chapters,omitempty"`
	TotalCount    uint64                 `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChaptersResponse) Reset() {
	*x = ChaptersResponse{}
	mi := &file_chapter_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChaptersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChaptersResponse) ProtoMessage() {}

func (x *ChaptersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chapter_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChaptersResponse.ProtoReflect.Descriptor instead.
func (*ChaptersResponse) Descriptor() ([]byte, []int) {
	return file_chapter_proto_rawDescGZIP(), []int{6}
}

func (x *ChaptersResponse) GetChapters() []*Chapter {
	if x != nil {
		return x.Chapters
	}
	return nil
}

func (x *ChaptersResponse) GetTotalCount() uint64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type LessonSort struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LessonSort) Reset() {
	*x = LessonSort{}
	mi := &file_chapter_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LessonSort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LessonSort) ProtoMessage() {}

func (x *LessonSort) ProtoReflect() protoreflect.Message {
	mi := &file_chapter_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LessonSort.ProtoReflect.Descriptor instead.
func (*LessonSort) Descriptor() ([]byte, []int) {
	return file_chapter_proto_rawDescGZIP(), []int{7}
}

func (x *LessonSort) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ChapterLessonSort struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lessons       []*LessonSort          `protobuf:"bytes,1,rep,name=lessons,proto3" json:"lessons,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChapterLessonSort) Reset() {
	*x = ChapterLessonSort{}
	mi := &file_chapter_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChapterLessonSort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChapterLessonSort) ProtoMessage() {}

func (x *ChapterLessonSort) ProtoReflect() protoreflect.Message {
	mi := &file_chapter_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChapterLessonSort.ProtoReflect.Descriptor instead.
func (*ChapterLessonSort) Descriptor() ([]byte, []int) {
	return file_chapter_proto_rawDescGZIP(), []int{8}
}

func (x *ChapterLessonSort) GetLessons() []*LessonSort {
	if x != nil {
		return x.Lessons
	}
	return nil
}

var File_chapter_proto protoreflect.FileDescriptor

const file_chapter_proto_rawDesc = "" +
	"\n" +
	"\rchapter.proto\x12\x04prot\x1a\flesson.proto\"\xd7\x02\n" +
	"\aChapter\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\x03R\bcourseId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12#\n" +
	"\rsort_position\x18\x05 \x01(\tR\fsortPosition\x12\x16\n" +
	"\x06status\x18\x06 \x01(\bR\x06status\x12*\n" +
	"\alessons\x18\a \x03(\v2\x10.prot.LessonInfoR\alessons\x12!\n" +
	"\fobject_title\x18\b \x01(\tR\vobjectTitle\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\tR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"program_id\x18\v \x01(\x03R\tprogramId\"#\n" +
	"\x11GetChapterRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"T\n" +
	"\x0fChapterResponse\x12'\n" +
	"\achapter\x18\x01 \x01(\v2\r.prot.ChapterR\achapter\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x15\n" +
	"\x13ListChaptersRequest\"\xa0\x02\n" +
	"\x0eChapterRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\x03R\bcourseId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12#\n" +
	"\rsort_position\x18\x05 \x01(\tR\fsortPosition\x12\x16\n" +
	"\x06status\x18\x06 \x01(\bR\x06status\x12*\n" +
	"\alessons\x18\a \x03(\v2\x10.prot.LessonInfoR\alessons\x12!\n" +
	"\fobject_title\x18\b \x01(\tR\vobjectTitle\x12\x1d\n" +
	"\n" +
	"program_id\x18\t \x01(\x03R\tprogramId\"\"\n" +
	"\x10ChapterIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"^\n" +
	"\x10ChaptersResponse\x12)\n" +
	"\bchapters\x18\x01 \x03(\v2\r.prot.ChapterR\bchapters\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x04R\n" +
	"totalCount\"\x1c\n" +
	"\n" +
	"LessonSort\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"?\n" +
	"\x11ChapterLessonSort\x12*\n" +
	"\alessons\x18\x01 \x03(\v2\x10.prot.LessonSortR\alessonsB\rZ\vbe-lms/protb\x06proto3"

var (
	file_chapter_proto_rawDescOnce sync.Once
	file_chapter_proto_rawDescData []byte
)

func file_chapter_proto_rawDescGZIP() []byte {
	file_chapter_proto_rawDescOnce.Do(func() {
		file_chapter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chapter_proto_rawDesc), len(file_chapter_proto_rawDesc)))
	})
	return file_chapter_proto_rawDescData
}

var file_chapter_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_chapter_proto_goTypes = []any{
	(*Chapter)(nil),             // 0: prot.Chapter
	(*GetChapterRequest)(nil),   // 1: prot.GetChapterRequest
	(*ChapterResponse)(nil),     // 2: prot.ChapterResponse
	(*ListChaptersRequest)(nil), // 3: prot.ListChaptersRequest
	(*ChapterRequest)(nil),      // 4: prot.ChapterRequest
	(*ChapterIDRequest)(nil),    // 5: prot.ChapterIDRequest
	(*ChaptersResponse)(nil),    // 6: prot.ChaptersResponse
	(*LessonSort)(nil),          // 7: prot.LessonSort
	(*ChapterLessonSort)(nil),   // 8: prot.ChapterLessonSort
	(*LessonInfo)(nil),          // 9: prot.LessonInfo
}
var file_chapter_proto_depIdxs = []int32{
	9, // 0: prot.Chapter.lessons:type_name -> prot.LessonInfo
	0, // 1: prot.ChapterResponse.chapter:type_name -> prot.Chapter
	9, // 2: prot.ChapterRequest.lessons:type_name -> prot.LessonInfo
	0, // 3: prot.ChaptersResponse.chapters:type_name -> prot.Chapter
	7, // 4: prot.ChapterLessonSort.lessons:type_name -> prot.LessonSort
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_chapter_proto_init() }
func file_chapter_proto_init() {
	if File_chapter_proto != nil {
		return
	}
	file_lesson_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chapter_proto_rawDesc), len(file_chapter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chapter_proto_goTypes,
		DependencyIndexes: file_chapter_proto_depIdxs,
		MessageInfos:      file_chapter_proto_msgTypes,
	}.Build()
	File_chapter_proto = out.File
	file_chapter_proto_goTypes = nil
	file_chapter_proto_depIdxs = nil
}
