// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: chat_reactions.proto

package prot

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Chat Message Reaction Messages
type ChatMessageReactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Emoji         string                 `protobuf:"bytes,1,opt,name=emoji,proto3" json:"emoji,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessageReactionRequest) Reset() {
	*x = ChatMessageReactionRequest{}
	mi := &file_chat_reactions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessageReactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessageReactionRequest) ProtoMessage() {}

func (x *ChatMessageReactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_reactions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessageReactionRequest.ProtoReflect.Descriptor instead.
func (*ChatMessageReactionRequest) Descriptor() ([]byte, []int) {
	return file_chat_reactions_proto_rawDescGZIP(), []int{0}
}

func (x *ChatMessageReactionRequest) GetEmoji() string {
	if x != nil {
		return x.Emoji
	}
	return ""
}

type ReactionSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Emoji         string                 `protobuf:"bytes,1,opt,name=emoji,proto3" json:"emoji,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Users         []string               `protobuf:"bytes,3,rep,name=users,proto3" json:"users,omitempty"`
	UserCounts    map[string]int32       `protobuf:"bytes,4,rep,name=user_counts,json=userCounts,proto3" json:"user_counts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReactionSummary) Reset() {
	*x = ReactionSummary{}
	mi := &file_chat_reactions_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReactionSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReactionSummary) ProtoMessage() {}

func (x *ReactionSummary) ProtoReflect() protoreflect.Message {
	mi := &file_chat_reactions_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReactionSummary.ProtoReflect.Descriptor instead.
func (*ReactionSummary) Descriptor() ([]byte, []int) {
	return file_chat_reactions_proto_rawDescGZIP(), []int{1}
}

func (x *ReactionSummary) GetEmoji() string {
	if x != nil {
		return x.Emoji
	}
	return ""
}

func (x *ReactionSummary) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ReactionSummary) GetUsers() []string {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *ReactionSummary) GetUserCounts() map[string]int32 {
	if x != nil {
		return x.UserCounts
	}
	return nil
}

type ChatMessageReactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Reactions     []*ReactionSummary     `protobuf:"bytes,2,rep,name=reactions,proto3" json:"reactions,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessageReactionResponse) Reset() {
	*x = ChatMessageReactionResponse{}
	mi := &file_chat_reactions_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessageReactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessageReactionResponse) ProtoMessage() {}

func (x *ChatMessageReactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_reactions_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessageReactionResponse.ProtoReflect.Descriptor instead.
func (*ChatMessageReactionResponse) Descriptor() ([]byte, []int) {
	return file_chat_reactions_proto_rawDescGZIP(), []int{2}
}

func (x *ChatMessageReactionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ChatMessageReactionResponse) GetReactions() []*ReactionSummary {
	if x != nil {
		return x.Reactions
	}
	return nil
}

func (x *ChatMessageReactionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AddReactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      uint64                 `protobuf:"varint,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	MessageId     uint64                 `protobuf:"varint,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Emoji         string                 `protobuf:"bytes,3,opt,name=emoji,proto3" json:"emoji,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddReactionRequest) Reset() {
	*x = AddReactionRequest{}
	mi := &file_chat_reactions_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddReactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddReactionRequest) ProtoMessage() {}

func (x *AddReactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_reactions_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddReactionRequest.ProtoReflect.Descriptor instead.
func (*AddReactionRequest) Descriptor() ([]byte, []int) {
	return file_chat_reactions_proto_rawDescGZIP(), []int{3}
}

func (x *AddReactionRequest) GetCourseId() uint64 {
	if x != nil {
		return x.CourseId
	}
	return 0
}

func (x *AddReactionRequest) GetMessageId() uint64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *AddReactionRequest) GetEmoji() string {
	if x != nil {
		return x.Emoji
	}
	return ""
}

type RemoveReactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      uint64                 `protobuf:"varint,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	MessageId     uint64                 `protobuf:"varint,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Emoji         string                 `protobuf:"bytes,3,opt,name=emoji,proto3" json:"emoji,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveReactionRequest) Reset() {
	*x = RemoveReactionRequest{}
	mi := &file_chat_reactions_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveReactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveReactionRequest) ProtoMessage() {}

func (x *RemoveReactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_reactions_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveReactionRequest.ProtoReflect.Descriptor instead.
func (*RemoveReactionRequest) Descriptor() ([]byte, []int) {
	return file_chat_reactions_proto_rawDescGZIP(), []int{4}
}

func (x *RemoveReactionRequest) GetCourseId() uint64 {
	if x != nil {
		return x.CourseId
	}
	return 0
}

func (x *RemoveReactionRequest) GetMessageId() uint64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *RemoveReactionRequest) GetEmoji() string {
	if x != nil {
		return x.Emoji
	}
	return ""
}

type GetReactionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      uint64                 `protobuf:"varint,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	MessageId     uint64                 `protobuf:"varint,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReactionsRequest) Reset() {
	*x = GetReactionsRequest{}
	mi := &file_chat_reactions_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReactionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReactionsRequest) ProtoMessage() {}

func (x *GetReactionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_reactions_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReactionsRequest.ProtoReflect.Descriptor instead.
func (*GetReactionsRequest) Descriptor() ([]byte, []int) {
	return file_chat_reactions_proto_rawDescGZIP(), []int{5}
}

func (x *GetReactionsRequest) GetCourseId() uint64 {
	if x != nil {
		return x.CourseId
	}
	return 0
}

func (x *GetReactionsRequest) GetMessageId() uint64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

var File_chat_reactions_proto protoreflect.FileDescriptor

const file_chat_reactions_proto_rawDesc = "" +
	"\n" +
	"\x14chat_reactions.proto\x12\x04prot\"2\n" +
	"\x1aChatMessageReactionRequest\x12\x14\n" +
	"\x05emoji\x18\x01 \x01(\tR\x05emoji\"\xda\x01\n" +
	"\x0fReactionSummary\x12\x14\n" +
	"\x05emoji\x18\x01 \x01(\tR\x05emoji\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\x12\x14\n" +
	"\x05users\x18\x03 \x03(\tR\x05users\x12F\n" +
	"\vuser_counts\x18\x04 \x03(\v2%.prot.ReactionSummary.UserCountsEntryR\n" +
	"userCounts\x1a=\n" +
	"\x0fUserCountsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\x86\x01\n" +
	"\x1bChatMessageReactionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x123\n" +
	"\treactions\x18\x02 \x03(\v2\x15.prot.ReactionSummaryR\treactions\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"f\n" +
	"\x12AddReactionRequest\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\x04R\bcourseId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\x04R\tmessageId\x12\x14\n" +
	"\x05emoji\x18\x03 \x01(\tR\x05emoji\"i\n" +
	"\x15RemoveReactionRequest\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\x04R\bcourseId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\x04R\tmessageId\x12\x14\n" +
	"\x05emoji\x18\x03 \x01(\tR\x05emoji\"Q\n" +
	"\x13GetReactionsRequest\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\x04R\bcourseId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\x04R\tmessageIdB\rZ\vbe-Clever School/protb\x06proto3"

var (
	file_chat_reactions_proto_rawDescOnce sync.Once
	file_chat_reactions_proto_rawDescData []byte
)

func file_chat_reactions_proto_rawDescGZIP() []byte {
	file_chat_reactions_proto_rawDescOnce.Do(func() {
		file_chat_reactions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chat_reactions_proto_rawDesc), len(file_chat_reactions_proto_rawDesc)))
	})
	return file_chat_reactions_proto_rawDescData
}

var file_chat_reactions_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_chat_reactions_proto_goTypes = []any{
	(*ChatMessageReactionRequest)(nil),  // 0: prot.ChatMessageReactionRequest
	(*ReactionSummary)(nil),             // 1: prot.ReactionSummary
	(*ChatMessageReactionResponse)(nil), // 2: prot.ChatMessageReactionResponse
	(*AddReactionRequest)(nil),          // 3: prot.AddReactionRequest
	(*RemoveReactionRequest)(nil),       // 4: prot.RemoveReactionRequest
	(*GetReactionsRequest)(nil),         // 5: prot.GetReactionsRequest
	nil,                                 // 6: prot.ReactionSummary.UserCountsEntry
}
var file_chat_reactions_proto_depIdxs = []int32{
	6, // 0: prot.ReactionSummary.user_counts:type_name -> prot.ReactionSummary.UserCountsEntry
	1, // 1: prot.ChatMessageReactionResponse.reactions:type_name -> prot.ReactionSummary
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_chat_reactions_proto_init() }
func file_chat_reactions_proto_init() {
	if File_chat_reactions_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chat_reactions_proto_rawDesc), len(file_chat_reactions_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chat_reactions_proto_goTypes,
		DependencyIndexes: file_chat_reactions_proto_depIdxs,
		MessageInfos:      file_chat_reactions_proto_msgTypes,
	}.Build()
	File_chat_reactions_proto = out.File
	file_chat_reactions_proto_goTypes = nil
	file_chat_reactions_proto_depIdxs = nil
}
