// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: course_ref_study_shift.proto

package prot

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CourseRefStudyShift struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CourseId      int64                  `protobuf:"varint,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	ShiftId       int64                  `protobuf:"varint,3,opt,name=shift_id,json=shiftId,proto3" json:"shift_id,omitempty"`
	DayOfWeek     int32                  `protobuf:"varint,4,opt,name=day_of_week,json=dayOfWeek,proto3" json:"day_of_week,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Shift         *StudyShift            `protobuf:"bytes,6,opt,name=shift,proto3" json:"shift,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CourseRefStudyShift) Reset() {
	*x = CourseRefStudyShift{}
	mi := &file_course_ref_study_shift_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CourseRefStudyShift) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourseRefStudyShift) ProtoMessage() {}

func (x *CourseRefStudyShift) ProtoReflect() protoreflect.Message {
	mi := &file_course_ref_study_shift_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourseRefStudyShift.ProtoReflect.Descriptor instead.
func (*CourseRefStudyShift) Descriptor() ([]byte, []int) {
	return file_course_ref_study_shift_proto_rawDescGZIP(), []int{0}
}

func (x *CourseRefStudyShift) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CourseRefStudyShift) GetCourseId() int64 {
	if x != nil {
		return x.CourseId
	}
	return 0
}

func (x *CourseRefStudyShift) GetShiftId() int64 {
	if x != nil {
		return x.ShiftId
	}
	return 0
}

func (x *CourseRefStudyShift) GetDayOfWeek() int32 {
	if x != nil {
		return x.DayOfWeek
	}
	return 0
}

func (x *CourseRefStudyShift) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *CourseRefStudyShift) GetShift() *StudyShift {
	if x != nil {
		return x.Shift
	}
	return nil
}

var File_course_ref_study_shift_proto protoreflect.FileDescriptor

const file_course_ref_study_shift_proto_rawDesc = "" +
	"\n" +
	"\x1ccourse_ref_study_shift.proto\x12\x04prot\x1a\x11study_shift.proto\"\xc4\x01\n" +
	"\x13CourseRefStudyShift\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\x03R\bcourseId\x12\x19\n" +
	"\bshift_id\x18\x03 \x01(\x03R\ashiftId\x12\x1e\n" +
	"\vday_of_week\x18\x04 \x01(\x05R\tdayOfWeek\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12&\n" +
	"\x05shift\x18\x06 \x01(\v2\x10.prot.StudyShiftR\x05shiftB\rZ\vbe-cleverschool/protb\x06proto3"

var (
	file_course_ref_study_shift_proto_rawDescOnce sync.Once
	file_course_ref_study_shift_proto_rawDescData []byte
)

func file_course_ref_study_shift_proto_rawDescGZIP() []byte {
	file_course_ref_study_shift_proto_rawDescOnce.Do(func() {
		file_course_ref_study_shift_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_course_ref_study_shift_proto_rawDesc), len(file_course_ref_study_shift_proto_rawDesc)))
	})
	return file_course_ref_study_shift_proto_rawDescData
}

var file_course_ref_study_shift_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_course_ref_study_shift_proto_goTypes = []any{
	(*CourseRefStudyShift)(nil), // 0: prot.CourseRefStudyShift
	(*StudyShift)(nil),          // 1: prot.StudyShift
}
var file_course_ref_study_shift_proto_depIdxs = []int32{
	1, // 0: prot.CourseRefStudyShift.shift:type_name -> prot.StudyShift
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_course_ref_study_shift_proto_init() }
func file_course_ref_study_shift_proto_init() {
	if File_course_ref_study_shift_proto != nil {
		return
	}
	file_study_shift_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_course_ref_study_shift_proto_rawDesc), len(file_course_ref_study_shift_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_course_ref_study_shift_proto_goTypes,
		DependencyIndexes: file_course_ref_study_shift_proto_depIdxs,
		MessageInfos:      file_course_ref_study_shift_proto_msgTypes,
	}.Build()
	File_course_ref_study_shift_proto = out.File
	file_course_ref_study_shift_proto_goTypes = nil
	file_course_ref_study_shift_proto_depIdxs = nil
}

