syntax = "proto3";

package prot;

option go_package = "be-cleverschool/prot";

message DashboardReportSchool {
  int64 id = 1;
  int64 school_id = 2;
  string school_name = 3;
  int64 total_students = 4;
  int64 total_teachers = 5;
  int64 active_teachers_from_sep8 = 6;
  int64 active_students_from_sep15 = 7;
  int64 students_completed_homework_from_sep15 = 8;
  int64 students_completed_homework_selected_week = 9;
  int64 active_students_selected_week = 10;
  int64 active_teachers_selected_week = 11;
}

message DashboardSchoolsRequest {
  string search = 1; // optional search by school_name
  int32 page = 2; // page number (default: 1)
  int32 limit = 3; // items per page (default: 10)
  string start_date = 4; // selected week start date (format: YYYY-MM-DD)
  string end_date = 5; // selected week end date (format: YYYY-MM-DD)
}

message DashboardSchoolsResponse {
  repeated DashboardReportSchool schools = 1;
  int64 total = 2;
  int32 page = 3;
  int32 limit = 4;
  int32 total_pages = 5;
}

//protoc --go_out=. --go_opt=paths=source_relative prot/dashboard_schools.proto

