// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: prot/dashboard_schools.proto

package prot

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DashboardReportSchool struct {
	state                                 protoimpl.MessageState `protogen:"open.v1"`
	Id                                    int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SchoolId                              int64                  `protobuf:"varint,2,opt,name=school_id,json=schoolId,proto3" json:"school_id,omitempty"`
	SchoolName                            string                 `protobuf:"bytes,3,opt,name=school_name,json=schoolName,proto3" json:"school_name,omitempty"`
	TotalStudents                         int64                  `protobuf:"varint,4,opt,name=total_students,json=totalStudents,proto3" json:"total_students,omitempty"`
	TotalTeachers                         int64                  `protobuf:"varint,5,opt,name=total_teachers,json=totalTeachers,proto3" json:"total_teachers,omitempty"`
	ActiveTeachersFromSep8                int64                  `protobuf:"varint,6,opt,name=active_teachers_from_sep8,json=activeTeachersFromSep8,proto3" json:"active_teachers_from_sep8,omitempty"`
	ActiveStudentsFromSep15               int64                  `protobuf:"varint,7,opt,name=active_students_from_sep15,json=activeStudentsFromSep15,proto3" json:"active_students_from_sep15,omitempty"`
	StudentsCompletedHomeworkFromSep15    int64                  `protobuf:"varint,8,opt,name=students_completed_homework_from_sep15,json=studentsCompletedHomeworkFromSep15,proto3" json:"students_completed_homework_from_sep15,omitempty"`
	StudentsCompletedHomeworkSelectedWeek int64                  `protobuf:"varint,9,opt,name=students_completed_homework_selected_week,json=studentsCompletedHomeworkSelectedWeek,proto3" json:"students_completed_homework_selected_week,omitempty"`
	ActiveStudentsSelectedWeek            int64                  `protobuf:"varint,10,opt,name=active_students_selected_week,json=activeStudentsSelectedWeek,proto3" json:"active_students_selected_week,omitempty"`
	ActiveTeachersSelectedWeek            int64                  `protobuf:"varint,11,opt,name=active_teachers_selected_week,json=activeTeachersSelectedWeek,proto3" json:"active_teachers_selected_week,omitempty"`
	unknownFields                         protoimpl.UnknownFields
	sizeCache                             protoimpl.SizeCache
}

func (x *DashboardReportSchool) Reset() {
	*x = DashboardReportSchool{}
	mi := &file_prot_dashboard_schools_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DashboardReportSchool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DashboardReportSchool) ProtoMessage() {}

func (x *DashboardReportSchool) ProtoReflect() protoreflect.Message {
	mi := &file_prot_dashboard_schools_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DashboardReportSchool.ProtoReflect.Descriptor instead.
func (*DashboardReportSchool) Descriptor() ([]byte, []int) {
	return file_prot_dashboard_schools_proto_rawDescGZIP(), []int{0}
}

func (x *DashboardReportSchool) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DashboardReportSchool) GetSchoolId() int64 {
	if x != nil {
		return x.SchoolId
	}
	return 0
}

func (x *DashboardReportSchool) GetSchoolName() string {
	if x != nil {
		return x.SchoolName
	}
	return ""
}

func (x *DashboardReportSchool) GetTotalStudents() int64 {
	if x != nil {
		return x.TotalStudents
	}
	return 0
}

func (x *DashboardReportSchool) GetTotalTeachers() int64 {
	if x != nil {
		return x.TotalTeachers
	}
	return 0
}

func (x *DashboardReportSchool) GetActiveTeachersFromSep8() int64 {
	if x != nil {
		return x.ActiveTeachersFromSep8
	}
	return 0
}

func (x *DashboardReportSchool) GetActiveStudentsFromSep15() int64 {
	if x != nil {
		return x.ActiveStudentsFromSep15
	}
	return 0
}

func (x *DashboardReportSchool) GetStudentsCompletedHomeworkFromSep15() int64 {
	if x != nil {
		return x.StudentsCompletedHomeworkFromSep15
	}
	return 0
}

func (x *DashboardReportSchool) GetStudentsCompletedHomeworkSelectedWeek() int64 {
	if x != nil {
		return x.StudentsCompletedHomeworkSelectedWeek
	}
	return 0
}

func (x *DashboardReportSchool) GetActiveStudentsSelectedWeek() int64 {
	if x != nil {
		return x.ActiveStudentsSelectedWeek
	}
	return 0
}

func (x *DashboardReportSchool) GetActiveTeachersSelectedWeek() int64 {
	if x != nil {
		return x.ActiveTeachersSelectedWeek
	}
	return 0
}

type DashboardSchoolsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Search        string                 `protobuf:"bytes,1,opt,name=search,proto3" json:"search,omitempty"`                        // optional search by school_name
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`                           // page number (default: 1)
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`                         // items per page (default: 10)
	StartDate     string                 `protobuf:"bytes,4,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"` // selected week start date (format: YYYY-MM-DD)
	EndDate       string                 `protobuf:"bytes,5,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`       // selected week end date (format: YYYY-MM-DD)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DashboardSchoolsRequest) Reset() {
	*x = DashboardSchoolsRequest{}
	mi := &file_prot_dashboard_schools_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DashboardSchoolsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DashboardSchoolsRequest) ProtoMessage() {}

func (x *DashboardSchoolsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_prot_dashboard_schools_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DashboardSchoolsRequest.ProtoReflect.Descriptor instead.
func (*DashboardSchoolsRequest) Descriptor() ([]byte, []int) {
	return file_prot_dashboard_schools_proto_rawDescGZIP(), []int{1}
}

func (x *DashboardSchoolsRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *DashboardSchoolsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *DashboardSchoolsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *DashboardSchoolsRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *DashboardSchoolsRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

type DashboardSchoolsResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Schools       []*DashboardReportSchool `protobuf:"bytes,1,rep,name=schools,proto3" json:"schools,omitempty"`
	Total         int64                    `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                    `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                    `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	TotalPages    int32                    `protobuf:"varint,5,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DashboardSchoolsResponse) Reset() {
	*x = DashboardSchoolsResponse{}
	mi := &file_prot_dashboard_schools_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DashboardSchoolsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DashboardSchoolsResponse) ProtoMessage() {}

func (x *DashboardSchoolsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_prot_dashboard_schools_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DashboardSchoolsResponse.ProtoReflect.Descriptor instead.
func (*DashboardSchoolsResponse) Descriptor() ([]byte, []int) {
	return file_prot_dashboard_schools_proto_rawDescGZIP(), []int{2}
}

func (x *DashboardSchoolsResponse) GetSchools() []*DashboardReportSchool {
	if x != nil {
		return x.Schools
	}
	return nil
}

func (x *DashboardSchoolsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *DashboardSchoolsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *DashboardSchoolsResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *DashboardSchoolsResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

var File_prot_dashboard_schools_proto protoreflect.FileDescriptor

const file_prot_dashboard_schools_proto_rawDesc = "" +
	"\n" +
	"\x1cprot/dashboard_schools.proto\x12\x04prot\"\xdf\x04\n" +
	"\x15DashboardReportSchool\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tschool_id\x18\x02 \x01(\x03R\bschoolId\x12\x1f\n" +
	"\vschool_name\x18\x03 \x01(\tR\n" +
	"schoolName\x12%\n" +
	"\x0etotal_students\x18\x04 \x01(\x03R\rtotalStudents\x12%\n" +
	"\x0etotal_teachers\x18\x05 \x01(\x03R\rtotalTeachers\x129\n" +
	"\x19active_teachers_from_sep8\x18\x06 \x01(\x03R\x16activeTeachersFromSep8\x12;\n" +
	"\x1aactive_students_from_sep15\x18\a \x01(\x03R\x17activeStudentsFromSep15\x12R\n" +
	"&students_completed_homework_from_sep15\x18\b \x01(\x03R\"studentsCompletedHomeworkFromSep15\x12X\n" +
	")students_completed_homework_selected_week\x18\t \x01(\x03R%studentsCompletedHomeworkSelectedWeek\x12A\n" +
	"\x1dactive_students_selected_week\x18\n" +
	" \x01(\x03R\x1aactiveStudentsSelectedWeek\x12A\n" +
	"\x1dactive_teachers_selected_week\x18\v \x01(\x03R\x1aactiveTeachersSelectedWeek\"\x95\x01\n" +
	"\x17DashboardSchoolsRequest\x12\x16\n" +
	"\x06search\x18\x01 \x01(\tR\x06search\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x1d\n" +
	"\n" +
	"start_date\x18\x04 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x05 \x01(\tR\aendDate\"\xb2\x01\n" +
	"\x18DashboardSchoolsResponse\x125\n" +
	"\aschools\x18\x01 \x03(\v2\x1b.prot.DashboardReportSchoolR\aschools\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x1f\n" +
	"\vtotal_pages\x18\x05 \x01(\x05R\n" +
	"totalPagesB\rZ\vbe-Clever School/protb\x06proto3"

var (
	file_prot_dashboard_schools_proto_rawDescOnce sync.Once
	file_prot_dashboard_schools_proto_rawDescData []byte
)

func file_prot_dashboard_schools_proto_rawDescGZIP() []byte {
	file_prot_dashboard_schools_proto_rawDescOnce.Do(func() {
		file_prot_dashboard_schools_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_prot_dashboard_schools_proto_rawDesc), len(file_prot_dashboard_schools_proto_rawDesc)))
	})
	return file_prot_dashboard_schools_proto_rawDescData
}

var file_prot_dashboard_schools_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_prot_dashboard_schools_proto_goTypes = []any{
	(*DashboardReportSchool)(nil),    // 0: prot.DashboardReportSchool
	(*DashboardSchoolsRequest)(nil),  // 1: prot.DashboardSchoolsRequest
	(*DashboardSchoolsResponse)(nil), // 2: prot.DashboardSchoolsResponse
}
var file_prot_dashboard_schools_proto_depIdxs = []int32{
	0, // 0: prot.DashboardSchoolsResponse.schools:type_name -> prot.DashboardReportSchool
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_prot_dashboard_schools_proto_init() }
func file_prot_dashboard_schools_proto_init() {
	if File_prot_dashboard_schools_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_prot_dashboard_schools_proto_rawDesc), len(file_prot_dashboard_schools_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_prot_dashboard_schools_proto_goTypes,
		DependencyIndexes: file_prot_dashboard_schools_proto_depIdxs,
		MessageInfos:      file_prot_dashboard_schools_proto_msgTypes,
	}.Build()
	File_prot_dashboard_schools_proto = out.File
	file_prot_dashboard_schools_proto_goTypes = nil
	file_prot_dashboard_schools_proto_depIdxs = nil
}
