syntax = "proto3";

package prot;

option go_package = "be-cleverschool/prot";

// Dashboard Teacher Homework Student
message DashboardTeacherHomeworkStudent {
  int64 student_id = 1;
  string student_name = 2;
  string student_avatar = 3;  // URL ảnh đại diện
  int64 total_questions = 4;
  int64 questions_completed = 5;
}

message DashboardTeacherHomeworkStudentListResponse {
  repeated DashboardTeacherHomeworkStudent students = 1;
  int64 total = 2;
}

// Dashboard Teacher Homework Student Statistics
message DashboardTeacherHomeworkStudentStats {
  int64 student_id = 1;
  string student_name = 2;
  string student_avatar = 3;  // URL ảnh đại diện
  int64 total_homework = 4;
  int64 total_assigned_homeworks = 5;
  int64 in_progress_homework = 6;
  int64 completed_homework = 7;
  int64 not_started_homework = 8;
  double average_ratio = 9;  // Tỷ lệ điểm trung bình của học sinh
  double completed_homework_ratio = 10;  // Tỷ lệ hoàn thành = completed_homework / total_assigned_homeworks
  int64 total_questions = 11;
  int64 questions_completed = 12;
}

message DashboardTeacherHomeworkStudentStatsResponse {
  repeated DashboardTeacherHomeworkStudentStats students = 1;
  int64 total = 2;
}

// Dashboard Teacher Homework Overview
message DashboardTeacherHomeworkOverview {
  double not_started_percentage = 1;
  double in_progress_percentage = 2;
  double completed_percentage = 3;
  int64 total_students = 4;
  int64 not_started_count = 5;
  int64 in_progress_count = 6;
  int64 completed_count = 7;
}

message DashboardTeacherHomeworkOverviewResponse {
  DashboardTeacherHomeworkOverview overview = 1;
}

//protoc --go_out=. --go_opt=paths=source_relative prot/dashboard_teacher_homework_student.proto 
