// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: dashboard_courses.proto

package prot

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DashboardTeacherInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DashboardTeacherInfo) Reset() {
	*x = DashboardTeacherInfo{}
	mi := &file_dashboard_courses_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DashboardTeacherInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DashboardTeacherInfo) ProtoMessage() {}

func (x *DashboardTeacherInfo) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_courses_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DashboardTeacherInfo.ProtoReflect.Descriptor instead.
func (*DashboardTeacherInfo) Descriptor() ([]byte, []int) {
	return file_dashboard_courses_proto_rawDescGZIP(), []int{0}
}

func (x *DashboardTeacherInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DashboardTeacherInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *DashboardTeacherInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DashboardReportCourse struct {
	state                                 protoimpl.MessageState  `protogen:"open.v1"`
	Id                                    int64                   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CourseId                              int64                   `protobuf:"varint,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	CourseName                            string                  `protobuf:"bytes,3,opt,name=course_name,json=courseName,proto3" json:"course_name,omitempty"`
	ObjectTitle                           string                  `protobuf:"bytes,4,opt,name=object_title,json=objectTitle,proto3" json:"object_title,omitempty"` // Thêm object_title từ courses
	SchoolId                              int64                   `protobuf:"varint,5,opt,name=school_id,json=schoolId,proto3" json:"school_id,omitempty"`
	SchoolName                            string                  `protobuf:"bytes,6,opt,name=school_name,json=schoolName,proto3" json:"school_name,omitempty"`
	TotalStudents                         int64                   `protobuf:"varint,7,opt,name=total_students,json=totalStudents,proto3" json:"total_students,omitempty"`
	TotalTeachers                         int64                   `protobuf:"varint,8,opt,name=total_teachers,json=totalTeachers,proto3" json:"total_teachers,omitempty"`
	TeacherIds                            string                  `protobuf:"bytes,9,opt,name=teacher_ids,json=teacherIds,proto3" json:"teacher_ids,omitempty"`
	TeacherInfos                          []*DashboardTeacherInfo `protobuf:"bytes,10,rep,name=teacher_infos,json=teacherInfos,proto3" json:"teacher_infos,omitempty"`
	ActiveTeachersFromSep8                int64                   `protobuf:"varint,11,opt,name=active_teachers_from_sep8,json=activeTeachersFromSep8,proto3" json:"active_teachers_from_sep8,omitempty"`
	ActiveStudentsFromSep15               int64                   `protobuf:"varint,12,opt,name=active_students_from_sep15,json=activeStudentsFromSep15,proto3" json:"active_students_from_sep15,omitempty"`
	StudentsCompletedHomeworkFromSep15    int64                   `protobuf:"varint,13,opt,name=students_completed_homework_from_sep15,json=studentsCompletedHomeworkFromSep15,proto3" json:"students_completed_homework_from_sep15,omitempty"`
	StudentsCompletedHomeworkSelectedWeek int64                   `protobuf:"varint,14,opt,name=students_completed_homework_selected_week,json=studentsCompletedHomeworkSelectedWeek,proto3" json:"students_completed_homework_selected_week,omitempty"`
	ActiveStudentsSelectedWeek            int64                   `protobuf:"varint,15,opt,name=active_students_selected_week,json=activeStudentsSelectedWeek,proto3" json:"active_students_selected_week,omitempty"`
	ActiveTeachersSelectedWeek            int64                   `protobuf:"varint,16,opt,name=active_teachers_selected_week,json=activeTeachersSelectedWeek,proto3" json:"active_teachers_selected_week,omitempty"`
	TotalHomeworks                        int64                   `protobuf:"varint,17,opt,name=total_homeworks,json=totalHomeworks,proto3" json:"total_homeworks,omitempty"`             // Tổng số homework từ 15/9/2025 đến hiện tại
	AssignedHomeworks                     int64                   `protobuf:"varint,18,opt,name=assigned_homeworks,json=assignedHomeworks,proto3" json:"assigned_homeworks,omitempty"`    // Số homework đã giao từ 15/9/2025 đến hiện tại
	CompletedHomeworks                    int64                   `protobuf:"varint,19,opt,name=completed_homeworks,json=completedHomeworks,proto3" json:"completed_homeworks,omitempty"` // Số homework đã hoàn thành từ 15/9/2025 đến hiện tại
	unknownFields                         protoimpl.UnknownFields
	sizeCache                             protoimpl.SizeCache
}

func (x *DashboardReportCourse) Reset() {
	*x = DashboardReportCourse{}
	mi := &file_dashboard_courses_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DashboardReportCourse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DashboardReportCourse) ProtoMessage() {}

func (x *DashboardReportCourse) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_courses_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DashboardReportCourse.ProtoReflect.Descriptor instead.
func (*DashboardReportCourse) Descriptor() ([]byte, []int) {
	return file_dashboard_courses_proto_rawDescGZIP(), []int{1}
}

func (x *DashboardReportCourse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DashboardReportCourse) GetCourseId() int64 {
	if x != nil {
		return x.CourseId
	}
	return 0
}

func (x *DashboardReportCourse) GetCourseName() string {
	if x != nil {
		return x.CourseName
	}
	return ""
}

func (x *DashboardReportCourse) GetObjectTitle() string {
	if x != nil {
		return x.ObjectTitle
	}
	return ""
}

func (x *DashboardReportCourse) GetSchoolId() int64 {
	if x != nil {
		return x.SchoolId
	}
	return 0
}

func (x *DashboardReportCourse) GetSchoolName() string {
	if x != nil {
		return x.SchoolName
	}
	return ""
}

func (x *DashboardReportCourse) GetTotalStudents() int64 {
	if x != nil {
		return x.TotalStudents
	}
	return 0
}

func (x *DashboardReportCourse) GetTotalTeachers() int64 {
	if x != nil {
		return x.TotalTeachers
	}
	return 0
}

func (x *DashboardReportCourse) GetTeacherIds() string {
	if x != nil {
		return x.TeacherIds
	}
	return ""
}

func (x *DashboardReportCourse) GetTeacherInfos() []*DashboardTeacherInfo {
	if x != nil {
		return x.TeacherInfos
	}
	return nil
}

func (x *DashboardReportCourse) GetActiveTeachersFromSep8() int64 {
	if x != nil {
		return x.ActiveTeachersFromSep8
	}
	return 0
}

func (x *DashboardReportCourse) GetActiveStudentsFromSep15() int64 {
	if x != nil {
		return x.ActiveStudentsFromSep15
	}
	return 0
}

func (x *DashboardReportCourse) GetStudentsCompletedHomeworkFromSep15() int64 {
	if x != nil {
		return x.StudentsCompletedHomeworkFromSep15
	}
	return 0
}

func (x *DashboardReportCourse) GetStudentsCompletedHomeworkSelectedWeek() int64 {
	if x != nil {
		return x.StudentsCompletedHomeworkSelectedWeek
	}
	return 0
}

func (x *DashboardReportCourse) GetActiveStudentsSelectedWeek() int64 {
	if x != nil {
		return x.ActiveStudentsSelectedWeek
	}
	return 0
}

func (x *DashboardReportCourse) GetActiveTeachersSelectedWeek() int64 {
	if x != nil {
		return x.ActiveTeachersSelectedWeek
	}
	return 0
}

func (x *DashboardReportCourse) GetTotalHomeworks() int64 {
	if x != nil {
		return x.TotalHomeworks
	}
	return 0
}

func (x *DashboardReportCourse) GetAssignedHomeworks() int64 {
	if x != nil {
		return x.AssignedHomeworks
	}
	return 0
}

func (x *DashboardReportCourse) GetCompletedHomeworks() int64 {
	if x != nil {
		return x.CompletedHomeworks
	}
	return 0
}

type DashboardCoursesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchoolId      int64                  `protobuf:"varint,1,opt,name=school_id,json=schoolId,proto3" json:"school_id,omitempty"`   // optional filter by school_id
	Search        string                 `protobuf:"bytes,2,opt,name=search,proto3" json:"search,omitempty"`                        // optional search by course_name or school_name
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`                           // page number (default: 1)
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`                         // items per page (default: 10)
	StartDate     string                 `protobuf:"bytes,5,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"` // selected week start date (format: YYYY-MM-DD)
	EndDate       string                 `protobuf:"bytes,6,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`       // selected week end date (format: YYYY-MM-DD)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DashboardCoursesRequest) Reset() {
	*x = DashboardCoursesRequest{}
	mi := &file_dashboard_courses_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DashboardCoursesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DashboardCoursesRequest) ProtoMessage() {}

func (x *DashboardCoursesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_courses_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DashboardCoursesRequest.ProtoReflect.Descriptor instead.
func (*DashboardCoursesRequest) Descriptor() ([]byte, []int) {
	return file_dashboard_courses_proto_rawDescGZIP(), []int{2}
}

func (x *DashboardCoursesRequest) GetSchoolId() int64 {
	if x != nil {
		return x.SchoolId
	}
	return 0
}

func (x *DashboardCoursesRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *DashboardCoursesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *DashboardCoursesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *DashboardCoursesRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *DashboardCoursesRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

type DashboardCoursesResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Courses       []*DashboardReportCourse `protobuf:"bytes,1,rep,name=courses,proto3" json:"courses,omitempty"`
	Total         int64                    `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                    `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                    `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	TotalPages    int32                    `protobuf:"varint,5,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DashboardCoursesResponse) Reset() {
	*x = DashboardCoursesResponse{}
	mi := &file_dashboard_courses_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DashboardCoursesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DashboardCoursesResponse) ProtoMessage() {}

func (x *DashboardCoursesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_courses_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DashboardCoursesResponse.ProtoReflect.Descriptor instead.
func (*DashboardCoursesResponse) Descriptor() ([]byte, []int) {
	return file_dashboard_courses_proto_rawDescGZIP(), []int{3}
}

func (x *DashboardCoursesResponse) GetCourses() []*DashboardReportCourse {
	if x != nil {
		return x.Courses
	}
	return nil
}

func (x *DashboardCoursesResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *DashboardCoursesResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *DashboardCoursesResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *DashboardCoursesResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

var File_dashboard_courses_proto protoreflect.FileDescriptor

const file_dashboard_courses_proto_rawDesc = "" +
	"\n" +
	"\x17dashboard_courses.proto\x12\x04prot\"V\n" +
	"\x14DashboardTeacherInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"\xab\a\n" +
	"\x15DashboardReportCourse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\x03R\bcourseId\x12\x1f\n" +
	"\vcourse_name\x18\x03 \x01(\tR\n" +
	"courseName\x12!\n" +
	"\fobject_title\x18\x04 \x01(\tR\vobjectTitle\x12\x1b\n" +
	"\tschool_id\x18\x05 \x01(\x03R\bschoolId\x12\x1f\n" +
	"\vschool_name\x18\x06 \x01(\tR\n" +
	"schoolName\x12%\n" +
	"\x0etotal_students\x18\a \x01(\x03R\rtotalStudents\x12%\n" +
	"\x0etotal_teachers\x18\b \x01(\x03R\rtotalTeachers\x12\x1f\n" +
	"\vteacher_ids\x18\t \x01(\tR\n" +
	"teacherIds\x12?\n" +
	"\rteacher_infos\x18\n" +
	" \x03(\v2\x1a.prot.DashboardTeacherInfoR\fteacherInfos\x129\n" +
	"\x19active_teachers_from_sep8\x18\v \x01(\x03R\x16activeTeachersFromSep8\x12;\n" +
	"\x1aactive_students_from_sep15\x18\f \x01(\x03R\x17activeStudentsFromSep15\x12R\n" +
	"&students_completed_homework_from_sep15\x18\r \x01(\x03R\"studentsCompletedHomeworkFromSep15\x12X\n" +
	")students_completed_homework_selected_week\x18\x0e \x01(\x03R%studentsCompletedHomeworkSelectedWeek\x12A\n" +
	"\x1dactive_students_selected_week\x18\x0f \x01(\x03R\x1aactiveStudentsSelectedWeek\x12A\n" +
	"\x1dactive_teachers_selected_week\x18\x10 \x01(\x03R\x1aactiveTeachersSelectedWeek\x12'\n" +
	"\x0ftotal_homeworks\x18\x11 \x01(\x03R\x0etotalHomeworks\x12-\n" +
	"\x12assigned_homeworks\x18\x12 \x01(\x03R\x11assignedHomeworks\x12/\n" +
	"\x13completed_homeworks\x18\x13 \x01(\x03R\x12completedHomeworks\"\xb2\x01\n" +
	"\x17DashboardCoursesRequest\x12\x1b\n" +
	"\tschool_id\x18\x01 \x01(\x03R\bschoolId\x12\x16\n" +
	"\x06search\x18\x02 \x01(\tR\x06search\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x1d\n" +
	"\n" +
	"start_date\x18\x05 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x06 \x01(\tR\aendDate\"\xb2\x01\n" +
	"\x18DashboardCoursesResponse\x125\n" +
	"\acourses\x18\x01 \x03(\v2\x1b.prot.DashboardReportCourseR\acourses\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x1f\n" +
	"\vtotal_pages\x18\x05 \x01(\x05R\n" +
	"totalPagesB\rZ\vbe-lms/protb\x06proto3"

var (
	file_dashboard_courses_proto_rawDescOnce sync.Once
	file_dashboard_courses_proto_rawDescData []byte
)

func file_dashboard_courses_proto_rawDescGZIP() []byte {
	file_dashboard_courses_proto_rawDescOnce.Do(func() {
		file_dashboard_courses_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dashboard_courses_proto_rawDesc), len(file_dashboard_courses_proto_rawDesc)))
	})
	return file_dashboard_courses_proto_rawDescData
}

var file_dashboard_courses_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_dashboard_courses_proto_goTypes = []any{
	(*DashboardTeacherInfo)(nil),     // 0: prot.DashboardTeacherInfo
	(*DashboardReportCourse)(nil),    // 1: prot.DashboardReportCourse
	(*DashboardCoursesRequest)(nil),  // 2: prot.DashboardCoursesRequest
	(*DashboardCoursesResponse)(nil), // 3: prot.DashboardCoursesResponse
}
var file_dashboard_courses_proto_depIdxs = []int32{
	0, // 0: prot.DashboardReportCourse.teacher_infos:type_name -> prot.DashboardTeacherInfo
	1, // 1: prot.DashboardCoursesResponse.courses:type_name -> prot.DashboardReportCourse
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_dashboard_courses_proto_init() }
func file_dashboard_courses_proto_init() {
	if File_dashboard_courses_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dashboard_courses_proto_rawDesc), len(file_dashboard_courses_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dashboard_courses_proto_goTypes,
		DependencyIndexes: file_dashboard_courses_proto_depIdxs,
		MessageInfos:      file_dashboard_courses_proto_msgTypes,
	}.Build()
	File_dashboard_courses_proto = out.File
	file_dashboard_courses_proto_goTypes = nil
	file_dashboard_courses_proto_depIdxs = nil
}
