// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: dashboard_teacher_homework_overview.proto

package prot

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Dashboard Teacher Homework Overview Stats
type DashboardTeacherHomeworkOverviewStats struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	TotalSubmitted       int64                  `protobuf:"varint,1,opt,name=total_submitted,json=totalSubmitted,proto3" json:"total_submitted,omitempty"`
	TotalScored          int64                  `protobuf:"varint,2,opt,name=total_scored,json=totalScored,proto3" json:"total_scored,omitempty"`
	TotalUnscored        int64                  `protobuf:"varint,3,opt,name=total_unscored,json=totalUnscored,proto3" json:"total_unscored,omitempty"`
	TotalNoManualScoring int64                  `protobuf:"varint,4,opt,name=total_no_manual_scoring,json=totalNoManualScoring,proto3" json:"total_no_manual_scoring,omitempty"`
	CompletionRate       float64                `protobuf:"fixed64,5,opt,name=completion_rate,json=completionRate,proto3" json:"completion_rate,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *DashboardTeacherHomeworkOverviewStats) Reset() {
	*x = DashboardTeacherHomeworkOverviewStats{}
	mi := &file_dashboard_teacher_homework_overview_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DashboardTeacherHomeworkOverviewStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DashboardTeacherHomeworkOverviewStats) ProtoMessage() {}

func (x *DashboardTeacherHomeworkOverviewStats) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_teacher_homework_overview_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DashboardTeacherHomeworkOverviewStats.ProtoReflect.Descriptor instead.
func (*DashboardTeacherHomeworkOverviewStats) Descriptor() ([]byte, []int) {
	return file_dashboard_teacher_homework_overview_proto_rawDescGZIP(), []int{0}
}

func (x *DashboardTeacherHomeworkOverviewStats) GetTotalSubmitted() int64 {
	if x != nil {
		return x.TotalSubmitted
	}
	return 0
}

func (x *DashboardTeacherHomeworkOverviewStats) GetTotalScored() int64 {
	if x != nil {
		return x.TotalScored
	}
	return 0
}

func (x *DashboardTeacherHomeworkOverviewStats) GetTotalUnscored() int64 {
	if x != nil {
		return x.TotalUnscored
	}
	return 0
}

func (x *DashboardTeacherHomeworkOverviewStats) GetTotalNoManualScoring() int64 {
	if x != nil {
		return x.TotalNoManualScoring
	}
	return 0
}

func (x *DashboardTeacherHomeworkOverviewStats) GetCompletionRate() float64 {
	if x != nil {
		return x.CompletionRate
	}
	return 0
}

type DashboardTeacherHomeworkOverviewStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartDate     int64                  `protobuf:"varint,1,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       int64                  `protobuf:"varint,2,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	CourseId      int64                  `protobuf:"varint,3,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	HomeworkId    int64                  `protobuf:"varint,4,opt,name=homework_id,json=homeworkId,proto3" json:"homework_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DashboardTeacherHomeworkOverviewStatsRequest) Reset() {
	*x = DashboardTeacherHomeworkOverviewStatsRequest{}
	mi := &file_dashboard_teacher_homework_overview_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DashboardTeacherHomeworkOverviewStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DashboardTeacherHomeworkOverviewStatsRequest) ProtoMessage() {}

func (x *DashboardTeacherHomeworkOverviewStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_teacher_homework_overview_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DashboardTeacherHomeworkOverviewStatsRequest.ProtoReflect.Descriptor instead.
func (*DashboardTeacherHomeworkOverviewStatsRequest) Descriptor() ([]byte, []int) {
	return file_dashboard_teacher_homework_overview_proto_rawDescGZIP(), []int{1}
}

func (x *DashboardTeacherHomeworkOverviewStatsRequest) GetStartDate() int64 {
	if x != nil {
		return x.StartDate
	}
	return 0
}

func (x *DashboardTeacherHomeworkOverviewStatsRequest) GetEndDate() int64 {
	if x != nil {
		return x.EndDate
	}
	return 0
}

func (x *DashboardTeacherHomeworkOverviewStatsRequest) GetCourseId() int64 {
	if x != nil {
		return x.CourseId
	}
	return 0
}

func (x *DashboardTeacherHomeworkOverviewStatsRequest) GetHomeworkId() int64 {
	if x != nil {
		return x.HomeworkId
	}
	return 0
}

type DashboardTeacherHomeworkOverviewStatsResponse struct {
	state         protoimpl.MessageState                 `protogen:"open.v1"`
	Overview      *DashboardTeacherHomeworkOverviewStats `protobuf:"bytes,1,opt,name=overview,proto3" json:"overview,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DashboardTeacherHomeworkOverviewStatsResponse) Reset() {
	*x = DashboardTeacherHomeworkOverviewStatsResponse{}
	mi := &file_dashboard_teacher_homework_overview_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DashboardTeacherHomeworkOverviewStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DashboardTeacherHomeworkOverviewStatsResponse) ProtoMessage() {}

func (x *DashboardTeacherHomeworkOverviewStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_teacher_homework_overview_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DashboardTeacherHomeworkOverviewStatsResponse.ProtoReflect.Descriptor instead.
func (*DashboardTeacherHomeworkOverviewStatsResponse) Descriptor() ([]byte, []int) {
	return file_dashboard_teacher_homework_overview_proto_rawDescGZIP(), []int{2}
}

func (x *DashboardTeacherHomeworkOverviewStatsResponse) GetOverview() *DashboardTeacherHomeworkOverviewStats {
	if x != nil {
		return x.Overview
	}
	return nil
}

var File_dashboard_teacher_homework_overview_proto protoreflect.FileDescriptor

const file_dashboard_teacher_homework_overview_proto_rawDesc = "" +
	"\n" +
	")dashboard_teacher_homework_overview.proto\x12\x04prot\"\xfa\x01\n" +
	"%DashboardTeacherHomeworkOverviewStats\x12'\n" +
	"\x0ftotal_submitted\x18\x01 \x01(\x03R\x0etotalSubmitted\x12!\n" +
	"\ftotal_scored\x18\x02 \x01(\x03R\vtotalScored\x12%\n" +
	"\x0etotal_unscored\x18\x03 \x01(\x03R\rtotalUnscored\x125\n" +
	"\x17total_no_manual_scoring\x18\x04 \x01(\x03R\x14totalNoManualScoring\x12'\n" +
	"\x0fcompletion_rate\x18\x05 \x01(\x01R\x0ecompletionRate\"\xa6\x01\n" +
	",DashboardTeacherHomeworkOverviewStatsRequest\x12\x1d\n" +
	"\n" +
	"start_date\x18\x01 \x01(\x03R\tstartDate\x12\x19\n" +
	"\bend_date\x18\x02 \x01(\x03R\aendDate\x12\x1b\n" +
	"\tcourse_id\x18\x03 \x01(\x03R\bcourseId\x12\x1f\n" +
	"\vhomework_id\x18\x04 \x01(\x03R\n" +
	"homeworkId\"x\n" +
	"-DashboardTeacherHomeworkOverviewStatsResponse\x12G\n" +
	"\boverview\x18\x01 \x01(\v2+.prot.DashboardTeacherHomeworkOverviewStatsR\boverviewB\rZ\vbe-cleverschool/protb\x06proto3"

var (
	file_dashboard_teacher_homework_overview_proto_rawDescOnce sync.Once
	file_dashboard_teacher_homework_overview_proto_rawDescData []byte
)

func file_dashboard_teacher_homework_overview_proto_rawDescGZIP() []byte {
	file_dashboard_teacher_homework_overview_proto_rawDescOnce.Do(func() {
		file_dashboard_teacher_homework_overview_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dashboard_teacher_homework_overview_proto_rawDesc), len(file_dashboard_teacher_homework_overview_proto_rawDesc)))
	})
	return file_dashboard_teacher_homework_overview_proto_rawDescData
}

var file_dashboard_teacher_homework_overview_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_dashboard_teacher_homework_overview_proto_goTypes = []any{
	(*DashboardTeacherHomeworkOverviewStats)(nil),         // 0: prot.DashboardTeacherHomeworkOverviewStats
	(*DashboardTeacherHomeworkOverviewStatsRequest)(nil),  // 1: prot.DashboardTeacherHomeworkOverviewStatsRequest
	(*DashboardTeacherHomeworkOverviewStatsResponse)(nil), // 2: prot.DashboardTeacherHomeworkOverviewStatsResponse
}
var file_dashboard_teacher_homework_overview_proto_depIdxs = []int32{
	0, // 0: prot.DashboardTeacherHomeworkOverviewStatsResponse.overview:type_name -> prot.DashboardTeacherHomeworkOverviewStats
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_dashboard_teacher_homework_overview_proto_init() }
func file_dashboard_teacher_homework_overview_proto_init() {
	if File_dashboard_teacher_homework_overview_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dashboard_teacher_homework_overview_proto_rawDesc), len(file_dashboard_teacher_homework_overview_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dashboard_teacher_homework_overview_proto_goTypes,
		DependencyIndexes: file_dashboard_teacher_homework_overview_proto_depIdxs,
		MessageInfos:      file_dashboard_teacher_homework_overview_proto_msgTypes,
	}.Build()
	File_dashboard_teacher_homework_overview_proto = out.File
	file_dashboard_teacher_homework_overview_proto_goTypes = nil
	file_dashboard_teacher_homework_overview_proto_depIdxs = nil
}

