// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: exercise.proto

package prot

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExerciseFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExerciseFile) Reset() {
	*x = ExerciseFile{}
	mi := &file_exercise_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExerciseFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExerciseFile) ProtoMessage() {}

func (x *ExerciseFile) ProtoReflect() protoreflect.Message {
	mi := &file_exercise_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExerciseFile.ProtoReflect.Descriptor instead.
func (*ExerciseFile) Descriptor() ([]byte, []int) {
	return file_exercise_proto_rawDescGZIP(), []int{0}
}

func (x *ExerciseFile) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ExerciseFile) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type Exercise struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status           int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	TimeLimit        int64                  `protobuf:"varint,4,opt,name=time_limit,json=timeLimit,proto3" json:"time_limit,omitempty"`
	MaxScore         float32                `protobuf:"fixed32,5,opt,name=max_score,json=maxScore,proto3" json:"max_score,omitempty"`
	Description      string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	CoverImage       string                 `protobuf:"bytes,7,opt,name=cover_image,json=coverImage,proto3" json:"cover_image,omitempty"`
	CreatedAt        int64                  `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CreatedBy        int64                  `protobuf:"varint,9,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	UpdatedAt        int64                  `protobuf:"varint,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	UpdatedBy        int64                  `protobuf:"varint,11,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	Deadline         int64                  `protobuf:"varint,12,opt,name=deadline,proto3" json:"deadline,omitempty"`
	IsAssigned       bool                   `protobuf:"varint,13,opt,name=is_assigned,json=isAssigned,proto3" json:"is_assigned,omitempty"`
	TotalQuestions   int32                  `protobuf:"varint,14,opt,name=total_questions,json=totalQuestions,proto3" json:"total_questions,omitempty"`
	ObjectTitle      string                 `protobuf:"bytes,15,opt,name=object_title,json=objectTitle,proto3" json:"object_title,omitempty"`
	IsRandomQuestion bool                   `protobuf:"varint,16,opt,name=is_random_question,json=isRandomQuestion,proto3" json:"is_random_question,omitempty"`
	QuestionForm     string                 `protobuf:"bytes,17,opt,name=question_form,json=questionForm,proto3" json:"question_form,omitempty"`
	QuestionFiles    []*ExerciseFile        `protobuf:"bytes,18,rep,name=question_files,json=questionFiles,proto3" json:"question_files,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Exercise) Reset() {
	*x = Exercise{}
	mi := &file_exercise_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Exercise) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Exercise) ProtoMessage() {}

func (x *Exercise) ProtoReflect() protoreflect.Message {
	mi := &file_exercise_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Exercise.ProtoReflect.Descriptor instead.
func (*Exercise) Descriptor() ([]byte, []int) {
	return file_exercise_proto_rawDescGZIP(), []int{1}
}

func (x *Exercise) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Exercise) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Exercise) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Exercise) GetTimeLimit() int64 {
	if x != nil {
		return x.TimeLimit
	}
	return 0
}

func (x *Exercise) GetMaxScore() float32 {
	if x != nil {
		return x.MaxScore
	}
	return 0
}

func (x *Exercise) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Exercise) GetCoverImage() string {
	if x != nil {
		return x.CoverImage
	}
	return ""
}

func (x *Exercise) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Exercise) GetCreatedBy() int64 {
	if x != nil {
		return x.CreatedBy
	}
	return 0
}

func (x *Exercise) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Exercise) GetUpdatedBy() int64 {
	if x != nil {
		return x.UpdatedBy
	}
	return 0
}

func (x *Exercise) GetDeadline() int64 {
	if x != nil {
		return x.Deadline
	}
	return 0
}

func (x *Exercise) GetIsAssigned() bool {
	if x != nil {
		return x.IsAssigned
	}
	return false
}

func (x *Exercise) GetTotalQuestions() int32 {
	if x != nil {
		return x.TotalQuestions
	}
	return 0
}

func (x *Exercise) GetObjectTitle() string {
	if x != nil {
		return x.ObjectTitle
	}
	return ""
}

func (x *Exercise) GetIsRandomQuestion() bool {
	if x != nil {
		return x.IsRandomQuestion
	}
	return false
}

func (x *Exercise) GetQuestionForm() string {
	if x != nil {
		return x.QuestionForm
	}
	return ""
}

func (x *Exercise) GetQuestionFiles() []*ExerciseFile {
	if x != nil {
		return x.QuestionFiles
	}
	return nil
}

type ExerciseRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status           int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	TimeLimit        int64                  `protobuf:"varint,4,opt,name=time_limit,json=timeLimit,proto3" json:"time_limit,omitempty"`
	MaxScore         float32                `protobuf:"fixed32,5,opt,name=max_score,json=maxScore,proto3" json:"max_score,omitempty"`
	Description      string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	CoverImage       string                 `protobuf:"bytes,7,opt,name=cover_image,json=coverImage,proto3" json:"cover_image,omitempty"`
	Deadline         int64                  `protobuf:"varint,8,opt,name=deadline,proto3" json:"deadline,omitempty"`
	IsAssigned       bool                   `protobuf:"varint,9,opt,name=is_assigned,json=isAssigned,proto3" json:"is_assigned,omitempty"`
	TotalQuestions   int32                  `protobuf:"varint,10,opt,name=total_questions,json=totalQuestions,proto3" json:"total_questions,omitempty"`
	ObjectTitle      string                 `protobuf:"bytes,11,opt,name=object_title,json=objectTitle,proto3" json:"object_title,omitempty"`
	IsRandomQuestion bool                   `protobuf:"varint,12,opt,name=is_random_question,json=isRandomQuestion,proto3" json:"is_random_question,omitempty"`
	QuestionForm     string                 `protobuf:"bytes,13,opt,name=question_form,json=questionForm,proto3" json:"question_form,omitempty"`
	QuestionFiles    []*ExerciseFile        `protobuf:"bytes,14,rep,name=question_files,json=questionFiles,proto3" json:"question_files,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ExerciseRequest) Reset() {
	*x = ExerciseRequest{}
	mi := &file_exercise_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExerciseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExerciseRequest) ProtoMessage() {}

func (x *ExerciseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exercise_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExerciseRequest.ProtoReflect.Descriptor instead.
func (*ExerciseRequest) Descriptor() ([]byte, []int) {
	return file_exercise_proto_rawDescGZIP(), []int{2}
}

func (x *ExerciseRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ExerciseRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ExerciseRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ExerciseRequest) GetTimeLimit() int64 {
	if x != nil {
		return x.TimeLimit
	}
	return 0
}

func (x *ExerciseRequest) GetMaxScore() float32 {
	if x != nil {
		return x.MaxScore
	}
	return 0
}

func (x *ExerciseRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ExerciseRequest) GetCoverImage() string {
	if x != nil {
		return x.CoverImage
	}
	return ""
}

func (x *ExerciseRequest) GetDeadline() int64 {
	if x != nil {
		return x.Deadline
	}
	return 0
}

func (x *ExerciseRequest) GetIsAssigned() bool {
	if x != nil {
		return x.IsAssigned
	}
	return false
}

func (x *ExerciseRequest) GetTotalQuestions() int32 {
	if x != nil {
		return x.TotalQuestions
	}
	return 0
}

func (x *ExerciseRequest) GetObjectTitle() string {
	if x != nil {
		return x.ObjectTitle
	}
	return ""
}

func (x *ExerciseRequest) GetIsRandomQuestion() bool {
	if x != nil {
		return x.IsRandomQuestion
	}
	return false
}

func (x *ExerciseRequest) GetQuestionForm() string {
	if x != nil {
		return x.QuestionForm
	}
	return ""
}

func (x *ExerciseRequest) GetQuestionFiles() []*ExerciseFile {
	if x != nil {
		return x.QuestionFiles
	}
	return nil
}

type ExerciseListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exercises     []*Exercise            `protobuf:"bytes,1,rep,name=exercises,proto3" json:"exercises,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExerciseListResponse) Reset() {
	*x = ExerciseListResponse{}
	mi := &file_exercise_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExerciseListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExerciseListResponse) ProtoMessage() {}

func (x *ExerciseListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_exercise_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExerciseListResponse.ProtoReflect.Descriptor instead.
func (*ExerciseListResponse) Descriptor() ([]byte, []int) {
	return file_exercise_proto_rawDescGZIP(), []int{3}
}

func (x *ExerciseListResponse) GetExercises() []*Exercise {
	if x != nil {
		return x.Exercises
	}
	return nil
}

func (x *ExerciseListResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ClonedExerciseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LessonId      int64                  `protobuf:"varint,1,opt,name=lesson_id,json=lessonId,proto3" json:"lesson_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClonedExerciseRequest) Reset() {
	*x = ClonedExerciseRequest{}
	mi := &file_exercise_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClonedExerciseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClonedExerciseRequest) ProtoMessage() {}

func (x *ClonedExerciseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exercise_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClonedExerciseRequest.ProtoReflect.Descriptor instead.
func (*ClonedExerciseRequest) Descriptor() ([]byte, []int) {
	return file_exercise_proto_rawDescGZIP(), []int{4}
}

func (x *ClonedExerciseRequest) GetLessonId() int64 {
	if x != nil {
		return x.LessonId
	}
	return 0
}

func (x *ClonedExerciseRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ClonedExerciseRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type AssignedExercise struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LessonId      int64                  `protobuf:"varint,1,opt,name=lesson_id,json=lessonId,proto3" json:"lesson_id,omitempty"`
	CourseId      int64                  `protobuf:"varint,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	IsAssigned    bool                   `protobuf:"varint,3,opt,name=is_assigned,json=isAssigned,proto3" json:"is_assigned,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignedExercise) Reset() {
	*x = AssignedExercise{}
	mi := &file_exercise_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignedExercise) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignedExercise) ProtoMessage() {}

func (x *AssignedExercise) ProtoReflect() protoreflect.Message {
	mi := &file_exercise_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignedExercise.ProtoReflect.Descriptor instead.
func (*AssignedExercise) Descriptor() ([]byte, []int) {
	return file_exercise_proto_rawDescGZIP(), []int{5}
}

func (x *AssignedExercise) GetLessonId() int64 {
	if x != nil {
		return x.LessonId
	}
	return 0
}

func (x *AssignedExercise) GetCourseId() int64 {
	if x != nil {
		return x.CourseId
	}
	return 0
}

func (x *AssignedExercise) GetIsAssigned() bool {
	if x != nil {
		return x.IsAssigned
	}
	return false
}

type ExerciseByCourse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Exercises          []*Exercise            `protobuf:"bytes,1,rep,name=exercises,proto3" json:"exercises,omitempty"`
	ExerciseByPrograms []*Exercise            `protobuf:"bytes,2,rep,name=exercise_by_programs,json=exerciseByPrograms,proto3" json:"exercise_by_programs,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ExerciseByCourse) Reset() {
	*x = ExerciseByCourse{}
	mi := &file_exercise_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExerciseByCourse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExerciseByCourse) ProtoMessage() {}

func (x *ExerciseByCourse) ProtoReflect() protoreflect.Message {
	mi := &file_exercise_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExerciseByCourse.ProtoReflect.Descriptor instead.
func (*ExerciseByCourse) Descriptor() ([]byte, []int) {
	return file_exercise_proto_rawDescGZIP(), []int{6}
}

func (x *ExerciseByCourse) GetExercises() []*Exercise {
	if x != nil {
		return x.Exercises
	}
	return nil
}

func (x *ExerciseByCourse) GetExerciseByPrograms() []*Exercise {
	if x != nil {
		return x.ExerciseByPrograms
	}
	return nil
}

var File_exercise_proto protoreflect.FileDescriptor

const file_exercise_proto_rawDesc = "" +
	"\n" +
	"\x0eexercise.proto\x12\x04prot\"4\n" +
	"\fExerciseFile\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\"\xd8\x04\n" +
	"\bExercise\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"time_limit\x18\x04 \x01(\x03R\ttimeLimit\x12\x1b\n" +
	"\tmax_score\x18\x05 \x01(\x02R\bmaxScore\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x1f\n" +
	"\vcover_image\x18\a \x01(\tR\n" +
	"coverImage\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"created_by\x18\t \x01(\x03R\tcreatedBy\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\x03R\tupdatedAt\x12\x1d\n" +
	"\n" +
	"updated_by\x18\v \x01(\x03R\tupdatedBy\x12\x1a\n" +
	"\bdeadline\x18\f \x01(\x03R\bdeadline\x12\x1f\n" +
	"\vis_assigned\x18\r \x01(\bR\n" +
	"isAssigned\x12'\n" +
	"\x0ftotal_questions\x18\x0e \x01(\x05R\x0etotalQuestions\x12!\n" +
	"\fobject_title\x18\x0f \x01(\tR\vobjectTitle\x12,\n" +
	"\x12is_random_question\x18\x10 \x01(\bR\x10isRandomQuestion\x12#\n" +
	"\rquestion_form\x18\x11 \x01(\tR\fquestionForm\x129\n" +
	"\x0equestion_files\x18\x12 \x03(\v2\x12.prot.ExerciseFileR\rquestionFiles\"\xe3\x03\n" +
	"\x0fExerciseRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"time_limit\x18\x04 \x01(\x03R\ttimeLimit\x12\x1b\n" +
	"\tmax_score\x18\x05 \x01(\x02R\bmaxScore\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x1f\n" +
	"\vcover_image\x18\a \x01(\tR\n" +
	"coverImage\x12\x1a\n" +
	"\bdeadline\x18\b \x01(\x03R\bdeadline\x12\x1f\n" +
	"\vis_assigned\x18\t \x01(\bR\n" +
	"isAssigned\x12'\n" +
	"\x0ftotal_questions\x18\n" +
	" \x01(\x05R\x0etotalQuestions\x12!\n" +
	"\fobject_title\x18\v \x01(\tR\vobjectTitle\x12,\n" +
	"\x12is_random_question\x18\f \x01(\bR\x10isRandomQuestion\x12#\n" +
	"\rquestion_form\x18\r \x01(\tR\fquestionForm\x129\n" +
	"\x0equestion_files\x18\x0e \x03(\v2\x12.prot.ExerciseFileR\rquestionFiles\"Z\n" +
	"\x14ExerciseListResponse\x12,\n" +
	"\texercises\x18\x01 \x03(\v2\x0e.prot.ExerciseR\texercises\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"j\n" +
	"\x15ClonedExerciseRequest\x12\x1b\n" +
	"\tlesson_id\x18\x01 \x01(\x03R\blessonId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"m\n" +
	"\x10AssignedExercise\x12\x1b\n" +
	"\tlesson_id\x18\x01 \x01(\x03R\blessonId\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\x03R\bcourseId\x12\x1f\n" +
	"\vis_assigned\x18\x03 \x01(\bR\n" +
	"isAssigned\"\x82\x01\n" +
	"\x10ExerciseByCourse\x12,\n" +
	"\texercises\x18\x01 \x03(\v2\x0e.prot.ExerciseR\texercises\x12@\n" +
	"\x14exercise_by_programs\x18\x02 \x03(\v2\x0e.prot.ExerciseR\x12exerciseByProgramsB\x16Z\x14be-cleverschool/protb\x06proto3"

var (
	file_exercise_proto_rawDescOnce sync.Once
	file_exercise_proto_rawDescData []byte
)

func file_exercise_proto_rawDescGZIP() []byte {
	file_exercise_proto_rawDescOnce.Do(func() {
		file_exercise_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_exercise_proto_rawDesc), len(file_exercise_proto_rawDesc)))
	})
	return file_exercise_proto_rawDescData
}

var file_exercise_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_exercise_proto_goTypes = []any{
	(*ExerciseFile)(nil),          // 0: prot.ExerciseFile
	(*Exercise)(nil),              // 1: prot.Exercise
	(*ExerciseRequest)(nil),       // 2: prot.ExerciseRequest
	(*ExerciseListResponse)(nil),  // 3: prot.ExerciseListResponse
	(*ClonedExerciseRequest)(nil), // 4: prot.ClonedExerciseRequest
	(*AssignedExercise)(nil),      // 5: prot.AssignedExercise
	(*ExerciseByCourse)(nil),      // 6: prot.ExerciseByCourse
}
var file_exercise_proto_depIdxs = []int32{
	0, // 0: prot.Exercise.question_files:type_name -> prot.ExerciseFile
	0, // 1: prot.ExerciseRequest.question_files:type_name -> prot.ExerciseFile
	1, // 2: prot.ExerciseListResponse.exercises:type_name -> prot.Exercise
	1, // 3: prot.ExerciseByCourse.exercises:type_name -> prot.Exercise
	1, // 4: prot.ExerciseByCourse.exercise_by_programs:type_name -> prot.Exercise
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_exercise_proto_init() }
func file_exercise_proto_init() {
	if File_exercise_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_exercise_proto_rawDesc), len(file_exercise_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_exercise_proto_goTypes,
		DependencyIndexes: file_exercise_proto_depIdxs,
		MessageInfos:      file_exercise_proto_msgTypes,
	}.Build()
	File_exercise_proto = out.File
	file_exercise_proto_goTypes = nil
	file_exercise_proto_depIdxs = nil
}
