syntax = "proto3";

package prot;

option go_package = "be-Clever School/prot";

import "school.proto";

// ----------- Faculty message -----------

message Faculty {
  int64 id = 1;
  string name = 2;
  string code = 3;
  string description = 4;
  bool status = 5;
  int64 school_id = 6;
  School school = 7;
  string name_head = 8;
  string avatar = 9;
  string created_at = 10;
  string updated_at = 11;
}

message FacultyRequest {
  int64 id = 1;
  string name = 2;
  string code = 3;
  string description = 4;
  bool status = 5;
  int64 school_id = 6;
  string name_head = 7;
  string avatar = 8;
}

// ----------- Response messages -----------

message FacultyResponse {
  Faculty faculty = 1;
  string message = 2;
}

message FacultiesResponse {
  repeated Faculty faculties = 1;
  uint64 total_count = 2;
}

