// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: grade.proto

package prot

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Grade struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Number        int32                  `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`
	NameVn        string                 `protobuf:"bytes,3,opt,name=name_vn,json=nameVn,proto3" json:"name_vn,omitempty"`
	NameEn        string                 `protobuf:"bytes,4,opt,name=name_en,json=nameEn,proto3" json:"name_en,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Grade) Reset() {
	*x = Grade{}
	mi := &file_grade_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Grade) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Grade) ProtoMessage() {}

func (x *Grade) ProtoReflect() protoreflect.Message {
	mi := &file_grade_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Grade.ProtoReflect.Descriptor instead.
func (*Grade) Descriptor() ([]byte, []int) {
	return file_grade_proto_rawDescGZIP(), []int{0}
}

func (x *Grade) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Grade) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *Grade) GetNameVn() string {
	if x != nil {
		return x.NameVn
	}
	return ""
}

func (x *Grade) GetNameEn() string {
	if x != nil {
		return x.NameEn
	}
	return ""
}

func (x *Grade) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Grade) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type GetGradeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGradeRequest) Reset() {
	*x = GetGradeRequest{}
	mi := &file_grade_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGradeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGradeRequest) ProtoMessage() {}

func (x *GetGradeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grade_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGradeRequest.ProtoReflect.Descriptor instead.
func (*GetGradeRequest) Descriptor() ([]byte, []int) {
	return file_grade_proto_rawDescGZIP(), []int{1}
}

func (x *GetGradeRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GradeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Grade         *Grade                 `protobuf:"bytes,1,opt,name=grade,proto3" json:"grade,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GradeResponse) Reset() {
	*x = GradeResponse{}
	mi := &file_grade_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GradeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GradeResponse) ProtoMessage() {}

func (x *GradeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grade_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GradeResponse.ProtoReflect.Descriptor instead.
func (*GradeResponse) Descriptor() ([]byte, []int) {
	return file_grade_proto_rawDescGZIP(), []int{2}
}

func (x *GradeResponse) GetGrade() *Grade {
	if x != nil {
		return x.Grade
	}
	return nil
}

func (x *GradeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListGradesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGradesRequest) Reset() {
	*x = ListGradesRequest{}
	mi := &file_grade_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGradesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGradesRequest) ProtoMessage() {}

func (x *ListGradesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grade_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGradesRequest.ProtoReflect.Descriptor instead.
func (*ListGradesRequest) Descriptor() ([]byte, []int) {
	return file_grade_proto_rawDescGZIP(), []int{3}
}

type GradeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Number        int32                  `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`
	NameVn        string                 `protobuf:"bytes,3,opt,name=name_vn,json=nameVn,proto3" json:"name_vn,omitempty"`
	NameEn        string                 `protobuf:"bytes,4,opt,name=name_en,json=nameEn,proto3" json:"name_en,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GradeRequest) Reset() {
	*x = GradeRequest{}
	mi := &file_grade_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GradeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GradeRequest) ProtoMessage() {}

func (x *GradeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grade_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GradeRequest.ProtoReflect.Descriptor instead.
func (*GradeRequest) Descriptor() ([]byte, []int) {
	return file_grade_proto_rawDescGZIP(), []int{4}
}

func (x *GradeRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GradeRequest) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *GradeRequest) GetNameVn() string {
	if x != nil {
		return x.NameVn
	}
	return ""
}

func (x *GradeRequest) GetNameEn() string {
	if x != nil {
		return x.NameEn
	}
	return ""
}

type GradeIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GradeIDRequest) Reset() {
	*x = GradeIDRequest{}
	mi := &file_grade_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GradeIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GradeIDRequest) ProtoMessage() {}

func (x *GradeIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grade_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GradeIDRequest.ProtoReflect.Descriptor instead.
func (*GradeIDRequest) Descriptor() ([]byte, []int) {
	return file_grade_proto_rawDescGZIP(), []int{5}
}

func (x *GradeIDRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GradesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Grades        []*Grade               `protobuf:"bytes,1,rep,name=grades,proto3" json:"grades,omitempty"`
	TotalCount    uint64                 `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GradesResponse) Reset() {
	*x = GradesResponse{}
	mi := &file_grade_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GradesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GradesResponse) ProtoMessage() {}

func (x *GradesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grade_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GradesResponse.ProtoReflect.Descriptor instead.
func (*GradesResponse) Descriptor() ([]byte, []int) {
	return file_grade_proto_rawDescGZIP(), []int{6}
}

func (x *GradesResponse) GetGrades() []*Grade {
	if x != nil {
		return x.Grades
	}
	return nil
}

func (x *GradesResponse) GetTotalCount() uint64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

var File_grade_proto protoreflect.FileDescriptor

const file_grade_proto_rawDesc = "" +
	"\n" +
	"\vgrade.proto\x12\x04prot\"\x9f\x01\n" +
	"\x05Grade\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06number\x18\x02 \x01(\x05R\x06number\x12\x17\n" +
	"\aname_vn\x18\x03 \x01(\tR\x06nameVn\x12\x17\n" +
	"\aname_en\x18\x04 \x01(\tR\x06nameEn\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\"!\n" +
	"\x0fGetGradeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"L\n" +
	"\rGradeResponse\x12!\n" +
	"\x05grade\x18\x01 \x01(\v2\v.prot.GradeR\x05grade\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x13\n" +
	"\x11ListGradesRequest\"h\n" +
	"\fGradeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06number\x18\x02 \x01(\x05R\x06number\x12\x17\n" +
	"\aname_vn\x18\x03 \x01(\tR\x06nameVn\x12\x17\n" +
	"\aname_en\x18\x04 \x01(\tR\x06nameEn\" \n" +
	"\x0eGradeIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"V\n" +
	"\x0eGradesResponse\x12#\n" +
	"\x06grades\x18\x01 \x03(\v2\v.prot.GradeR\x06grades\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x04R\n" +
	"totalCountB\x16Z\x14be-cleverschool/protb\x06proto3"

var (
	file_grade_proto_rawDescOnce sync.Once
	file_grade_proto_rawDescData []byte
)

func file_grade_proto_rawDescGZIP() []byte {
	file_grade_proto_rawDescOnce.Do(func() {
		file_grade_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grade_proto_rawDesc), len(file_grade_proto_rawDesc)))
	})
	return file_grade_proto_rawDescData
}

var file_grade_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_grade_proto_goTypes = []any{
	(*Grade)(nil),             // 0: prot.Grade
	(*GetGradeRequest)(nil),   // 1: prot.GetGradeRequest
	(*GradeResponse)(nil),     // 2: prot.GradeResponse
	(*ListGradesRequest)(nil), // 3: prot.ListGradesRequest
	(*GradeRequest)(nil),      // 4: prot.GradeRequest
	(*GradeIDRequest)(nil),    // 5: prot.GradeIDRequest
	(*GradesResponse)(nil),    // 6: prot.GradesResponse
}
var file_grade_proto_depIdxs = []int32{
	0, // 0: prot.GradeResponse.grade:type_name -> prot.Grade
	0, // 1: prot.GradesResponse.grades:type_name -> prot.Grade
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_grade_proto_init() }
func file_grade_proto_init() {
	if File_grade_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grade_proto_rawDesc), len(file_grade_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_grade_proto_goTypes,
		DependencyIndexes: file_grade_proto_depIdxs,
		MessageInfos:      file_grade_proto_msgTypes,
	}.Build()
	File_grade_proto = out.File
	file_grade_proto_goTypes = nil
	file_grade_proto_depIdxs = nil
}
