// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.0
// source: heading.proto

package prot

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Heading struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ChapterId     int64                  `protobuf:"varint,2,opt,name=chapter_id,json=chapterId,proto3" json:"chapter_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Lessons       []*LessonInfo          `protobuf:"bytes,5,rep,name=lessons,proto3" json:"lessons,omitempty"`
	Time          int32                  `protobuf:"varint,6,opt,name=time,proto3" json:"time,omitempty"`
	SortPosition  int32                  `protobuf:"varint,7,opt,name=sort_position,json=sortPosition,proto3" json:"sort_position,omitempty"`
	Target        string                 `protobuf:"bytes,8,opt,name=target,proto3" json:"target,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heading) Reset() {
	*x = Heading{}
	mi := &file_heading_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heading) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heading) ProtoMessage() {}

func (x *Heading) ProtoReflect() protoreflect.Message {
	mi := &file_heading_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heading.ProtoReflect.Descriptor instead.
func (*Heading) Descriptor() ([]byte, []int) {
	return file_heading_proto_rawDescGZIP(), []int{0}
}

func (x *Heading) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Heading) GetChapterId() int64 {
	if x != nil {
		return x.ChapterId
	}
	return 0
}

func (x *Heading) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Heading) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Heading) GetLessons() []*LessonInfo {
	if x != nil {
		return x.Lessons
	}
	return nil
}

func (x *Heading) GetTime() int32 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *Heading) GetSortPosition() int32 {
	if x != nil {
		return x.SortPosition
	}
	return 0
}

func (x *Heading) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Heading) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Heading) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type HeadingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ChapterId     int64                  `protobuf:"varint,2,opt,name=chapter_id,json=chapterId,proto3" json:"chapter_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Lessons       []*LessonInfo          `protobuf:"bytes,6,rep,name=lessons,proto3" json:"lessons,omitempty"`
	Time          int32                  `protobuf:"varint,7,opt,name=time,proto3" json:"time,omitempty"`
	SortPosition  int32                  `protobuf:"varint,8,opt,name=sort_position,json=sortPosition,proto3" json:"sort_position,omitempty"`
	Target        string                 `protobuf:"bytes,9,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeadingRequest) Reset() {
	*x = HeadingRequest{}
	mi := &file_heading_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeadingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeadingRequest) ProtoMessage() {}

func (x *HeadingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_heading_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeadingRequest.ProtoReflect.Descriptor instead.
func (*HeadingRequest) Descriptor() ([]byte, []int) {
	return file_heading_proto_rawDescGZIP(), []int{1}
}

func (x *HeadingRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *HeadingRequest) GetChapterId() int64 {
	if x != nil {
		return x.ChapterId
	}
	return 0
}

func (x *HeadingRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HeadingRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *HeadingRequest) GetLessons() []*LessonInfo {
	if x != nil {
		return x.Lessons
	}
	return nil
}

func (x *HeadingRequest) GetTime() int32 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *HeadingRequest) GetSortPosition() int32 {
	if x != nil {
		return x.SortPosition
	}
	return 0
}

func (x *HeadingRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

type HeadingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Headings      []*Heading             `protobuf:"bytes,1,rep,name=headings,proto3" json:"headings,omitempty"`
	TotalCount    uint64                 `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeadingsResponse) Reset() {
	*x = HeadingsResponse{}
	mi := &file_heading_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeadingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeadingsResponse) ProtoMessage() {}

func (x *HeadingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_heading_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeadingsResponse.ProtoReflect.Descriptor instead.
func (*HeadingsResponse) Descriptor() ([]byte, []int) {
	return file_heading_proto_rawDescGZIP(), []int{2}
}

func (x *HeadingsResponse) GetHeadings() []*Heading {
	if x != nil {
		return x.Headings
	}
	return nil
}

func (x *HeadingsResponse) GetTotalCount() uint64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

var File_heading_proto protoreflect.FileDescriptor

const file_heading_proto_rawDesc = "" +
	"\n" +
	"\rheading.proto\x12\x04prot\x1a\flesson.proto\"\xa9\x02\n" +
	"\aHeading\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"chapter_id\x18\x02 \x01(\x03R\tchapterId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12*\n" +
	"\alessons\x18\x05 \x03(\v2\x10.prot.LessonInfoR\alessons\x12\x12\n" +
	"\x04time\x18\x06 \x01(\x05R\x04time\x12#\n" +
	"\rsort_position\x18\a \x01(\x05R\fsortPosition\x12\x16\n" +
	"\x06target\x18\b \x01(\tR\x06target\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\tR\tupdatedAt\"\xf2\x01\n" +
	"\x0eHeadingRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"chapter_id\x18\x02 \x01(\x03R\tchapterId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12*\n" +
	"\alessons\x18\x06 \x03(\v2\x10.prot.LessonInfoR\alessons\x12\x12\n" +
	"\x04time\x18\a \x01(\x05R\x04time\x12#\n" +
	"\rsort_position\x18\b \x01(\x05R\fsortPosition\x12\x16\n" +
	"\x06target\x18\t \x01(\tR\x06target\"^\n" +
	"\x10HeadingsResponse\x12)\n" +
	"\bheadings\x18\x01 \x03(\v2\r.prot.HeadingR\bheadings\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x04R\n" +
	"totalCountB\rZ\vbe-lms/protb\x06proto3"

var (
	file_heading_proto_rawDescOnce sync.Once
	file_heading_proto_rawDescData []byte
)

func file_heading_proto_rawDescGZIP() []byte {
	file_heading_proto_rawDescOnce.Do(func() {
		file_heading_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_heading_proto_rawDesc), len(file_heading_proto_rawDesc)))
	})
	return file_heading_proto_rawDescData
}

var file_heading_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_heading_proto_goTypes = []any{
	(*Heading)(nil),          // 0: prot.Heading
	(*HeadingRequest)(nil),   // 1: prot.HeadingRequest
	(*HeadingsResponse)(nil), // 2: prot.HeadingsResponse
	(*LessonInfo)(nil),       // 3: prot.LessonInfo
}
var file_heading_proto_depIdxs = []int32{
	3, // 0: prot.Heading.lessons:type_name -> prot.LessonInfo
	3, // 1: prot.HeadingRequest.lessons:type_name -> prot.LessonInfo
	0, // 2: prot.HeadingsResponse.headings:type_name -> prot.Heading
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_heading_proto_init() }
func file_heading_proto_init() {
	if File_heading_proto != nil {
		return
	}
	file_lesson_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_heading_proto_rawDesc), len(file_heading_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_heading_proto_goTypes,
		DependencyIndexes: file_heading_proto_depIdxs,
		MessageInfos:      file_heading_proto_msgTypes,
	}.Build()
	File_heading_proto = out.File
	file_heading_proto_goTypes = nil
	file_heading_proto_depIdxs = nil
}
