syntax = "proto3";

package prot;

option go_package = "be-lms/prot";

message LessonPlan {
  int64 id = 1;
  string name = 2;
  string description = 3;
  string cover_image = 4;
  int32 status = 5;
  int32 sort_position = 6;
  int64 total_time = 7;
  int32 views = 8;
  int64 created_at = 9;
  int64 updated_at = 10;
  bool is_complete = 11;
  int64 complete_at = 12;
  string object_title = 13;
}

message LessonPlanListResponse {
  repeated LessonPlan lessonPlans = 1;
  int64 total = 2;
}

message LessonPlanRequest {
  int64 id = 1;
  string name = 2;
  string description = 3;
  string cover_image = 4;
  int32 status = 5;
  int32 sort_position = 6;
  int64 total_time = 7;
  int32 views = 8;
  int64 created_at = 9;
  int64 updated_at = 10;
  bool is_complete = 11;
  int64 complete_at = 12;
  int64 lesson_id = 13;
  string object_title = 14;
}

message LessonPlanCompleteRequest {
  bool is_complete = 1;
}

message LessonPlanByCourse {
  repeated LessonPlan lesson_plans = 1;
  repeated LessonPlan lesson_plan_by_programs = 2;
}

//protoc --go_out=. --go_opt=paths=source_relative prot/lesson_plan.proto
