// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.0
// source: lesson_plan.proto

package prot

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LessonPlanFacultyInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LessonPlanFacultyInfo) Reset() {
	*x = LessonPlanFacultyInfo{}
	mi := &file_lesson_plan_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LessonPlanFacultyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LessonPlanFacultyInfo) ProtoMessage() {}

func (x *LessonPlanFacultyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_lesson_plan_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LessonPlanFacultyInfo.ProtoReflect.Descriptor instead.
func (*LessonPlanFacultyInfo) Descriptor() ([]byte, []int) {
	return file_lesson_plan_proto_rawDescGZIP(), []int{0}
}

func (x *LessonPlanFacultyInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LessonPlanFacultyInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LessonPlanFacultyInfo) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *LessonPlanFacultyInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type LessonPlanSubjectInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Faculty       *LessonPlanFacultyInfo `protobuf:"bytes,4,opt,name=faculty,proto3" json:"faculty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LessonPlanSubjectInfo) Reset() {
	*x = LessonPlanSubjectInfo{}
	mi := &file_lesson_plan_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LessonPlanSubjectInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LessonPlanSubjectInfo) ProtoMessage() {}

func (x *LessonPlanSubjectInfo) ProtoReflect() protoreflect.Message {
	mi := &file_lesson_plan_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LessonPlanSubjectInfo.ProtoReflect.Descriptor instead.
func (*LessonPlanSubjectInfo) Descriptor() ([]byte, []int) {
	return file_lesson_plan_proto_rawDescGZIP(), []int{1}
}

func (x *LessonPlanSubjectInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LessonPlanSubjectInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LessonPlanSubjectInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *LessonPlanSubjectInfo) GetFaculty() *LessonPlanFacultyInfo {
	if x != nil {
		return x.Faculty
	}
	return nil
}

type LessonPlanProgramInfo struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Id            int64                    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Subjects      []*LessonPlanSubjectInfo `protobuf:"bytes,4,rep,name=subjects,proto3" json:"subjects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LessonPlanProgramInfo) Reset() {
	*x = LessonPlanProgramInfo{}
	mi := &file_lesson_plan_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LessonPlanProgramInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LessonPlanProgramInfo) ProtoMessage() {}

func (x *LessonPlanProgramInfo) ProtoReflect() protoreflect.Message {
	mi := &file_lesson_plan_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LessonPlanProgramInfo.ProtoReflect.Descriptor instead.
func (*LessonPlanProgramInfo) Descriptor() ([]byte, []int) {
	return file_lesson_plan_proto_rawDescGZIP(), []int{2}
}

func (x *LessonPlanProgramInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LessonPlanProgramInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LessonPlanProgramInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *LessonPlanProgramInfo) GetSubjects() []*LessonPlanSubjectInfo {
	if x != nil {
		return x.Subjects
	}
	return nil
}

type LessonPlanChapterInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Program       *LessonPlanProgramInfo `protobuf:"bytes,4,opt,name=program,proto3" json:"program,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LessonPlanChapterInfo) Reset() {
	*x = LessonPlanChapterInfo{}
	mi := &file_lesson_plan_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LessonPlanChapterInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LessonPlanChapterInfo) ProtoMessage() {}

func (x *LessonPlanChapterInfo) ProtoReflect() protoreflect.Message {
	mi := &file_lesson_plan_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LessonPlanChapterInfo.ProtoReflect.Descriptor instead.
func (*LessonPlanChapterInfo) Descriptor() ([]byte, []int) {
	return file_lesson_plan_proto_rawDescGZIP(), []int{3}
}

func (x *LessonPlanChapterInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LessonPlanChapterInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *LessonPlanChapterInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *LessonPlanChapterInfo) GetProgram() *LessonPlanProgramInfo {
	if x != nil {
		return x.Program
	}
	return nil
}

type LessonPlanLessonInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Chapter       *LessonPlanChapterInfo `protobuf:"bytes,4,opt,name=chapter,proto3" json:"chapter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LessonPlanLessonInfo) Reset() {
	*x = LessonPlanLessonInfo{}
	mi := &file_lesson_plan_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LessonPlanLessonInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LessonPlanLessonInfo) ProtoMessage() {}

func (x *LessonPlanLessonInfo) ProtoReflect() protoreflect.Message {
	mi := &file_lesson_plan_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LessonPlanLessonInfo.ProtoReflect.Descriptor instead.
func (*LessonPlanLessonInfo) Descriptor() ([]byte, []int) {
	return file_lesson_plan_proto_rawDescGZIP(), []int{4}
}

func (x *LessonPlanLessonInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LessonPlanLessonInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *LessonPlanLessonInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *LessonPlanLessonInfo) GetChapter() *LessonPlanChapterInfo {
	if x != nil {
		return x.Chapter
	}
	return nil
}

type LessonPlanAuthor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LessonPlanAuthor) Reset() {
	*x = LessonPlanAuthor{}
	mi := &file_lesson_plan_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LessonPlanAuthor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LessonPlanAuthor) ProtoMessage() {}

func (x *LessonPlanAuthor) ProtoReflect() protoreflect.Message {
	mi := &file_lesson_plan_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LessonPlanAuthor.ProtoReflect.Descriptor instead.
func (*LessonPlanAuthor) Descriptor() ([]byte, []int) {
	return file_lesson_plan_proto_rawDescGZIP(), []int{5}
}

func (x *LessonPlanAuthor) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LessonPlanAuthor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LessonPlanAuthor) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type LessonPlan struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Id            int64                   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                  `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	CoverImage    string                  `protobuf:"bytes,4,opt,name=cover_image,json=coverImage,proto3" json:"cover_image,omitempty"`
	Status        int32                   `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	SortPosition  int32                   `protobuf:"varint,6,opt,name=sort_position,json=sortPosition,proto3" json:"sort_position,omitempty"`
	TotalTime     int64                   `protobuf:"varint,7,opt,name=total_time,json=totalTime,proto3" json:"total_time,omitempty"`
	Views         int32                   `protobuf:"varint,8,opt,name=views,proto3" json:"views,omitempty"`
	CreatedAt     int64                   `protobuf:"varint,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                   `protobuf:"varint,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	IsComplete    bool                    `protobuf:"varint,11,opt,name=is_complete,json=isComplete,proto3" json:"is_complete,omitempty"`
	CompleteAt    int64                   `protobuf:"varint,12,opt,name=complete_at,json=completeAt,proto3" json:"complete_at,omitempty"`
	ObjectTitle   string                  `protobuf:"bytes,13,opt,name=object_title,json=objectTitle,proto3" json:"object_title,omitempty"`
	AuthorId      int64                   `protobuf:"varint,14,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Author        *LessonPlanAuthor       `protobuf:"bytes,15,opt,name=author,proto3" json:"author,omitempty"`
	Lessons       []*LessonPlanLessonInfo `protobuf:"bytes,16,rep,name=lessons,proto3" json:"lessons,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LessonPlan) Reset() {
	*x = LessonPlan{}
	mi := &file_lesson_plan_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LessonPlan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LessonPlan) ProtoMessage() {}

func (x *LessonPlan) ProtoReflect() protoreflect.Message {
	mi := &file_lesson_plan_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LessonPlan.ProtoReflect.Descriptor instead.
func (*LessonPlan) Descriptor() ([]byte, []int) {
	return file_lesson_plan_proto_rawDescGZIP(), []int{6}
}

func (x *LessonPlan) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LessonPlan) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LessonPlan) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *LessonPlan) GetCoverImage() string {
	if x != nil {
		return x.CoverImage
	}
	return ""
}

func (x *LessonPlan) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *LessonPlan) GetSortPosition() int32 {
	if x != nil {
		return x.SortPosition
	}
	return 0
}

func (x *LessonPlan) GetTotalTime() int64 {
	if x != nil {
		return x.TotalTime
	}
	return 0
}

func (x *LessonPlan) GetViews() int32 {
	if x != nil {
		return x.Views
	}
	return 0
}

func (x *LessonPlan) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *LessonPlan) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *LessonPlan) GetIsComplete() bool {
	if x != nil {
		return x.IsComplete
	}
	return false
}

func (x *LessonPlan) GetCompleteAt() int64 {
	if x != nil {
		return x.CompleteAt
	}
	return 0
}

func (x *LessonPlan) GetObjectTitle() string {
	if x != nil {
		return x.ObjectTitle
	}
	return ""
}

func (x *LessonPlan) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *LessonPlan) GetAuthor() *LessonPlanAuthor {
	if x != nil {
		return x.Author
	}
	return nil
}

func (x *LessonPlan) GetLessons() []*LessonPlanLessonInfo {
	if x != nil {
		return x.Lessons
	}
	return nil
}

type LessonPlanListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LessonPlans   []*LessonPlan          `protobuf:"bytes,1,rep,name=lessonPlans,proto3" json:"lessonPlans,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LessonPlanListResponse) Reset() {
	*x = LessonPlanListResponse{}
	mi := &file_lesson_plan_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LessonPlanListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LessonPlanListResponse) ProtoMessage() {}

func (x *LessonPlanListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lesson_plan_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LessonPlanListResponse.ProtoReflect.Descriptor instead.
func (*LessonPlanListResponse) Descriptor() ([]byte, []int) {
	return file_lesson_plan_proto_rawDescGZIP(), []int{7}
}

func (x *LessonPlanListResponse) GetLessonPlans() []*LessonPlan {
	if x != nil {
		return x.LessonPlans
	}
	return nil
}

func (x *LessonPlanListResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type LessonPlanRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Id            int64                   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                  `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	CoverImage    string                  `protobuf:"bytes,4,opt,name=cover_image,json=coverImage,proto3" json:"cover_image,omitempty"`
	Status        int32                   `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	SortPosition  int32                   `protobuf:"varint,6,opt,name=sort_position,json=sortPosition,proto3" json:"sort_position,omitempty"`
	TotalTime     int64                   `protobuf:"varint,7,opt,name=total_time,json=totalTime,proto3" json:"total_time,omitempty"`
	Views         int32                   `protobuf:"varint,8,opt,name=views,proto3" json:"views,omitempty"`
	CreatedAt     int64                   `protobuf:"varint,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                   `protobuf:"varint,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	IsComplete    bool                    `protobuf:"varint,11,opt,name=is_complete,json=isComplete,proto3" json:"is_complete,omitempty"`
	CompleteAt    int64                   `protobuf:"varint,12,opt,name=complete_at,json=completeAt,proto3" json:"complete_at,omitempty"`
	LessonId      int64                   `protobuf:"varint,13,opt,name=lesson_id,json=lessonId,proto3" json:"lesson_id,omitempty"`
	ObjectTitle   string                  `protobuf:"bytes,14,opt,name=object_title,json=objectTitle,proto3" json:"object_title,omitempty"`
	AuthorId      int64                   `protobuf:"varint,15,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Author        *LessonPlanAuthor       `protobuf:"bytes,16,opt,name=author,proto3" json:"author,omitempty"`
	Lessons       []*LessonPlanLessonInfo `protobuf:"bytes,17,rep,name=lessons,proto3" json:"lessons,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LessonPlanRequest) Reset() {
	*x = LessonPlanRequest{}
	mi := &file_lesson_plan_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LessonPlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LessonPlanRequest) ProtoMessage() {}

func (x *LessonPlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lesson_plan_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LessonPlanRequest.ProtoReflect.Descriptor instead.
func (*LessonPlanRequest) Descriptor() ([]byte, []int) {
	return file_lesson_plan_proto_rawDescGZIP(), []int{8}
}

func (x *LessonPlanRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LessonPlanRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LessonPlanRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *LessonPlanRequest) GetCoverImage() string {
	if x != nil {
		return x.CoverImage
	}
	return ""
}

func (x *LessonPlanRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *LessonPlanRequest) GetSortPosition() int32 {
	if x != nil {
		return x.SortPosition
	}
	return 0
}

func (x *LessonPlanRequest) GetTotalTime() int64 {
	if x != nil {
		return x.TotalTime
	}
	return 0
}

func (x *LessonPlanRequest) GetViews() int32 {
	if x != nil {
		return x.Views
	}
	return 0
}

func (x *LessonPlanRequest) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *LessonPlanRequest) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *LessonPlanRequest) GetIsComplete() bool {
	if x != nil {
		return x.IsComplete
	}
	return false
}

func (x *LessonPlanRequest) GetCompleteAt() int64 {
	if x != nil {
		return x.CompleteAt
	}
	return 0
}

func (x *LessonPlanRequest) GetLessonId() int64 {
	if x != nil {
		return x.LessonId
	}
	return 0
}

func (x *LessonPlanRequest) GetObjectTitle() string {
	if x != nil {
		return x.ObjectTitle
	}
	return ""
}

func (x *LessonPlanRequest) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *LessonPlanRequest) GetAuthor() *LessonPlanAuthor {
	if x != nil {
		return x.Author
	}
	return nil
}

func (x *LessonPlanRequest) GetLessons() []*LessonPlanLessonInfo {
	if x != nil {
		return x.Lessons
	}
	return nil
}

type LessonPlanCompleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsComplete    bool                   `protobuf:"varint,1,opt,name=is_complete,json=isComplete,proto3" json:"is_complete,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LessonPlanCompleteRequest) Reset() {
	*x = LessonPlanCompleteRequest{}
	mi := &file_lesson_plan_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LessonPlanCompleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LessonPlanCompleteRequest) ProtoMessage() {}

func (x *LessonPlanCompleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lesson_plan_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LessonPlanCompleteRequest.ProtoReflect.Descriptor instead.
func (*LessonPlanCompleteRequest) Descriptor() ([]byte, []int) {
	return file_lesson_plan_proto_rawDescGZIP(), []int{9}
}

func (x *LessonPlanCompleteRequest) GetIsComplete() bool {
	if x != nil {
		return x.IsComplete
	}
	return false
}

type LessonPlanByCourse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	LessonPlans          []*LessonPlan          `protobuf:"bytes,1,rep,name=lesson_plans,json=lessonPlans,proto3" json:"lesson_plans,omitempty"`
	LessonPlanByPrograms []*LessonPlan          `protobuf:"bytes,2,rep,name=lesson_plan_by_programs,json=lessonPlanByPrograms,proto3" json:"lesson_plan_by_programs,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *LessonPlanByCourse) Reset() {
	*x = LessonPlanByCourse{}
	mi := &file_lesson_plan_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LessonPlanByCourse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LessonPlanByCourse) ProtoMessage() {}

func (x *LessonPlanByCourse) ProtoReflect() protoreflect.Message {
	mi := &file_lesson_plan_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LessonPlanByCourse.ProtoReflect.Descriptor instead.
func (*LessonPlanByCourse) Descriptor() ([]byte, []int) {
	return file_lesson_plan_proto_rawDescGZIP(), []int{10}
}

func (x *LessonPlanByCourse) GetLessonPlans() []*LessonPlan {
	if x != nil {
		return x.LessonPlans
	}
	return nil
}

func (x *LessonPlanByCourse) GetLessonPlanByPrograms() []*LessonPlan {
	if x != nil {
		return x.LessonPlanByPrograms
	}
	return nil
}

var File_lesson_plan_proto protoreflect.FileDescriptor

const file_lesson_plan_proto_rawDesc = "" +
	"\n" +
	"\x11lesson_plan.proto\x12\x04prot\"q\n" +
	"\x15LessonPlanFacultyInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"\x94\x01\n" +
	"\x15LessonPlanSubjectInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x125\n" +
	"\afaculty\x18\x04 \x01(\v2\x1b.prot.LessonPlanFacultyInfoR\afaculty\"\x96\x01\n" +
	"\x15LessonPlanProgramInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x127\n" +
	"\bsubjects\x18\x04 \x03(\v2\x1b.prot.LessonPlanSubjectInfoR\bsubjects\"\x96\x01\n" +
	"\x15LessonPlanChapterInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x125\n" +
	"\aprogram\x18\x04 \x01(\v2\x1b.prot.LessonPlanProgramInfoR\aprogram\"\x95\x01\n" +
	"\x14LessonPlanLessonInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x125\n" +
	"\achapter\x18\x04 \x01(\v2\x1b.prot.LessonPlanChapterInfoR\achapter\"N\n" +
	"\x10LessonPlanAuthor\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\"\x8b\x04\n" +
	"\n" +
	"LessonPlan\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1f\n" +
	"\vcover_image\x18\x04 \x01(\tR\n" +
	"coverImage\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\x12#\n" +
	"\rsort_position\x18\x06 \x01(\x05R\fsortPosition\x12\x1d\n" +
	"\n" +
	"total_time\x18\a \x01(\x03R\ttotalTime\x12\x14\n" +
	"\x05views\x18\b \x01(\x05R\x05views\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\x03R\tupdatedAt\x12\x1f\n" +
	"\vis_complete\x18\v \x01(\bR\n" +
	"isComplete\x12\x1f\n" +
	"\vcomplete_at\x18\f \x01(\x03R\n" +
	"completeAt\x12!\n" +
	"\fobject_title\x18\r \x01(\tR\vobjectTitle\x12\x1b\n" +
	"\tauthor_id\x18\x0e \x01(\x03R\bauthorId\x12.\n" +
	"\x06author\x18\x0f \x01(\v2\x16.prot.LessonPlanAuthorR\x06author\x124\n" +
	"\alessons\x18\x10 \x03(\v2\x1a.prot.LessonPlanLessonInfoR\alessons\"b\n" +
	"\x16LessonPlanListResponse\x122\n" +
	"\vlessonPlans\x18\x01 \x03(\v2\x10.prot.LessonPlanR\vlessonPlans\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\xaf\x04\n" +
	"\x11LessonPlanRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1f\n" +
	"\vcover_image\x18\x04 \x01(\tR\n" +
	"coverImage\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\x12#\n" +
	"\rsort_position\x18\x06 \x01(\x05R\fsortPosition\x12\x1d\n" +
	"\n" +
	"total_time\x18\a \x01(\x03R\ttotalTime\x12\x14\n" +
	"\x05views\x18\b \x01(\x05R\x05views\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\x03R\tupdatedAt\x12\x1f\n" +
	"\vis_complete\x18\v \x01(\bR\n" +
	"isComplete\x12\x1f\n" +
	"\vcomplete_at\x18\f \x01(\x03R\n" +
	"completeAt\x12\x1b\n" +
	"\tlesson_id\x18\r \x01(\x03R\blessonId\x12!\n" +
	"\fobject_title\x18\x0e \x01(\tR\vobjectTitle\x12\x1b\n" +
	"\tauthor_id\x18\x0f \x01(\x03R\bauthorId\x12.\n" +
	"\x06author\x18\x10 \x01(\v2\x16.prot.LessonPlanAuthorR\x06author\x124\n" +
	"\alessons\x18\x11 \x03(\v2\x1a.prot.LessonPlanLessonInfoR\alessons\"<\n" +
	"\x19LessonPlanCompleteRequest\x12\x1f\n" +
	"\vis_complete\x18\x01 \x01(\bR\n" +
	"isComplete\"\x92\x01\n" +
	"\x12LessonPlanByCourse\x123\n" +
	"\flesson_plans\x18\x01 \x03(\v2\x10.prot.LessonPlanR\vlessonPlans\x12G\n" +
	"\x17lesson_plan_by_programs\x18\x02 \x03(\v2\x10.prot.LessonPlanR\x14lessonPlanByProgramsB\rZ\vbe-Clever School/protb\x06proto3"

var (
	file_lesson_plan_proto_rawDescOnce sync.Once
	file_lesson_plan_proto_rawDescData []byte
)

func file_lesson_plan_proto_rawDescGZIP() []byte {
	file_lesson_plan_proto_rawDescOnce.Do(func() {
		file_lesson_plan_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lesson_plan_proto_rawDesc), len(file_lesson_plan_proto_rawDesc)))
	})
	return file_lesson_plan_proto_rawDescData
}

var file_lesson_plan_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_lesson_plan_proto_goTypes = []any{
	(*LessonPlanFacultyInfo)(nil),     // 0: prot.LessonPlanFacultyInfo
	(*LessonPlanSubjectInfo)(nil),     // 1: prot.LessonPlanSubjectInfo
	(*LessonPlanProgramInfo)(nil),     // 2: prot.LessonPlanProgramInfo
	(*LessonPlanChapterInfo)(nil),     // 3: prot.LessonPlanChapterInfo
	(*LessonPlanLessonInfo)(nil),      // 4: prot.LessonPlanLessonInfo
	(*LessonPlanAuthor)(nil),          // 5: prot.LessonPlanAuthor
	(*LessonPlan)(nil),                // 6: prot.LessonPlan
	(*LessonPlanListResponse)(nil),    // 7: prot.LessonPlanListResponse
	(*LessonPlanRequest)(nil),         // 8: prot.LessonPlanRequest
	(*LessonPlanCompleteRequest)(nil), // 9: prot.LessonPlanCompleteRequest
	(*LessonPlanByCourse)(nil),        // 10: prot.LessonPlanByCourse
}
var file_lesson_plan_proto_depIdxs = []int32{
	0,  // 0: prot.LessonPlanSubjectInfo.faculty:type_name -> prot.LessonPlanFacultyInfo
	1,  // 1: prot.LessonPlanProgramInfo.subjects:type_name -> prot.LessonPlanSubjectInfo
	2,  // 2: prot.LessonPlanChapterInfo.program:type_name -> prot.LessonPlanProgramInfo
	3,  // 3: prot.LessonPlanLessonInfo.chapter:type_name -> prot.LessonPlanChapterInfo
	5,  // 4: prot.LessonPlan.author:type_name -> prot.LessonPlanAuthor
	4,  // 5: prot.LessonPlan.lessons:type_name -> prot.LessonPlanLessonInfo
	6,  // 6: prot.LessonPlanListResponse.lessonPlans:type_name -> prot.LessonPlan
	5,  // 7: prot.LessonPlanRequest.author:type_name -> prot.LessonPlanAuthor
	4,  // 8: prot.LessonPlanRequest.lessons:type_name -> prot.LessonPlanLessonInfo
	6,  // 9: prot.LessonPlanByCourse.lesson_plans:type_name -> prot.LessonPlan
	6,  // 10: prot.LessonPlanByCourse.lesson_plan_by_programs:type_name -> prot.LessonPlan
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_lesson_plan_proto_init() }
func file_lesson_plan_proto_init() {
	if File_lesson_plan_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lesson_plan_proto_rawDesc), len(file_lesson_plan_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_lesson_plan_proto_goTypes,
		DependencyIndexes: file_lesson_plan_proto_depIdxs,
		MessageInfos:      file_lesson_plan_proto_msgTypes,
	}.Build()
	File_lesson_plan_proto = out.File
	file_lesson_plan_proto_goTypes = nil
	file_lesson_plan_proto_depIdxs = nil
}
