syntax = "proto3";

package prot;

option go_package = "be-Clever School/prot";

message Notice {
  int64 id = 1;
  string cover = 2;
  string title = 3;
  string description = 4;
  string content = 5;
  string created_at = 6;
  int64 created_by = 7;
  string updated_at = 8;
  int64 updated_by = 9;
  bool status = 10;
  string type = 11;
  repeated NotificationLog logs = 12;
}

message NoticeListResponse {
  repeated Notice notices = 1;
  int64 total_count = 2;
  int64 page = 3;
  int64 page_size = 4;
}

message NotificationData {
  string value = 1;
  string type = 2;
  int32 success_count = 3;
  int32 failed_count = 4;
  string error = 5;
}

message NotificationLog {
  int64 id = 1;
  int64 notice_id = 2;
  string status = 3;
  NotificationData data = 4;
  string sent_at = 5;
  string created_at = 6;
}

//protoc --go_out=. --go_opt=paths=source_relative prot/notice.proto
