// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.0
// source: notice.proto

package prot

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Notice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Cover         string                 `protobuf:"bytes,2,opt,name=cover,proto3" json:"cover,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CreatedBy     int64                  `protobuf:"varint,7,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	UpdatedBy     int64                  `protobuf:"varint,9,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	Status        bool                   `protobuf:"varint,10,opt,name=status,proto3" json:"status,omitempty"`
	Type          string                 `protobuf:"bytes,11,opt,name=type,proto3" json:"type,omitempty"`
	Logs          []*NotificationLog     `protobuf:"bytes,12,rep,name=logs,proto3" json:"logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notice) Reset() {
	*x = Notice{}
	mi := &file_notice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notice) ProtoMessage() {}

func (x *Notice) ProtoReflect() protoreflect.Message {
	mi := &file_notice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notice.ProtoReflect.Descriptor instead.
func (*Notice) Descriptor() ([]byte, []int) {
	return file_notice_proto_rawDescGZIP(), []int{0}
}

func (x *Notice) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Notice) GetCover() string {
	if x != nil {
		return x.Cover
	}
	return ""
}

func (x *Notice) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Notice) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Notice) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Notice) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Notice) GetCreatedBy() int64 {
	if x != nil {
		return x.CreatedBy
	}
	return 0
}

func (x *Notice) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Notice) GetUpdatedBy() int64 {
	if x != nil {
		return x.UpdatedBy
	}
	return 0
}

func (x *Notice) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *Notice) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Notice) GetLogs() []*NotificationLog {
	if x != nil {
		return x.Logs
	}
	return nil
}

type NoticeListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notices       []*Notice              `protobuf:"bytes,1,rep,name=notices,proto3" json:"notices,omitempty"`
	TotalCount    int64                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Page          int64                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int64                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoticeListResponse) Reset() {
	*x = NoticeListResponse{}
	mi := &file_notice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoticeListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoticeListResponse) ProtoMessage() {}

func (x *NoticeListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoticeListResponse.ProtoReflect.Descriptor instead.
func (*NoticeListResponse) Descriptor() ([]byte, []int) {
	return file_notice_proto_rawDescGZIP(), []int{1}
}

func (x *NoticeListResponse) GetNotices() []*Notice {
	if x != nil {
		return x.Notices
	}
	return nil
}

func (x *NoticeListResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *NoticeListResponse) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *NoticeListResponse) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type NotificationData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	SuccessCount  int32                  `protobuf:"varint,3,opt,name=success_count,json=successCount,proto3" json:"success_count,omitempty"`
	FailedCount   int32                  `protobuf:"varint,4,opt,name=failed_count,json=failedCount,proto3" json:"failed_count,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationData) Reset() {
	*x = NotificationData{}
	mi := &file_notice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationData) ProtoMessage() {}

func (x *NotificationData) ProtoReflect() protoreflect.Message {
	mi := &file_notice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationData.ProtoReflect.Descriptor instead.
func (*NotificationData) Descriptor() ([]byte, []int) {
	return file_notice_proto_rawDescGZIP(), []int{2}
}

func (x *NotificationData) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *NotificationData) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *NotificationData) GetSuccessCount() int32 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

func (x *NotificationData) GetFailedCount() int32 {
	if x != nil {
		return x.FailedCount
	}
	return 0
}

func (x *NotificationData) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type NotificationLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	NoticeId      int64                  `protobuf:"varint,2,opt,name=notice_id,json=noticeId,proto3" json:"notice_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Data          *NotificationData      `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	SentAt        string                 `protobuf:"bytes,5,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationLog) Reset() {
	*x = NotificationLog{}
	mi := &file_notice_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationLog) ProtoMessage() {}

func (x *NotificationLog) ProtoReflect() protoreflect.Message {
	mi := &file_notice_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationLog.ProtoReflect.Descriptor instead.
func (*NotificationLog) Descriptor() ([]byte, []int) {
	return file_notice_proto_rawDescGZIP(), []int{3}
}

func (x *NotificationLog) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *NotificationLog) GetNoticeId() int64 {
	if x != nil {
		return x.NoticeId
	}
	return 0
}

func (x *NotificationLog) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *NotificationLog) GetData() *NotificationData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *NotificationLog) GetSentAt() string {
	if x != nil {
		return x.SentAt
	}
	return ""
}

func (x *NotificationLog) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

var File_notice_proto protoreflect.FileDescriptor

const file_notice_proto_rawDesc = "" +
	"\n" +
	"\fnotice.proto\x12\x04prot\"\xd3\x02\n" +
	"\x06Notice\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05cover\x18\x02 \x01(\tR\x05cover\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"created_by\x18\a \x01(\x03R\tcreatedBy\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"updated_by\x18\t \x01(\x03R\tupdatedBy\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\bR\x06status\x12\x12\n" +
	"\x04type\x18\v \x01(\tR\x04type\x12)\n" +
	"\x04logs\x18\f \x03(\v2\x15.prot.NotificationLogR\x04logs\"\x8e\x01\n" +
	"\x12NoticeListResponse\x12&\n" +
	"\anotices\x18\x01 \x03(\v2\f.prot.NoticeR\anotices\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x03R\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x03R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x03R\bpageSize\"\x9a\x01\n" +
	"\x10NotificationData\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12#\n" +
	"\rsuccess_count\x18\x03 \x01(\x05R\fsuccessCount\x12!\n" +
	"\ffailed_count\x18\x04 \x01(\x05R\vfailedCount\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"\xba\x01\n" +
	"\x0fNotificationLog\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tnotice_id\x18\x02 \x01(\x03R\bnoticeId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12*\n" +
	"\x04data\x18\x04 \x01(\v2\x16.prot.NotificationDataR\x04data\x12\x17\n" +
	"\asent_at\x18\x05 \x01(\tR\x06sentAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAtB\rZ\vbe-cleverschool/protb\x06proto3"

var (
	file_notice_proto_rawDescOnce sync.Once
	file_notice_proto_rawDescData []byte
)

func file_notice_proto_rawDescGZIP() []byte {
	file_notice_proto_rawDescOnce.Do(func() {
		file_notice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notice_proto_rawDesc), len(file_notice_proto_rawDesc)))
	})
	return file_notice_proto_rawDescData
}

var file_notice_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_notice_proto_goTypes = []any{
	(*Notice)(nil),             // 0: prot.Notice
	(*NoticeListResponse)(nil), // 1: prot.NoticeListResponse
	(*NotificationData)(nil),   // 2: prot.NotificationData
	(*NotificationLog)(nil),    // 3: prot.NotificationLog
}
var file_notice_proto_depIdxs = []int32{
	3, // 0: prot.Notice.logs:type_name -> prot.NotificationLog
	0, // 1: prot.NoticeListResponse.notices:type_name -> prot.Notice
	2, // 2: prot.NotificationLog.data:type_name -> prot.NotificationData
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_notice_proto_init() }
func file_notice_proto_init() {
	if File_notice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notice_proto_rawDesc), len(file_notice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_notice_proto_goTypes,
		DependencyIndexes: file_notice_proto_depIdxs,
		MessageInfos:      file_notice_proto_msgTypes,
	}.Build()
	File_notice_proto = out.File
	file_notice_proto_goTypes = nil
	file_notice_proto_depIdxs = nil
}

