// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.0
// source: program.proto

package prot

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Program struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SubjectId       int64                  `protobuf:"varint,2,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	Name            string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description     string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Image           string                 `protobuf:"bytes,5,opt,name=image,proto3" json:"image,omitempty"`
	Status          bool                   `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	Target          string                 `protobuf:"bytes,7,opt,name=target,proto3" json:"target,omitempty"`
	Subject         *Subject               `protobuf:"bytes,8,opt,name=subject,proto3" json:"subject,omitempty"`
	Courses         []*Course              `protobuf:"bytes,9,rep,name=courses,proto3" json:"courses,omitempty"`
	Chapters        []*Chapter             `protobuf:"bytes,10,rep,name=chapters,proto3" json:"chapters,omitempty"`
	Duration        int32                  `protobuf:"varint,11,opt,name=duration,proto3" json:"duration,omitempty"`
	CurrentStudents int32                  `protobuf:"varint,12,opt,name=current_students,json=currentStudents,proto3" json:"current_students,omitempty"`
	Type            string                 `protobuf:"bytes,13,opt,name=type,proto3" json:"type,omitempty"`
	CreatedAt       string                 `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       string                 `protobuf:"bytes,15,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	VtgInfo         *ProgramVTGInfo        `protobuf:"bytes,16,opt,name=vtg_info,json=vtgInfo,proto3" json:"vtg_info,omitempty"`
	Subjects        []*Subject             `protobuf:"bytes,17,rep,name=subjects,proto3" json:"subjects,omitempty"`
	BookUrl         string                 `protobuf:"bytes,18,opt,name=book_url,json=bookUrl,proto3" json:"book_url,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Program) Reset() {
	*x = Program{}
	mi := &file_program_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Program) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Program) ProtoMessage() {}

func (x *Program) ProtoReflect() protoreflect.Message {
	mi := &file_program_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Program.ProtoReflect.Descriptor instead.
func (*Program) Descriptor() ([]byte, []int) {
	return file_program_proto_rawDescGZIP(), []int{0}
}

func (x *Program) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Program) GetSubjectId() int64 {
	if x != nil {
		return x.SubjectId
	}
	return 0
}

func (x *Program) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Program) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Program) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *Program) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *Program) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Program) GetSubject() *Subject {
	if x != nil {
		return x.Subject
	}
	return nil
}

func (x *Program) GetCourses() []*Course {
	if x != nil {
		return x.Courses
	}
	return nil
}

func (x *Program) GetChapters() []*Chapter {
	if x != nil {
		return x.Chapters
	}
	return nil
}

func (x *Program) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *Program) GetCurrentStudents() int32 {
	if x != nil {
		return x.CurrentStudents
	}
	return 0
}

func (x *Program) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Program) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Program) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Program) GetVtgInfo() *ProgramVTGInfo {
	if x != nil {
		return x.VtgInfo
	}
	return nil
}

func (x *Program) GetSubjects() []*Subject {
	if x != nil {
		return x.Subjects
	}
	return nil
}

func (x *Program) GetBookUrl() string {
	if x != nil {
		return x.BookUrl
	}
	return ""
}

type ProgramVTGInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Code             string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	ManagementCode   string                 `protobuf:"bytes,2,opt,name=management_code,json=managementCode,proto3" json:"management_code,omitempty"`
	NumberOfCredits  int32                  `protobuf:"varint,3,opt,name=number_of_credits,json=numberOfCredits,proto3" json:"number_of_credits,omitempty"`
	Time             string                 `protobuf:"bytes,4,opt,name=time,proto3" json:"time,omitempty"`
	TheoreticalTime  string                 `protobuf:"bytes,5,opt,name=theoretical_time,json=theoreticalTime,proto3" json:"theoretical_time,omitempty"`
	DiscussionTime   string                 `protobuf:"bytes,6,opt,name=discussion_time,json=discussionTime,proto3" json:"discussion_time,omitempty"`
	PracticeTime     string                 `protobuf:"bytes,7,opt,name=practice_time,json=practiceTime,proto3" json:"practice_time,omitempty"`
	TestTime         string                 `protobuf:"bytes,8,opt,name=test_time,json=testTime,proto3" json:"test_time,omitempty"`
	StudyModule      string                 `protobuf:"bytes,9,opt,name=study_module,json=studyModule,proto3" json:"study_module,omitempty"`
	NumberOfFrequent int32                  `protobuf:"varint,10,opt,name=number_of_frequent,json=numberOfFrequent,proto3" json:"number_of_frequent,omitempty"`
	NumberOfEvaluate int32                  `protobuf:"varint,11,opt,name=number_of_evaluate,json=numberOfEvaluate,proto3" json:"number_of_evaluate,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ProgramVTGInfo) Reset() {
	*x = ProgramVTGInfo{}
	mi := &file_program_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgramVTGInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgramVTGInfo) ProtoMessage() {}

func (x *ProgramVTGInfo) ProtoReflect() protoreflect.Message {
	mi := &file_program_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgramVTGInfo.ProtoReflect.Descriptor instead.
func (*ProgramVTGInfo) Descriptor() ([]byte, []int) {
	return file_program_proto_rawDescGZIP(), []int{1}
}

func (x *ProgramVTGInfo) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ProgramVTGInfo) GetManagementCode() string {
	if x != nil {
		return x.ManagementCode
	}
	return ""
}

func (x *ProgramVTGInfo) GetNumberOfCredits() int32 {
	if x != nil {
		return x.NumberOfCredits
	}
	return 0
}

func (x *ProgramVTGInfo) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *ProgramVTGInfo) GetTheoreticalTime() string {
	if x != nil {
		return x.TheoreticalTime
	}
	return ""
}

func (x *ProgramVTGInfo) GetDiscussionTime() string {
	if x != nil {
		return x.DiscussionTime
	}
	return ""
}

func (x *ProgramVTGInfo) GetPracticeTime() string {
	if x != nil {
		return x.PracticeTime
	}
	return ""
}

func (x *ProgramVTGInfo) GetTestTime() string {
	if x != nil {
		return x.TestTime
	}
	return ""
}

func (x *ProgramVTGInfo) GetStudyModule() string {
	if x != nil {
		return x.StudyModule
	}
	return ""
}

func (x *ProgramVTGInfo) GetNumberOfFrequent() int32 {
	if x != nil {
		return x.NumberOfFrequent
	}
	return 0
}

func (x *ProgramVTGInfo) GetNumberOfEvaluate() int32 {
	if x != nil {
		return x.NumberOfEvaluate
	}
	return 0
}

type ProgramRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Status        bool                   `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	SubjectId     int64                  `protobuf:"varint,5,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	Target        string                 `protobuf:"bytes,6,opt,name=target,proto3" json:"target,omitempty"`
	Image         string                 `protobuf:"bytes,7,opt,name=image,proto3" json:"image,omitempty"`
	Duration      int32                  `protobuf:"varint,8,opt,name=duration,proto3" json:"duration,omitempty"`
	Type          string                 `protobuf:"bytes,9,opt,name=type,proto3" json:"type,omitempty"`
	VtgInfo       *ProgramVTGInfo        `protobuf:"bytes,10,opt,name=vtg_info,json=vtgInfo,proto3" json:"vtg_info,omitempty"`
	Subjects      []*Subject             `protobuf:"bytes,11,rep,name=subjects,proto3" json:"subjects,omitempty"`
	BookUrl       string                 `protobuf:"bytes,12,opt,name=book_url,json=bookUrl,proto3" json:"book_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgramRequest) Reset() {
	*x = ProgramRequest{}
	mi := &file_program_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgramRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgramRequest) ProtoMessage() {}

func (x *ProgramRequest) ProtoReflect() protoreflect.Message {
	mi := &file_program_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgramRequest.ProtoReflect.Descriptor instead.
func (*ProgramRequest) Descriptor() ([]byte, []int) {
	return file_program_proto_rawDescGZIP(), []int{2}
}

func (x *ProgramRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProgramRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProgramRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProgramRequest) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *ProgramRequest) GetSubjectId() int64 {
	if x != nil {
		return x.SubjectId
	}
	return 0
}

func (x *ProgramRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *ProgramRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ProgramRequest) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *ProgramRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ProgramRequest) GetVtgInfo() *ProgramVTGInfo {
	if x != nil {
		return x.VtgInfo
	}
	return nil
}

func (x *ProgramRequest) GetSubjects() []*Subject {
	if x != nil {
		return x.Subjects
	}
	return nil
}

func (x *ProgramRequest) GetBookUrl() string {
	if x != nil {
		return x.BookUrl
	}
	return ""
}

type ProgramsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Programs      []*Program             `protobuf:"bytes,1,rep,name=programs,proto3" json:"programs,omitempty"`
	TotalCount    uint64                 `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgramsResponse) Reset() {
	*x = ProgramsResponse{}
	mi := &file_program_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgramsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgramsResponse) ProtoMessage() {}

func (x *ProgramsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_program_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgramsResponse.ProtoReflect.Descriptor instead.
func (*ProgramsResponse) Descriptor() ([]byte, []int) {
	return file_program_proto_rawDescGZIP(), []int{3}
}

func (x *ProgramsResponse) GetPrograms() []*Program {
	if x != nil {
		return x.Programs
	}
	return nil
}

func (x *ProgramsResponse) GetTotalCount() uint64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type ReSyncProgram struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      int64                  `protobuf:"varint,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	CourseIds     []int64                `protobuf:"varint,2,rep,packed,name=course_ids,json=courseIds,proto3" json:"course_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReSyncProgram) Reset() {
	*x = ReSyncProgram{}
	mi := &file_program_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReSyncProgram) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReSyncProgram) ProtoMessage() {}

func (x *ReSyncProgram) ProtoReflect() protoreflect.Message {
	mi := &file_program_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReSyncProgram.ProtoReflect.Descriptor instead.
func (*ReSyncProgram) Descriptor() ([]byte, []int) {
	return file_program_proto_rawDescGZIP(), []int{4}
}

func (x *ReSyncProgram) GetCourseId() int64 {
	if x != nil {
		return x.CourseId
	}
	return 0
}

func (x *ReSyncProgram) GetCourseIds() []int64 {
	if x != nil {
		return x.CourseIds
	}
	return nil
}

type ChapterSort struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChapterSort) Reset() {
	*x = ChapterSort{}
	mi := &file_program_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChapterSort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChapterSort) ProtoMessage() {}

func (x *ChapterSort) ProtoReflect() protoreflect.Message {
	mi := &file_program_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChapterSort.ProtoReflect.Descriptor instead.
func (*ChapterSort) Descriptor() ([]byte, []int) {
	return file_program_proto_rawDescGZIP(), []int{5}
}

func (x *ChapterSort) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ProgramChapterSort struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chapters      []*ChapterSort         `protobuf:"bytes,1,rep,name=chapters,proto3" json:"chapters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgramChapterSort) Reset() {
	*x = ProgramChapterSort{}
	mi := &file_program_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgramChapterSort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgramChapterSort) ProtoMessage() {}

func (x *ProgramChapterSort) ProtoReflect() protoreflect.Message {
	mi := &file_program_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgramChapterSort.ProtoReflect.Descriptor instead.
func (*ProgramChapterSort) Descriptor() ([]byte, []int) {
	return file_program_proto_rawDescGZIP(), []int{6}
}

func (x *ProgramChapterSort) GetChapters() []*ChapterSort {
	if x != nil {
		return x.Chapters
	}
	return nil
}

var File_program_proto protoreflect.FileDescriptor

const file_program_proto_rawDesc = "" +
	"\n" +
	"\rprogram.proto\x12\x04prot\x1a\fcourse.proto\x1a\rsubject.proto\x1a\rchapter.proto\"\xc0\x04\n" +
	"\aProgram\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x02 \x01(\x03R\tsubjectId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x14\n" +
	"\x05image\x18\x05 \x01(\tR\x05image\x12\x16\n" +
	"\x06status\x18\x06 \x01(\bR\x06status\x12\x16\n" +
	"\x06target\x18\a \x01(\tR\x06target\x12'\n" +
	"\asubject\x18\b \x01(\v2\r.prot.SubjectR\asubject\x12&\n" +
	"\acourses\x18\t \x03(\v2\f.prot.CourseR\acourses\x12)\n" +
	"\bchapters\x18\n" +
	" \x03(\v2\r.prot.ChapterR\bchapters\x12\x1a\n" +
	"\bduration\x18\v \x01(\x05R\bduration\x12)\n" +
	"\x10current_students\x18\f \x01(\x05R\x0fcurrentStudents\x12\x12\n" +
	"\x04type\x18\r \x01(\tR\x04type\x12\x1d\n" +
	"\n" +
	"created_at\x18\x0e \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x0f \x01(\tR\tupdatedAt\x12/\n" +
	"\bvtg_info\x18\x10 \x01(\v2\x14.prot.ProgramVTGInfoR\avtgInfo\x12)\n" +
	"\bsubjects\x18\x11 \x03(\v2\r.prot.SubjectR\bsubjects\x12\x19\n" +
	"\bbook_url\x18\x12 \x01(\tR\abookUrl\"\xa2\x03\n" +
	"\x0eProgramVTGInfo\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12'\n" +
	"\x0fmanagement_code\x18\x02 \x01(\tR\x0emanagementCode\x12*\n" +
	"\x11number_of_credits\x18\x03 \x01(\x05R\x0fnumberOfCredits\x12\x12\n" +
	"\x04time\x18\x04 \x01(\tR\x04time\x12)\n" +
	"\x10theoretical_time\x18\x05 \x01(\tR\x0ftheoreticalTime\x12'\n" +
	"\x0fdiscussion_time\x18\x06 \x01(\tR\x0ediscussionTime\x12#\n" +
	"\rpractice_time\x18\a \x01(\tR\fpracticeTime\x12\x1b\n" +
	"\ttest_time\x18\b \x01(\tR\btestTime\x12!\n" +
	"\fstudy_module\x18\t \x01(\tR\vstudyModule\x12,\n" +
	"\x12number_of_frequent\x18\n" +
	" \x01(\x05R\x10numberOfFrequent\x12,\n" +
	"\x12number_of_evaluate\x18\v \x01(\x05R\x10numberOfEvaluate\"\xe2\x02\n" +
	"\x0eProgramRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\x04 \x01(\bR\x06status\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x05 \x01(\x03R\tsubjectId\x12\x16\n" +
	"\x06target\x18\x06 \x01(\tR\x06target\x12\x14\n" +
	"\x05image\x18\a \x01(\tR\x05image\x12\x1a\n" +
	"\bduration\x18\b \x01(\x05R\bduration\x12\x12\n" +
	"\x04type\x18\t \x01(\tR\x04type\x12/\n" +
	"\bvtg_info\x18\n" +
	" \x01(\v2\x14.prot.ProgramVTGInfoR\avtgInfo\x12)\n" +
	"\bsubjects\x18\v \x03(\v2\r.prot.SubjectR\bsubjects\x12\x19\n" +
	"\bbook_url\x18\f \x01(\tR\abookUrl\"^\n" +
	"\x10ProgramsResponse\x12)\n" +
	"\bprograms\x18\x01 \x03(\v2\r.prot.ProgramR\bprograms\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x04R\n" +
	"totalCount\"K\n" +
	"\rReSyncProgram\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\x03R\bcourseId\x12\x1d\n" +
	"\n" +
	"course_ids\x18\x02 \x03(\x03R\tcourseIds\"\x1d\n" +
	"\vChapterSort\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"C\n" +
	"\x12ProgramChapterSort\x12-\n" +
	"\bchapters\x18\x01 \x03(\v2\x11.prot.ChapterSortR\bchaptersB\rZ\vbe-lms/protb\x06proto3"

var (
	file_program_proto_rawDescOnce sync.Once
	file_program_proto_rawDescData []byte
)

func file_program_proto_rawDescGZIP() []byte {
	file_program_proto_rawDescOnce.Do(func() {
		file_program_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_program_proto_rawDesc), len(file_program_proto_rawDesc)))
	})
	return file_program_proto_rawDescData
}

var file_program_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_program_proto_goTypes = []any{
	(*Program)(nil),            // 0: prot.Program
	(*ProgramVTGInfo)(nil),     // 1: prot.ProgramVTGInfo
	(*ProgramRequest)(nil),     // 2: prot.ProgramRequest
	(*ProgramsResponse)(nil),   // 3: prot.ProgramsResponse
	(*ReSyncProgram)(nil),      // 4: prot.ReSyncProgram
	(*ChapterSort)(nil),        // 5: prot.ChapterSort
	(*ProgramChapterSort)(nil), // 6: prot.ProgramChapterSort
	(*Subject)(nil),            // 7: prot.Subject
	(*Course)(nil),             // 8: prot.Course
	(*Chapter)(nil),            // 9: prot.Chapter
}
var file_program_proto_depIdxs = []int32{
	7, // 0: prot.Program.subject:type_name -> prot.Subject
	8, // 1: prot.Program.courses:type_name -> prot.Course
	9, // 2: prot.Program.chapters:type_name -> prot.Chapter
	1, // 3: prot.Program.vtg_info:type_name -> prot.ProgramVTGInfo
	7, // 4: prot.Program.subjects:type_name -> prot.Subject
	1, // 5: prot.ProgramRequest.vtg_info:type_name -> prot.ProgramVTGInfo
	7, // 6: prot.ProgramRequest.subjects:type_name -> prot.Subject
	0, // 7: prot.ProgramsResponse.programs:type_name -> prot.Program
	5, // 8: prot.ProgramChapterSort.chapters:type_name -> prot.ChapterSort
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_program_proto_init() }
func file_program_proto_init() {
	if File_program_proto != nil {
		return
	}
	file_course_proto_init()
	file_subject_proto_init()
	file_chapter_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_program_proto_rawDesc), len(file_program_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_program_proto_goTypes,
		DependencyIndexes: file_program_proto_depIdxs,
		MessageInfos:      file_program_proto_msgTypes,
	}.Build()
	File_program_proto = out.File
	file_program_proto_goTypes = nil
	file_program_proto_depIdxs = nil
}
