// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: question.proto

package prot

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MapPosition struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PositionX      int32                  `protobuf:"varint,2,opt,name=position_x,json=positionX,proto3" json:"position_x,omitempty"`
	PositionY      int32                  `protobuf:"varint,3,opt,name=position_y,json=positionY,proto3" json:"position_y,omitempty"`
	PositionWidth  int32                  `protobuf:"varint,4,opt,name=position_width,json=positionWidth,proto3" json:"position_width,omitempty"`
	PositionHeight int32                  `protobuf:"varint,5,opt,name=position_height,json=positionHeight,proto3" json:"position_height,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MapPosition) Reset() {
	*x = MapPosition{}
	mi := &file_question_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapPosition) ProtoMessage() {}

func (x *MapPosition) ProtoReflect() protoreflect.Message {
	mi := &file_question_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapPosition.ProtoReflect.Descriptor instead.
func (*MapPosition) Descriptor() ([]byte, []int) {
	return file_question_proto_rawDescGZIP(), []int{0}
}

func (x *MapPosition) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MapPosition) GetPositionX() int32 {
	if x != nil {
		return x.PositionX
	}
	return 0
}

func (x *MapPosition) GetPositionY() int32 {
	if x != nil {
		return x.PositionY
	}
	return 0
}

func (x *MapPosition) GetPositionWidth() int32 {
	if x != nil {
		return x.PositionWidth
	}
	return 0
}

func (x *MapPosition) GetPositionHeight() int32 {
	if x != nil {
		return x.PositionHeight
	}
	return 0
}

type Matching struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FileUrl       string                 `protobuf:"bytes,2,opt,name=file_url,json=fileUrl,proto3" json:"file_url,omitempty"`
	Kind          string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Matching) Reset() {
	*x = Matching{}
	mi := &file_question_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Matching) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Matching) ProtoMessage() {}

func (x *Matching) ProtoReflect() protoreflect.Message {
	mi := &file_question_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Matching.ProtoReflect.Descriptor instead.
func (*Matching) Descriptor() ([]byte, []int) {
	return file_question_proto_rawDescGZIP(), []int{1}
}

func (x *Matching) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Matching) GetFileUrl() string {
	if x != nil {
		return x.FileUrl
	}
	return ""
}

func (x *Matching) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Matching) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type MediaQuestion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	File          []byte                 `protobuf:"bytes,3,opt,name=file,proto3" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaQuestion) Reset() {
	*x = MediaQuestion{}
	mi := &file_question_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaQuestion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaQuestion) ProtoMessage() {}

func (x *MediaQuestion) ProtoReflect() protoreflect.Message {
	mi := &file_question_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaQuestion.ProtoReflect.Descriptor instead.
func (*MediaQuestion) Descriptor() ([]byte, []int) {
	return file_question_proto_rawDescGZIP(), []int{2}
}

func (x *MediaQuestion) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *MediaQuestion) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *MediaQuestion) GetFile() []byte {
	if x != nil {
		return x.File
	}
	return nil
}

type QuestionContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Media         *MediaQuestion         `protobuf:"bytes,2,opt,name=media,proto3" json:"media,omitempty"`
	Medias        []*MediaQuestion       `protobuf:"bytes,3,rep,name=medias,proto3" json:"medias,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuestionContent) Reset() {
	*x = QuestionContent{}
	mi := &file_question_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuestionContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestionContent) ProtoMessage() {}

func (x *QuestionContent) ProtoReflect() protoreflect.Message {
	mi := &file_question_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestionContent.ProtoReflect.Descriptor instead.
func (*QuestionContent) Descriptor() ([]byte, []int) {
	return file_question_proto_rawDescGZIP(), []int{3}
}

func (x *QuestionContent) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *QuestionContent) GetMedia() *MediaQuestion {
	if x != nil {
		return x.Media
	}
	return nil
}

func (x *QuestionContent) GetMedias() []*MediaQuestion {
	if x != nil {
		return x.Medias
	}
	return nil
}

type QuestionMetaData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instructions  string                 `protobuf:"bytes,1,opt,name=instructions,proto3" json:"instructions,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Points        float64                `protobuf:"fixed64,3,opt,name=points,proto3" json:"points,omitempty"`
	Time          float32                `protobuf:"fixed32,4,opt,name=time,proto3" json:"time,omitempty"`
	IsRandom      bool                   `protobuf:"varint,5,opt,name=is_random,json=isRandom,proto3" json:"is_random,omitempty"`
	Display       string                 `protobuf:"bytes,6,opt,name=display,proto3" json:"display,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuestionMetaData) Reset() {
	*x = QuestionMetaData{}
	mi := &file_question_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuestionMetaData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestionMetaData) ProtoMessage() {}

func (x *QuestionMetaData) ProtoReflect() protoreflect.Message {
	mi := &file_question_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestionMetaData.ProtoReflect.Descriptor instead.
func (*QuestionMetaData) Descriptor() ([]byte, []int) {
	return file_question_proto_rawDescGZIP(), []int{4}
}

func (x *QuestionMetaData) GetInstructions() string {
	if x != nil {
		return x.Instructions
	}
	return ""
}

func (x *QuestionMetaData) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *QuestionMetaData) GetPoints() float64 {
	if x != nil {
		return x.Points
	}
	return 0
}

func (x *QuestionMetaData) GetTime() float32 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *QuestionMetaData) GetIsRandom() bool {
	if x != nil {
		return x.IsRandom
	}
	return false
}

func (x *QuestionMetaData) GetDisplay() string {
	if x != nil {
		return x.Display
	}
	return ""
}

type QuestionOption struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Answers       []*AnswerContent       `protobuf:"bytes,1,rep,name=answers,proto3" json:"answers,omitempty"`
	Sources       []*AnswerSource        `protobuf:"bytes,2,rep,name=sources,proto3" json:"sources,omitempty"`
	Targets       []*AnswerTarget        `protobuf:"bytes,3,rep,name=targets,proto3" json:"targets,omitempty"`
	Labels        []*AnswerContent       `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty"`
	Blanks        []*AnswerBlank         `protobuf:"bytes,5,rep,name=blanks,proto3" json:"blanks,omitempty"`
	Items         []*AnswerContent       `protobuf:"bytes,6,rep,name=items,proto3" json:"items,omitempty"`
	Categories    []*GroupAnswer         `protobuf:"bytes,7,rep,name=categories,proto3" json:"categories,omitempty"`
	Questions     []*AnswerContent       `protobuf:"bytes,8,rep,name=questions,proto3" json:"questions,omitempty"`
	Groups        []*GroupPosition       `protobuf:"bytes,9,rep,name=groups,proto3" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuestionOption) Reset() {
	*x = QuestionOption{}
	mi := &file_question_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuestionOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestionOption) ProtoMessage() {}

func (x *QuestionOption) ProtoReflect() protoreflect.Message {
	mi := &file_question_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestionOption.ProtoReflect.Descriptor instead.
func (*QuestionOption) Descriptor() ([]byte, []int) {
	return file_question_proto_rawDescGZIP(), []int{5}
}

func (x *QuestionOption) GetAnswers() []*AnswerContent {
	if x != nil {
		return x.Answers
	}
	return nil
}

func (x *QuestionOption) GetSources() []*AnswerSource {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *QuestionOption) GetTargets() []*AnswerTarget {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *QuestionOption) GetLabels() []*AnswerContent {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *QuestionOption) GetBlanks() []*AnswerBlank {
	if x != nil {
		return x.Blanks
	}
	return nil
}

func (x *QuestionOption) GetItems() []*AnswerContent {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *QuestionOption) GetCategories() []*GroupAnswer {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *QuestionOption) GetQuestions() []*AnswerContent {
	if x != nil {
		return x.Questions
	}
	return nil
}

func (x *QuestionOption) GetGroups() []*GroupPosition {
	if x != nil {
		return x.Groups
	}
	return nil
}

type QuestionCorrectAnswers struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []int64                `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	List          map[string]string      `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuestionCorrectAnswers) Reset() {
	*x = QuestionCorrectAnswers{}
	mi := &file_question_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuestionCorrectAnswers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestionCorrectAnswers) ProtoMessage() {}

func (x *QuestionCorrectAnswers) ProtoReflect() protoreflect.Message {
	mi := &file_question_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestionCorrectAnswers.ProtoReflect.Descriptor instead.
func (*QuestionCorrectAnswers) Descriptor() ([]byte, []int) {
	return file_question_proto_rawDescGZIP(), []int{6}
}

func (x *QuestionCorrectAnswers) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *QuestionCorrectAnswers) GetList() map[string]string {
	if x != nil {
		return x.List
	}
	return nil
}

type QuestionAttributeValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Weight        int32                  `protobuf:"varint,3,opt,name=weight,proto3" json:"weight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuestionAttributeValue) Reset() {
	*x = QuestionAttributeValue{}
	mi := &file_question_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuestionAttributeValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestionAttributeValue) ProtoMessage() {}

func (x *QuestionAttributeValue) ProtoReflect() protoreflect.Message {
	mi := &file_question_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestionAttributeValue.ProtoReflect.Descriptor instead.
func (*QuestionAttributeValue) Descriptor() ([]byte, []int) {
	return file_question_proto_rawDescGZIP(), []int{7}
}

func (x *QuestionAttributeValue) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *QuestionAttributeValue) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *QuestionAttributeValue) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

type QuestionAttributeInfo struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Id            int64                   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Value         *QuestionAttributeValue `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuestionAttributeInfo) Reset() {
	*x = QuestionAttributeInfo{}
	mi := &file_question_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuestionAttributeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestionAttributeInfo) ProtoMessage() {}

func (x *QuestionAttributeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_question_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestionAttributeInfo.ProtoReflect.Descriptor instead.
func (*QuestionAttributeInfo) Descriptor() ([]byte, []int) {
	return file_question_proto_rawDescGZIP(), []int{8}
}

func (x *QuestionAttributeInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *QuestionAttributeInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *QuestionAttributeInfo) GetValue() *QuestionAttributeValue {
	if x != nil {
		return x.Value
	}
	return nil
}

type QuestionSubjectInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuestionSubjectInfo) Reset() {
	*x = QuestionSubjectInfo{}
	mi := &file_question_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuestionSubjectInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestionSubjectInfo) ProtoMessage() {}

func (x *QuestionSubjectInfo) ProtoReflect() protoreflect.Message {
	mi := &file_question_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestionSubjectInfo.ProtoReflect.Descriptor instead.
func (*QuestionSubjectInfo) Descriptor() ([]byte, []int) {
	return file_question_proto_rawDescGZIP(), []int{9}
}

func (x *QuestionSubjectInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *QuestionSubjectInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *QuestionSubjectInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// Message for the question
type Question struct {
	state            protoimpl.MessageState   `protogen:"open.v1"`
	Id               int64                    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type             string                   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Metadata         *QuestionMetaData        `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Content          *QuestionContent         `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	SortPosition     int32                    `protobuf:"varint,5,opt,name=sort_position,json=sortPosition,proto3" json:"sort_position,omitempty"`
	ImageWidth       int32                    `protobuf:"varint,6,opt,name=image_width,json=imageWidth,proto3" json:"image_width,omitempty"`
	ImageHeight      int32                    `protobuf:"varint,7,opt,name=image_height,json=imageHeight,proto3" json:"image_height,omitempty"`
	Options          *QuestionOption          `protobuf:"bytes,8,opt,name=options,proto3" json:"options,omitempty"`
	SourceQuestionId int64                    `protobuf:"varint,9,opt,name=source_question_id,json=sourceQuestionId,proto3" json:"source_question_id,omitempty"`
	Status           bool                     `protobuf:"varint,10,opt,name=status,proto3" json:"status,omitempty"`
	Source           *SourceQuestion          `protobuf:"bytes,11,opt,name=source,proto3" json:"source,omitempty"`
	CorrectAnswers   *QuestionCorrectAnswers  `protobuf:"bytes,12,opt,name=correct_answers,json=correctAnswers,proto3" json:"correct_answers,omitempty"`
	Attributes       []*QuestionAttributeInfo `protobuf:"bytes,13,rep,name=attributes,proto3" json:"attributes,omitempty"`
	SubjectId        int64                    `protobuf:"varint,14,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	Subject          *QuestionSubjectInfo     `protobuf:"bytes,15,opt,name=subject,proto3" json:"subject,omitempty"`
	CreatedAt        string                   `protobuf:"bytes,16,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        string                   `protobuf:"bytes,17,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Question) Reset() {
	*x = Question{}
	mi := &file_question_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Question) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Question) ProtoMessage() {}

func (x *Question) ProtoReflect() protoreflect.Message {
	mi := &file_question_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Question.ProtoReflect.Descriptor instead.
func (*Question) Descriptor() ([]byte, []int) {
	return file_question_proto_rawDescGZIP(), []int{10}
}

func (x *Question) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Question) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Question) GetMetadata() *QuestionMetaData {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Question) GetContent() *QuestionContent {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Question) GetSortPosition() int32 {
	if x != nil {
		return x.SortPosition
	}
	return 0
}

func (x *Question) GetImageWidth() int32 {
	if x != nil {
		return x.ImageWidth
	}
	return 0
}

func (x *Question) GetImageHeight() int32 {
	if x != nil {
		return x.ImageHeight
	}
	return 0
}

func (x *Question) GetOptions() *QuestionOption {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *Question) GetSourceQuestionId() int64 {
	if x != nil {
		return x.SourceQuestionId
	}
	return 0
}

func (x *Question) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *Question) GetSource() *SourceQuestion {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *Question) GetCorrectAnswers() *QuestionCorrectAnswers {
	if x != nil {
		return x.CorrectAnswers
	}
	return nil
}

func (x *Question) GetAttributes() []*QuestionAttributeInfo {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *Question) GetSubjectId() int64 {
	if x != nil {
		return x.SubjectId
	}
	return 0
}

func (x *Question) GetSubject() *QuestionSubjectInfo {
	if x != nil {
		return x.Subject
	}
	return nil
}

func (x *Question) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Question) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// Request to create a new question
type QuestionRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type             string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Metadata         *QuestionMetaData      `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Content          *QuestionContent       `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	SortPosition     int32                  `protobuf:"varint,5,opt,name=sort_position,json=sortPosition,proto3" json:"sort_position,omitempty"`
	ImageWidth       int32                  `protobuf:"varint,6,opt,name=image_width,json=imageWidth,proto3" json:"image_width,omitempty"`
	ImageHeight      int32                  `protobuf:"varint,7,opt,name=image_height,json=imageHeight,proto3" json:"image_height,omitempty"`
	Options          *QuestionOption        `protobuf:"bytes,8,opt,name=options,proto3" json:"options,omitempty"`
	SourceQuestionId int64                  `protobuf:"varint,9,opt,name=source_question_id,json=sourceQuestionId,proto3" json:"source_question_id,omitempty"`
	Status           bool                   `protobuf:"varint,10,opt,name=status,proto3" json:"status,omitempty"`
	Source           *SourceQuestion        `protobuf:"bytes,11,opt,name=source,proto3" json:"source,omitempty"`
	SubjectId        int64                  `protobuf:"varint,12,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	CreatedAt        string                 `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        string                 `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *QuestionRequest) Reset() {
	*x = QuestionRequest{}
	mi := &file_question_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestionRequest) ProtoMessage() {}

func (x *QuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_question_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestionRequest.ProtoReflect.Descriptor instead.
func (*QuestionRequest) Descriptor() ([]byte, []int) {
	return file_question_proto_rawDescGZIP(), []int{11}
}

func (x *QuestionRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *QuestionRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *QuestionRequest) GetMetadata() *QuestionMetaData {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *QuestionRequest) GetContent() *QuestionContent {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *QuestionRequest) GetSortPosition() int32 {
	if x != nil {
		return x.SortPosition
	}
	return 0
}

func (x *QuestionRequest) GetImageWidth() int32 {
	if x != nil {
		return x.ImageWidth
	}
	return 0
}

func (x *QuestionRequest) GetImageHeight() int32 {
	if x != nil {
		return x.ImageHeight
	}
	return 0
}

func (x *QuestionRequest) GetOptions() *QuestionOption {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *QuestionRequest) GetSourceQuestionId() int64 {
	if x != nil {
		return x.SourceQuestionId
	}
	return 0
}

func (x *QuestionRequest) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *QuestionRequest) GetSource() *SourceQuestion {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *QuestionRequest) GetSubjectId() int64 {
	if x != nil {
		return x.SubjectId
	}
	return 0
}

func (x *QuestionRequest) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *QuestionRequest) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// Response for a single question
type QuestionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Question      *Question              `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuestionResponse) Reset() {
	*x = QuestionResponse{}
	mi := &file_question_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuestionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestionResponse) ProtoMessage() {}

func (x *QuestionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_question_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestionResponse.ProtoReflect.Descriptor instead.
func (*QuestionResponse) Descriptor() ([]byte, []int) {
	return file_question_proto_rawDescGZIP(), []int{12}
}

func (x *QuestionResponse) GetQuestion() *Question {
	if x != nil {
		return x.Question
	}
	return nil
}

func (x *QuestionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Response for multiple questions
type QuestionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Questions     []*Question            `protobuf:"bytes,1,rep,name=questions,proto3" json:"questions,omitempty"`
	TotalCount    int64                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuestionsResponse) Reset() {
	*x = QuestionsResponse{}
	mi := &file_question_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuestionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestionsResponse) ProtoMessage() {}

func (x *QuestionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_question_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestionsResponse.ProtoReflect.Descriptor instead.
func (*QuestionsResponse) Descriptor() ([]byte, []int) {
	return file_question_proto_rawDescGZIP(), []int{13}
}

func (x *QuestionsResponse) GetQuestions() []*Question {
	if x != nil {
		return x.Questions
	}
	return nil
}

func (x *QuestionsResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type CreateQuestionRelationRequest struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	ExamId                    int32                  `protobuf:"varint,1,opt,name=exam_id,json=examId,proto3" json:"exam_id,omitempty"`
	ExerciseId                int32                  `protobuf:"varint,2,opt,name=exercise_id,json=exerciseId,proto3" json:"exercise_id,omitempty"`
	LessonPlanPartId          int32                  `protobuf:"varint,3,opt,name=lesson_plan_part_id,json=lessonPlanPartId,proto3" json:"lesson_plan_part_id,omitempty"`
	HomeworkId                int32                  `protobuf:"varint,4,opt,name=homework_id,json=homeworkId,proto3" json:"homework_id,omitempty"`
	LevelTestId               int32                  `protobuf:"varint,5,opt,name=level_test_id,json=levelTestId,proto3" json:"level_test_id,omitempty"`
	LessonId                  int32                  `protobuf:"varint,6,opt,name=lesson_id,json=lessonId,proto3" json:"lesson_id,omitempty"`
	ContestRoundId            int32                  `protobuf:"varint,7,opt,name=contest_round_id,json=contestRoundId,proto3" json:"contest_round_id,omitempty"`
	QuestionScores            map[string]float64     `protobuf:"bytes,8,rep,name=question_scores,json=questionScores,proto3" json:"question_scores,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	SourceQuestionScores      map[string]float64     `protobuf:"bytes,9,rep,name=source_question_scores,json=sourceQuestionScores,proto3" json:"source_question_scores,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	IsReset                   bool                   `protobuf:"varint,10,opt,name=is_reset,json=isReset,proto3" json:"is_reset,omitempty"`
	ResetAll                  bool                   `protobuf:"varint,11,opt,name=reset_all,json=resetAll,proto3" json:"reset_all,omitempty"`
	ClearSelfScoringQuestions bool                   `protobuf:"varint,12,opt,name=clear_self_scoring_questions,json=clearSelfScoringQuestions,proto3" json:"clear_self_scoring_questions,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *CreateQuestionRelationRequest) Reset() {
	*x = CreateQuestionRelationRequest{}
	mi := &file_question_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateQuestionRelationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateQuestionRelationRequest) ProtoMessage() {}

func (x *CreateQuestionRelationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_question_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateQuestionRelationRequest.ProtoReflect.Descriptor instead.
func (*CreateQuestionRelationRequest) Descriptor() ([]byte, []int) {
	return file_question_proto_rawDescGZIP(), []int{14}
}

func (x *CreateQuestionRelationRequest) GetExamId() int32 {
	if x != nil {
		return x.ExamId
	}
	return 0
}

func (x *CreateQuestionRelationRequest) GetExerciseId() int32 {
	if x != nil {
		return x.ExerciseId
	}
	return 0
}

func (x *CreateQuestionRelationRequest) GetLessonPlanPartId() int32 {
	if x != nil {
		return x.LessonPlanPartId
	}
	return 0
}

func (x *CreateQuestionRelationRequest) GetHomeworkId() int32 {
	if x != nil {
		return x.HomeworkId
	}
	return 0
}

func (x *CreateQuestionRelationRequest) GetLevelTestId() int32 {
	if x != nil {
		return x.LevelTestId
	}
	return 0
}

func (x *CreateQuestionRelationRequest) GetLessonId() int32 {
	if x != nil {
		return x.LessonId
	}
	return 0
}

func (x *CreateQuestionRelationRequest) GetContestRoundId() int32 {
	if x != nil {
		return x.ContestRoundId
	}
	return 0
}

func (x *CreateQuestionRelationRequest) GetQuestionScores() map[string]float64 {
	if x != nil {
		return x.QuestionScores
	}
	return nil
}

func (x *CreateQuestionRelationRequest) GetSourceQuestionScores() map[string]float64 {
	if x != nil {
		return x.SourceQuestionScores
	}
	return nil
}

func (x *CreateQuestionRelationRequest) GetIsReset() bool {
	if x != nil {
		return x.IsReset
	}
	return false
}

func (x *CreateQuestionRelationRequest) GetResetAll() bool {
	if x != nil {
		return x.ResetAll
	}
	return false
}

func (x *CreateQuestionRelationRequest) GetClearSelfScoringQuestions() bool {
	if x != nil {
		return x.ClearSelfScoringQuestions
	}
	return false
}

var File_question_proto protoreflect.FileDescriptor

const file_question_proto_rawDesc = "" +
	"\n" +
	"\x0equestion.proto\x12\x04prot\x1a\fanswer.proto\x1a\x15source_question.proto\"\xab\x01\n" +
	"\vMapPosition\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"position_x\x18\x02 \x01(\x05R\tpositionX\x12\x1d\n" +
	"\n" +
	"position_y\x18\x03 \x01(\x05R\tpositionY\x12%\n" +
	"\x0eposition_width\x18\x04 \x01(\x05R\rpositionWidth\x12'\n" +
	"\x0fposition_height\x18\x05 \x01(\x05R\x0epositionHeight\"c\n" +
	"\bMatching\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\bfile_url\x18\x02 \x01(\tR\afileUrl\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\"I\n" +
	"\rMediaQuestion\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x12\n" +
	"\x04file\x18\x03 \x01(\fR\x04file\"}\n" +
	"\x0fQuestionContent\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12)\n" +
	"\x05media\x18\x02 \x01(\v2\x13.prot.MediaQuestionR\x05media\x12+\n" +
	"\x06medias\x18\x03 \x03(\v2\x13.prot.MediaQuestionR\x06medias\"\xbb\x01\n" +
	"\x10QuestionMetaData\x12\"\n" +
	"\finstructions\x18\x01 \x01(\tR\finstructions\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x16\n" +
	"\x06points\x18\x03 \x01(\x01R\x06points\x12\x12\n" +
	"\x04time\x18\x04 \x01(\x02R\x04time\x12\x1b\n" +
	"\tis_random\x18\x05 \x01(\bR\bisRandom\x12\x18\n" +
	"\adisplay\x18\x06 \x01(\tR\adisplay\"\xb1\x03\n" +
	"\x0eQuestionOption\x12-\n" +
	"\aanswers\x18\x01 \x03(\v2\x13.prot.AnswerContentR\aanswers\x12,\n" +
	"\asources\x18\x02 \x03(\v2\x12.prot.AnswerSourceR\asources\x12,\n" +
	"\atargets\x18\x03 \x03(\v2\x12.prot.AnswerTargetR\atargets\x12+\n" +
	"\x06labels\x18\x04 \x03(\v2\x13.prot.AnswerContentR\x06labels\x12)\n" +
	"\x06blanks\x18\x05 \x03(\v2\x11.prot.AnswerBlankR\x06blanks\x12)\n" +
	"\x05items\x18\x06 \x03(\v2\x13.prot.AnswerContentR\x05items\x121\n" +
	"\n" +
	"categories\x18\a \x03(\v2\x11.prot.GroupAnswerR\n" +
	"categories\x121\n" +
	"\tquestions\x18\b \x03(\v2\x13.prot.AnswerContentR\tquestions\x12+\n" +
	"\x06groups\x18\t \x03(\v2\x13.prot.GroupPositionR\x06groups\"\x9f\x01\n" +
	"\x16QuestionCorrectAnswers\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x03R\x03ids\x12:\n" +
	"\x04list\x18\x02 \x03(\v2&.prot.QuestionCorrectAnswers.ListEntryR\x04list\x1a7\n" +
	"\tListEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"T\n" +
	"\x16QuestionAttributeValue\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06weight\x18\x03 \x01(\x05R\x06weight\"o\n" +
	"\x15QuestionAttributeInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x122\n" +
	"\x05value\x18\x03 \x01(\v2\x1c.prot.QuestionAttributeValueR\x05value\"[\n" +
	"\x13QuestionSubjectInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"\xb6\x05\n" +
	"\bQuestion\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x122\n" +
	"\bmetadata\x18\x03 \x01(\v2\x16.prot.QuestionMetaDataR\bmetadata\x12/\n" +
	"\acontent\x18\x04 \x01(\v2\x15.prot.QuestionContentR\acontent\x12#\n" +
	"\rsort_position\x18\x05 \x01(\x05R\fsortPosition\x12\x1f\n" +
	"\vimage_width\x18\x06 \x01(\x05R\n" +
	"imageWidth\x12!\n" +
	"\fimage_height\x18\a \x01(\x05R\vimageHeight\x12.\n" +
	"\aoptions\x18\b \x01(\v2\x14.prot.QuestionOptionR\aoptions\x12,\n" +
	"\x12source_question_id\x18\t \x01(\x03R\x10sourceQuestionId\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\bR\x06status\x12,\n" +
	"\x06source\x18\v \x01(\v2\x14.prot.SourceQuestionR\x06source\x12E\n" +
	"\x0fcorrect_answers\x18\f \x01(\v2\x1c.prot.QuestionCorrectAnswersR\x0ecorrectAnswers\x12;\n" +
	"\n" +
	"attributes\x18\r \x03(\v2\x1b.prot.QuestionAttributeInfoR\n" +
	"attributes\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x0e \x01(\x03R\tsubjectId\x123\n" +
	"\asubject\x18\x0f \x01(\v2\x19.prot.QuestionSubjectInfoR\asubject\x12\x1d\n" +
	"\n" +
	"created_at\x18\x10 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x11 \x01(\tR\tupdatedAt\"\x84\x04\n" +
	"\x0fQuestionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x122\n" +
	"\bmetadata\x18\x03 \x01(\v2\x16.prot.QuestionMetaDataR\bmetadata\x12/\n" +
	"\acontent\x18\x04 \x01(\v2\x15.prot.QuestionContentR\acontent\x12#\n" +
	"\rsort_position\x18\x05 \x01(\x05R\fsortPosition\x12\x1f\n" +
	"\vimage_width\x18\x06 \x01(\x05R\n" +
	"imageWidth\x12!\n" +
	"\fimage_height\x18\a \x01(\x05R\vimageHeight\x12.\n" +
	"\aoptions\x18\b \x01(\v2\x14.prot.QuestionOptionR\aoptions\x12,\n" +
	"\x12source_question_id\x18\t \x01(\x03R\x10sourceQuestionId\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\bR\x06status\x12,\n" +
	"\x06source\x18\v \x01(\v2\x14.prot.SourceQuestionR\x06source\x12\x1d\n" +
	"\n" +
	"subject_id\x18\f \x01(\x03R\tsubjectId\x12\x1d\n" +
	"\n" +
	"created_at\x18\r \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\tR\tupdatedAt\"X\n" +
	"\x10QuestionResponse\x12*\n" +
	"\bquestion\x18\x01 \x01(\v2\x0e.prot.QuestionR\bquestion\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"b\n" +
	"\x11QuestionsResponse\x12,\n" +
	"\tquestions\x18\x01 \x03(\v2\x0e.prot.QuestionR\tquestions\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x03R\n" +
	"totalCount\"\xf0\x05\n" +
	"\x1dCreateQuestionRelationRequest\x12\x17\n" +
	"\aexam_id\x18\x01 \x01(\x05R\x06examId\x12\x1f\n" +
	"\vexercise_id\x18\x02 \x01(\x05R\n" +
	"exerciseId\x12-\n" +
	"\x13lesson_plan_part_id\x18\x03 \x01(\x05R\x10lessonPlanPartId\x12\x1f\n" +
	"\vhomework_id\x18\x04 \x01(\x05R\n" +
	"homeworkId\x12\"\n" +
	"\rlevel_test_id\x18\x05 \x01(\x05R\vlevelTestId\x12\x1b\n" +
	"\tlesson_id\x18\x06 \x01(\x05R\blessonId\x12(\n" +
	"\x10contest_round_id\x18\a \x01(\x05R\x0econtestRoundId\x12`\n" +
	"\x0fquestion_scores\x18\b \x03(\v27.prot.CreateQuestionRelationRequest.QuestionScoresEntryR\x0equestionScores\x12s\n" +
	"\x16source_question_scores\x18\t \x03(\v2=.prot.CreateQuestionRelationRequest.SourceQuestionScoresEntryR\x14sourceQuestionScores\x12\x19\n" +
	"\bis_reset\x18\n" +
	" \x01(\bR\aisReset\x12\x1b\n" +
	"\treset_all\x18\v \x01(\bR\bresetAll\x12?\n" +
	"\x1cclear_self_scoring_questions\x18\f \x01(\bR\x19clearSelfScoringQuestions\x1aA\n" +
	"\x13QuestionScoresEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\x1aG\n" +
	"\x19SourceQuestionScoresEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01B\x13Z\x11be-lms/admin/protb\x06proto3"

var (
	file_question_proto_rawDescOnce sync.Once
	file_question_proto_rawDescData []byte
)

func file_question_proto_rawDescGZIP() []byte {
	file_question_proto_rawDescOnce.Do(func() {
		file_question_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_question_proto_rawDesc), len(file_question_proto_rawDesc)))
	})
	return file_question_proto_rawDescData
}

var file_question_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_question_proto_goTypes = []any{
	(*MapPosition)(nil),                   // 0: prot.MapPosition
	(*Matching)(nil),                      // 1: prot.Matching
	(*MediaQuestion)(nil),                 // 2: prot.MediaQuestion
	(*QuestionContent)(nil),               // 3: prot.QuestionContent
	(*QuestionMetaData)(nil),              // 4: prot.QuestionMetaData
	(*QuestionOption)(nil),                // 5: prot.QuestionOption
	(*QuestionCorrectAnswers)(nil),        // 6: prot.QuestionCorrectAnswers
	(*QuestionAttributeValue)(nil),        // 7: prot.QuestionAttributeValue
	(*QuestionAttributeInfo)(nil),         // 8: prot.QuestionAttributeInfo
	(*QuestionSubjectInfo)(nil),           // 9: prot.QuestionSubjectInfo
	(*Question)(nil),                      // 10: prot.Question
	(*QuestionRequest)(nil),               // 11: prot.QuestionRequest
	(*QuestionResponse)(nil),              // 12: prot.QuestionResponse
	(*QuestionsResponse)(nil),             // 13: prot.QuestionsResponse
	(*CreateQuestionRelationRequest)(nil), // 14: prot.CreateQuestionRelationRequest
	nil,                                   // 15: prot.QuestionCorrectAnswers.ListEntry
	nil,                                   // 16: prot.CreateQuestionRelationRequest.QuestionScoresEntry
	nil,                                   // 17: prot.CreateQuestionRelationRequest.SourceQuestionScoresEntry
	(*AnswerContent)(nil),                 // 18: prot.AnswerContent
	(*AnswerSource)(nil),                  // 19: prot.AnswerSource
	(*AnswerTarget)(nil),                  // 20: prot.AnswerTarget
	(*AnswerBlank)(nil),                   // 21: prot.AnswerBlank
	(*GroupAnswer)(nil),                   // 22: prot.GroupAnswer
	(*GroupPosition)(nil),                 // 23: prot.GroupPosition
	(*SourceQuestion)(nil),                // 24: prot.SourceQuestion
}
var file_question_proto_depIdxs = []int32{
	2,  // 0: prot.QuestionContent.media:type_name -> prot.MediaQuestion
	2,  // 1: prot.QuestionContent.medias:type_name -> prot.MediaQuestion
	18, // 2: prot.QuestionOption.answers:type_name -> prot.AnswerContent
	19, // 3: prot.QuestionOption.sources:type_name -> prot.AnswerSource
	20, // 4: prot.QuestionOption.targets:type_name -> prot.AnswerTarget
	18, // 5: prot.QuestionOption.labels:type_name -> prot.AnswerContent
	21, // 6: prot.QuestionOption.blanks:type_name -> prot.AnswerBlank
	18, // 7: prot.QuestionOption.items:type_name -> prot.AnswerContent
	22, // 8: prot.QuestionOption.categories:type_name -> prot.GroupAnswer
	18, // 9: prot.QuestionOption.questions:type_name -> prot.AnswerContent
	23, // 10: prot.QuestionOption.groups:type_name -> prot.GroupPosition
	15, // 11: prot.QuestionCorrectAnswers.list:type_name -> prot.QuestionCorrectAnswers.ListEntry
	7,  // 12: prot.QuestionAttributeInfo.value:type_name -> prot.QuestionAttributeValue
	4,  // 13: prot.Question.metadata:type_name -> prot.QuestionMetaData
	3,  // 14: prot.Question.content:type_name -> prot.QuestionContent
	5,  // 15: prot.Question.options:type_name -> prot.QuestionOption
	24, // 16: prot.Question.source:type_name -> prot.SourceQuestion
	6,  // 17: prot.Question.correct_answers:type_name -> prot.QuestionCorrectAnswers
	8,  // 18: prot.Question.attributes:type_name -> prot.QuestionAttributeInfo
	9,  // 19: prot.Question.subject:type_name -> prot.QuestionSubjectInfo
	4,  // 20: prot.QuestionRequest.metadata:type_name -> prot.QuestionMetaData
	3,  // 21: prot.QuestionRequest.content:type_name -> prot.QuestionContent
	5,  // 22: prot.QuestionRequest.options:type_name -> prot.QuestionOption
	24, // 23: prot.QuestionRequest.source:type_name -> prot.SourceQuestion
	10, // 24: prot.QuestionResponse.question:type_name -> prot.Question
	10, // 25: prot.QuestionsResponse.questions:type_name -> prot.Question
	16, // 26: prot.CreateQuestionRelationRequest.question_scores:type_name -> prot.CreateQuestionRelationRequest.QuestionScoresEntry
	17, // 27: prot.CreateQuestionRelationRequest.source_question_scores:type_name -> prot.CreateQuestionRelationRequest.SourceQuestionScoresEntry
	28, // [28:28] is the sub-list for method output_type
	28, // [28:28] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_question_proto_init() }
func file_question_proto_init() {
	if File_question_proto != nil {
		return
	}
	file_answer_proto_init()
	file_source_question_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_question_proto_rawDesc), len(file_question_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_question_proto_goTypes,
		DependencyIndexes: file_question_proto_depIdxs,
		MessageInfos:      file_question_proto_msgTypes,
	}.Build()
	File_question_proto = out.File
	file_question_proto_goTypes = nil
	file_question_proto_depIdxs = nil
}
