// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: school_dashboard.proto

package prot

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SchoolSummary struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	StudentCount   int64                  `protobuf:"varint,3,opt,name=student_count,json=studentCount,proto3" json:"student_count,omitempty"`
	TeacherCount   int64                  `protobuf:"varint,4,opt,name=teacher_count,json=teacherCount,proto3" json:"teacher_count,omitempty"`
	ClassroomCount int64                  `protobuf:"varint,5,opt,name=classroom_count,json=classroomCount,proto3" json:"classroom_count,omitempty"`
	CourseCount    int64                  `protobuf:"varint,6,opt,name=course_count,json=courseCount,proto3" json:"course_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SchoolSummary) Reset() {
	*x = SchoolSummary{}
	mi := &file_school_dashboard_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchoolSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchoolSummary) ProtoMessage() {}

func (x *SchoolSummary) ProtoReflect() protoreflect.Message {
	mi := &file_school_dashboard_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchoolSummary.ProtoReflect.Descriptor instead.
func (*SchoolSummary) Descriptor() ([]byte, []int) {
	return file_school_dashboard_proto_rawDescGZIP(), []int{0}
}

func (x *SchoolSummary) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SchoolSummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SchoolSummary) GetStudentCount() int64 {
	if x != nil {
		return x.StudentCount
	}
	return 0
}

func (x *SchoolSummary) GetTeacherCount() int64 {
	if x != nil {
		return x.TeacherCount
	}
	return 0
}

func (x *SchoolSummary) GetClassroomCount() int64 {
	if x != nil {
		return x.ClassroomCount
	}
	return 0
}

func (x *SchoolSummary) GetCourseCount() int64 {
	if x != nil {
		return x.CourseCount
	}
	return 0
}

type SchoolSummaryList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*SchoolSummary       `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchoolSummaryList) Reset() {
	*x = SchoolSummaryList{}
	mi := &file_school_dashboard_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchoolSummaryList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchoolSummaryList) ProtoMessage() {}

func (x *SchoolSummaryList) ProtoReflect() protoreflect.Message {
	mi := &file_school_dashboard_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchoolSummaryList.ProtoReflect.Descriptor instead.
func (*SchoolSummaryList) Descriptor() ([]byte, []int) {
	return file_school_dashboard_proto_rawDescGZIP(), []int{1}
}

func (x *SchoolSummaryList) GetItems() []*SchoolSummary {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_school_dashboard_proto protoreflect.FileDescriptor

const file_school_dashboard_proto_rawDesc = "" +
	"\n" +
	"\x16school_dashboard.proto\x12\x04prot\"\xc9\x01\n" +
	"\rSchoolSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12#\n" +
	"\rstudent_count\x18\x03 \x01(\x03R\fstudentCount\x12#\n" +
	"\rteacher_count\x18\x04 \x01(\x03R\fteacherCount\x12'\n" +
	"\x0fclassroom_count\x18\x05 \x01(\x03R\x0eclassroomCount\x12!\n" +
	"\fcourse_count\x18\x06 \x01(\x03R\vcourseCount\">\n" +
	"\x11SchoolSummaryList\x12)\n" +
	"\x05items\x18\x01 \x03(\v2\x13.prot.SchoolSummaryR\x05itemsB\x19Z\x17be-Clever School/be-Clever School/prot;protb\x06proto3"

var (
	file_school_dashboard_proto_rawDescOnce sync.Once
	file_school_dashboard_proto_rawDescData []byte
)

func file_school_dashboard_proto_rawDescGZIP() []byte {
	file_school_dashboard_proto_rawDescOnce.Do(func() {
		file_school_dashboard_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_school_dashboard_proto_rawDesc), len(file_school_dashboard_proto_rawDesc)))
	})
	return file_school_dashboard_proto_rawDescData
}

var file_school_dashboard_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_school_dashboard_proto_goTypes = []any{
	(*SchoolSummary)(nil),     // 0: prot.SchoolSummary
	(*SchoolSummaryList)(nil), // 1: prot.SchoolSummaryList
}
var file_school_dashboard_proto_depIdxs = []int32{
	0, // 0: prot.SchoolSummaryList.items:type_name -> prot.SchoolSummary
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_school_dashboard_proto_init() }
func file_school_dashboard_proto_init() {
	if File_school_dashboard_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_school_dashboard_proto_rawDesc), len(file_school_dashboard_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_school_dashboard_proto_goTypes,
		DependencyIndexes: file_school_dashboard_proto_depIdxs,
		MessageInfos:      file_school_dashboard_proto_msgTypes,
	}.Build()
	File_school_dashboard_proto = out.File
	file_school_dashboard_proto_goTypes = nil
	file_school_dashboard_proto_depIdxs = nil
}
