syntax = "proto3";

package prot;

option go_package = "be-cleverschool/prot";

import "holiday.proto";

message Semester {
  int64 id = 1;
  string name = 2;
  string description = 3;
  string start_date = 4;
  string end_date = 5;
  bool status = 6;
  int32 sort_order = 7;
  int64 previous_semester_id = 8;
  int64 start_week_id = 9;
  int64 end_week_id = 10;
  repeated Holiday holidays = 11;
  string created_at = 12;
  string updated_at = 13;
}

message SemesterInfo {
  int64 id = 1;
  string name = 2;
  string description = 3;
  string start_date = 4;
  string end_date = 5;
}

message GetSemesterRequest {
  int64 id = 1;
}

message SemesterResponse {
  Semester semester = 1;
  string message = 2;
}

message ListSemestersRequest {
  int32 page = 1;
  int32 limit = 2;
  string search = 3;
  string sort_by = 4;
  string sort_order = 5;
}

message SemesterRequest {
  int64 id = 1;
  string name = 2;
  string description = 3;
  string begin_date = 4;
  string start_date = 5;
  string end_date = 6;
  bool status = 7;
  int32 sort_order = 8;
  int64 previous_semester_id = 9;
  int64 start_week_id = 10;
  int64 end_week_id = 11;
  repeated Holiday holidays = 12;
}

message SemesterIDRequest {
  int64 id = 1;
}

message SemestersResponse {
  repeated Semester semesters = 1;
  int64 total_count = 2;
}

