syntax = "proto3";

package prot;

option go_package = "be-lms/prot";

message SettingKVPair {
  string key = 1;
  string value = 2;
}

message Setting {
  int64 id = 1;
  string key = 2;
  string name = 3;
  repeated SettingKVPair values = 4;
  bool is_active = 5;
  int64 created_by = 6;
  int64 updated_by = 7;
  string created_at = 8;
  string updated_at = 9;
}

message SettingRequest {
  int64 id = 1;
  string key = 2;
  string name = 3;
  repeated SettingKVPair values = 4;
  bool is_active = 5;
}

message SettingsResponse {
  repeated Setting settings = 1;
  int64 total_count = 2;
}
