// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: source_question.proto

package prot

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Message for the source question in the source_questions table
type SourceQuestion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`          // ID câu hỏi
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`     // Tiêu đề câu hỏi
	Skill         string                 `protobuf:"bytes,3,opt,name=skill,proto3" json:"skill,omitempty"`     // Kỹ năng (Listening, Reading, etc.)
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"` // Nội dung câu hỏi
	Level         string                 `protobuf:"bytes,5,opt,name=level,proto3" json:"level,omitempty"`     // Độ khó (Easy, Medium, Hard)
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Status        bool                   `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceQuestion) Reset() {
	*x = SourceQuestion{}
	mi := &file_source_question_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceQuestion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceQuestion) ProtoMessage() {}

func (x *SourceQuestion) ProtoReflect() protoreflect.Message {
	mi := &file_source_question_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceQuestion.ProtoReflect.Descriptor instead.
func (*SourceQuestion) Descriptor() ([]byte, []int) {
	return file_source_question_proto_rawDescGZIP(), []int{0}
}

func (x *SourceQuestion) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SourceQuestion) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SourceQuestion) GetSkill() string {
	if x != nil {
		return x.Skill
	}
	return ""
}

func (x *SourceQuestion) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SourceQuestion) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *SourceQuestion) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *SourceQuestion) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *SourceQuestion) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type SourceQuestionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                // ID câu hỏi
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`                           // Tiêu đề câu hỏi
	Skill         string                 `protobuf:"bytes,3,opt,name=skill,proto3" json:"skill,omitempty"`                           // Kỹ năng
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`                       // Nội dung câu hỏi
	Level         string                 `protobuf:"bytes,5,opt,name=level,proto3" json:"level,omitempty"`                           // Độ khó
	UpdatedBy     int64                  `protobuf:"varint,6,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"` // Người cập nhật câu hỏi
	Status        bool                   `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceQuestionRequest) Reset() {
	*x = SourceQuestionRequest{}
	mi := &file_source_question_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceQuestionRequest) ProtoMessage() {}

func (x *SourceQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_source_question_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceQuestionRequest.ProtoReflect.Descriptor instead.
func (*SourceQuestionRequest) Descriptor() ([]byte, []int) {
	return file_source_question_proto_rawDescGZIP(), []int{1}
}

func (x *SourceQuestionRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SourceQuestionRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SourceQuestionRequest) GetSkill() string {
	if x != nil {
		return x.Skill
	}
	return ""
}

func (x *SourceQuestionRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SourceQuestionRequest) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *SourceQuestionRequest) GetUpdatedBy() int64 {
	if x != nil {
		return x.UpdatedBy
	}
	return 0
}

func (x *SourceQuestionRequest) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

// Response for a single source question
type SourceQuestionResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SourceQuestion *SourceQuestion        `protobuf:"bytes,1,opt,name=source_question,json=sourceQuestion,proto3" json:"source_question,omitempty"` // Câu hỏi nguồn
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                                     // Thông báo
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SourceQuestionResponse) Reset() {
	*x = SourceQuestionResponse{}
	mi := &file_source_question_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceQuestionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceQuestionResponse) ProtoMessage() {}

func (x *SourceQuestionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_source_question_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceQuestionResponse.ProtoReflect.Descriptor instead.
func (*SourceQuestionResponse) Descriptor() ([]byte, []int) {
	return file_source_question_proto_rawDescGZIP(), []int{2}
}

func (x *SourceQuestionResponse) GetSourceQuestion() *SourceQuestion {
	if x != nil {
		return x.SourceQuestion
	}
	return nil
}

func (x *SourceQuestionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Response for multiple source questions
type SourceQuestionsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SourceQuestions []*SourceQuestion      `protobuf:"bytes,1,rep,name=source_questions,json=sourceQuestions,proto3" json:"source_questions,omitempty"`
	TotalCount      uint64                 `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SourceQuestionsResponse) Reset() {
	*x = SourceQuestionsResponse{}
	mi := &file_source_question_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceQuestionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceQuestionsResponse) ProtoMessage() {}

func (x *SourceQuestionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_source_question_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceQuestionsResponse.ProtoReflect.Descriptor instead.
func (*SourceQuestionsResponse) Descriptor() ([]byte, []int) {
	return file_source_question_proto_rawDescGZIP(), []int{3}
}

func (x *SourceQuestionsResponse) GetSourceQuestions() []*SourceQuestion {
	if x != nil {
		return x.SourceQuestions
	}
	return nil
}

func (x *SourceQuestionsResponse) GetTotalCount() uint64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

var File_source_question_proto protoreflect.FileDescriptor

const file_source_question_proto_rawDesc = "" +
	"\n" +
	"\x15source_question.proto\x12\x04prot\"\xd2\x01\n" +
	"\x0eSourceQuestion\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x14\n" +
	"\x05skill\x18\x03 \x01(\tR\x05skill\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x14\n" +
	"\x05level\x18\x05 \x01(\tR\x05level\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\x12\x16\n" +
	"\x06status\x18\b \x01(\bR\x06status\"\xba\x01\n" +
	"\x15SourceQuestionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x14\n" +
	"\x05skill\x18\x03 \x01(\tR\x05skill\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x14\n" +
	"\x05level\x18\x05 \x01(\tR\x05level\x12\x1d\n" +
	"\n" +
	"updated_by\x18\x06 \x01(\x03R\tupdatedBy\x12\x16\n" +
	"\x06status\x18\a \x01(\bR\x06status\"q\n" +
	"\x16SourceQuestionResponse\x12=\n" +
	"\x0fsource_question\x18\x01 \x01(\v2\x14.prot.SourceQuestionR\x0esourceQuestion\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"{\n" +
	"\x17SourceQuestionsResponse\x12?\n" +
	"\x10source_questions\x18\x01 \x03(\v2\x14.prot.SourceQuestionR\x0fsourceQuestions\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x04R\n" +
	"totalCountB\x13Z\x11be-lms/admin/protb\x06proto3"

var (
	file_source_question_proto_rawDescOnce sync.Once
	file_source_question_proto_rawDescData []byte
)

func file_source_question_proto_rawDescGZIP() []byte {
	file_source_question_proto_rawDescOnce.Do(func() {
		file_source_question_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_source_question_proto_rawDesc), len(file_source_question_proto_rawDesc)))
	})
	return file_source_question_proto_rawDescData
}

var file_source_question_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_source_question_proto_goTypes = []any{
	(*SourceQuestion)(nil),          // 0: prot.SourceQuestion
	(*SourceQuestionRequest)(nil),   // 1: prot.SourceQuestionRequest
	(*SourceQuestionResponse)(nil),  // 2: prot.SourceQuestionResponse
	(*SourceQuestionsResponse)(nil), // 3: prot.SourceQuestionsResponse
}
var file_source_question_proto_depIdxs = []int32{
	0, // 0: prot.SourceQuestionResponse.source_question:type_name -> prot.SourceQuestion
	0, // 1: prot.SourceQuestionsResponse.source_questions:type_name -> prot.SourceQuestion
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_source_question_proto_init() }
func file_source_question_proto_init() {
	if File_source_question_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_source_question_proto_rawDesc), len(file_source_question_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_source_question_proto_goTypes,
		DependencyIndexes: file_source_question_proto_depIdxs,
		MessageInfos:      file_source_question_proto_msgTypes,
	}.Build()
	File_source_question_proto = out.File
	file_source_question_proto_goTypes = nil
	file_source_question_proto_depIdxs = nil
}
