syntax = "proto3";

package prot;

option go_package = "be-lms/prot";

message Tag {
  int64 id = 1;
  string name = 2;
  string type = 3;
  string description = 4;
  string image_url = 5;
  bool status = 6;
  string created_at = 7;
  string updated_at = 8;
}

message GetTagRequest {
  int64 id = 1;
}

message TagResponse {
  Tag tag = 1;
  string message = 2;
}

message ListTagsRequest {}

message TagRequest {
  int64 id = 1;
  string name = 2;
  string type = 3;
  string description = 4;
  string image_url = 5;
  bool status = 6;
}

message TagIDRequest {
  int64 id = 1;
}

message TagsResponse {
  repeated Tag tags = 1;
  uint64 total_count = 2;
}
