syntax = "proto3";

package prot;

option go_package = "be-Clever School/prot";

message TrainingLevel {
  int64 id = 1;
  string name = 2;
  string description = 3;
  int32 sort_position = 4;
  string created_at = 5;
  string updated_at = 6;
}

message GetTrainingLevelRequest {
  int64 id = 1;
}

message TrainingLevelRequest {
  int64 id = 1;
  string name = 2;
  string description = 3;
  int32 sort_position = 4;
}

message TrainingLevelIDRequest {
  int64 id = 1;
}

message TrainingLevelsResponse {
  repeated TrainingLevel training_levels = 1;
  uint64 total_count = 2;
}
