// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.0
// source: user.proto

package prot

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UsernameExits struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Exits         bool                   `protobuf:"varint,2,opt,name=exits,proto3" json:"exits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsernameExits) Reset() {
	*x = UsernameExits{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsernameExits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsernameExits) ProtoMessage() {}

func (x *UsernameExits) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsernameExits.ProtoReflect.Descriptor instead.
func (*UsernameExits) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

func (x *UsernameExits) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UsernameExits) GetExits() bool {
	if x != nil {
		return x.Exits
	}
	return false
}

type SessionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Ip            string                 `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	UserAgent     string                 `protobuf:"bytes,4,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	Expires       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expires,proto3" json:"expires,omitempty"`
	LoginAt       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=login_at,json=loginAt,proto3" json:"login_at,omitempty"`
	IsCurrent     bool                   `protobuf:"varint,7,opt,name=is_current,json=isCurrent,proto3" json:"is_current,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionInfo) Reset() {
	*x = SessionInfo{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionInfo) ProtoMessage() {}

func (x *SessionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionInfo.ProtoReflect.Descriptor instead.
func (*SessionInfo) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

func (x *SessionInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SessionInfo) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *SessionInfo) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *SessionInfo) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *SessionInfo) GetExpires() *timestamppb.Timestamp {
	if x != nil {
		return x.Expires
	}
	return nil
}

func (x *SessionInfo) GetLoginAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LoginAt
	}
	return nil
}

func (x *SessionInfo) GetIsCurrent() bool {
	if x != nil {
		return x.IsCurrent
	}
	return false
}

type ListSession struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*SessionInfo         `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSession) Reset() {
	*x = ListSession{}
	mi := &file_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSession) ProtoMessage() {}

func (x *ListSession) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSession.ProtoReflect.Descriptor instead.
func (*ListSession) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2}
}

func (x *ListSession) GetSessions() []*SessionInfo {
	if x != nil {
		return x.Sessions
	}
	return nil
}

type UserRole struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRole) Reset() {
	*x = UserRole{}
	mi := &file_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRole) ProtoMessage() {}

func (x *UserRole) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRole.ProtoReflect.Descriptor instead.
func (*UserRole) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{3}
}

func (x *UserRole) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserRole) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type User struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserInfo             *UserInfo              `protobuf:"bytes,2,opt,name=user_info,json=userInfo,proto3" json:"user_info,omitempty"`
	Identifier           string                 `protobuf:"bytes,3,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Username             string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Name                 string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Address              string                 `protobuf:"bytes,6,opt,name=address,proto3" json:"address,omitempty"`
	Email                string                 `protobuf:"bytes,7,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNumber          string                 `protobuf:"bytes,8,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Status               bool                   `protobuf:"varint,9,opt,name=status,proto3" json:"status,omitempty"`
	ParentId             int64                  `protobuf:"varint,10,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	RoleName             string                 `protobuf:"bytes,11,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	Password             string                 `protobuf:"bytes,12,opt,name=password,proto3" json:"password,omitempty"`
	RoleId               int64                  `protobuf:"varint,13,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	Avatar               string                 `protobuf:"bytes,14,opt,name=avatar,proto3" json:"avatar,omitempty"`
	DateOfBirth          string                 `protobuf:"bytes,15,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	Description          string                 `protobuf:"bytes,16,opt,name=description,proto3" json:"description,omitempty"`
	MainTeacher          bool                   `protobuf:"varint,17,opt,name=main_teacher,json=mainTeacher,proto3" json:"main_teacher,omitempty"`
	TypeTeacher          int32                  `protobuf:"varint,18,opt,name=type_teacher,json=typeTeacher,proto3" json:"type_teacher,omitempty"`
	Code                 string                 `protobuf:"bytes,19,opt,name=code,proto3" json:"code,omitempty"`
	CreatedAt            string                 `protobuf:"bytes,20,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string                 `protobuf:"bytes,21,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	MemberType           string                 `protobuf:"bytes,22,opt,name=member_type,json=memberType,proto3" json:"member_type,omitempty"`
	IsIndependentStudent bool                   `protobuf:"varint,23,opt,name=is_independent_student,json=isIndependentStudent,proto3" json:"is_independent_student,omitempty"`
	IsFailedSubject      bool                   `protobuf:"varint,24,opt,name=is_failed_subject,json=isFailedSubject,proto3" json:"is_failed_subject,omitempty"`
	TotalStar            int64                  `protobuf:"varint,25,opt,name=total_star,json=totalStar,proto3" json:"total_star,omitempty"`
	TotalExp             float64                `protobuf:"fixed64,26,opt,name=total_exp,json=totalExp,proto3" json:"total_exp,omitempty"`
	IsFailed             bool                   `protobuf:"varint,27,opt,name=is_failed,json=isFailed,proto3" json:"is_failed,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{4}
}

func (x *User) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetUserInfo() *UserInfo {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

func (x *User) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *User) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *User) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *User) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *User) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *User) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *User) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *User) GetDateOfBirth() string {
	if x != nil {
		return x.DateOfBirth
	}
	return ""
}

func (x *User) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *User) GetMainTeacher() bool {
	if x != nil {
		return x.MainTeacher
	}
	return false
}

func (x *User) GetTypeTeacher() int32 {
	if x != nil {
		return x.TypeTeacher
	}
	return 0
}

func (x *User) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *User) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *User) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *User) GetMemberType() string {
	if x != nil {
		return x.MemberType
	}
	return ""
}

func (x *User) GetIsIndependentStudent() bool {
	if x != nil {
		return x.IsIndependentStudent
	}
	return false
}

func (x *User) GetIsFailedSubject() bool {
	if x != nil {
		return x.IsFailedSubject
	}
	return false
}

func (x *User) GetTotalStar() int64 {
	if x != nil {
		return x.TotalStar
	}
	return 0
}

func (x *User) GetTotalExp() float64 {
	if x != nil {
		return x.TotalExp
	}
	return 0
}

func (x *User) GetIsFailed() bool {
	if x != nil {
		return x.IsFailed
	}
	return false
}

type ClassInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	School        *SchoolInfo            `protobuf:"bytes,3,opt,name=school,proto3" json:"school,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClassInfo) Reset() {
	*x = ClassInfo{}
	mi := &file_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassInfo) ProtoMessage() {}

func (x *ClassInfo) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassInfo.ProtoReflect.Descriptor instead.
func (*ClassInfo) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{5}
}

func (x *ClassInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ClassInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ClassInfo) GetSchool() *SchoolInfo {
	if x != nil {
		return x.School
	}
	return nil
}

type SchoolInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchoolInfo) Reset() {
	*x = SchoolInfo{}
	mi := &file_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchoolInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchoolInfo) ProtoMessage() {}

func (x *SchoolInfo) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchoolInfo.ProtoReflect.Descriptor instead.
func (*SchoolInfo) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{6}
}

func (x *SchoolInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SchoolInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UserProgramInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserProgramInfo) Reset() {
	*x = UserProgramInfo{}
	mi := &file_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProgramInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProgramInfo) ProtoMessage() {}

func (x *UserProgramInfo) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProgramInfo.ProtoReflect.Descriptor instead.
func (*UserProgramInfo) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{7}
}

func (x *UserProgramInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserProgramInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CourseInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ObjectTitle   string                 `protobuf:"bytes,3,opt,name=object_title,json=objectTitle,proto3" json:"object_title,omitempty"`
	Program       *UserProgramInfo       `protobuf:"bytes,4,opt,name=program,proto3" json:"program,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CourseInfo) Reset() {
	*x = CourseInfo{}
	mi := &file_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CourseInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourseInfo) ProtoMessage() {}

func (x *CourseInfo) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourseInfo.ProtoReflect.Descriptor instead.
func (*CourseInfo) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{8}
}

func (x *CourseInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CourseInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CourseInfo) GetObjectTitle() string {
	if x != nil {
		return x.ObjectTitle
	}
	return ""
}

func (x *CourseInfo) GetProgram() *UserProgramInfo {
	if x != nil {
		return x.Program
	}
	return nil
}

type SubjectInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubjectInfo) Reset() {
	*x = SubjectInfo{}
	mi := &file_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubjectInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubjectInfo) ProtoMessage() {}

func (x *SubjectInfo) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubjectInfo.ProtoReflect.Descriptor instead.
func (*SubjectInfo) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{9}
}

func (x *SubjectInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SubjectInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type FacultyInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FacultyInfo) Reset() {
	*x = FacultyInfo{}
	mi := &file_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FacultyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FacultyInfo) ProtoMessage() {}

func (x *FacultyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FacultyInfo.ProtoReflect.Descriptor instead.
func (*FacultyInfo) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{10}
}

func (x *FacultyInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FacultyInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type AddressInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProvinceCode  string                 `protobuf:"bytes,2,opt,name=province_code,json=provinceCode,proto3" json:"province_code,omitempty"`
	WardCode      string                 `protobuf:"bytes,3,opt,name=ward_code,json=wardCode,proto3" json:"ward_code,omitempty"`
	ProvinceName  string                 `protobuf:"bytes,4,opt,name=province_name,json=provinceName,proto3" json:"province_name,omitempty"`
	WardName      string                 `protobuf:"bytes,5,opt,name=ward_name,json=wardName,proto3" json:"ward_name,omitempty"`
	Address       string                 `protobuf:"bytes,6,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddressInfo) Reset() {
	*x = AddressInfo{}
	mi := &file_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddressInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressInfo) ProtoMessage() {}

func (x *AddressInfo) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressInfo.ProtoReflect.Descriptor instead.
func (*AddressInfo) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{11}
}

func (x *AddressInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AddressInfo) GetProvinceCode() string {
	if x != nil {
		return x.ProvinceCode
	}
	return ""
}

func (x *AddressInfo) GetWardCode() string {
	if x != nil {
		return x.WardCode
	}
	return ""
}

func (x *AddressInfo) GetProvinceName() string {
	if x != nil {
		return x.ProvinceName
	}
	return ""
}

func (x *AddressInfo) GetWardName() string {
	if x != nil {
		return x.WardName
	}
	return ""
}

func (x *AddressInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	School        *SchoolInfo            `protobuf:"bytes,1,opt,name=school,proto3" json:"school,omitempty"`
	Class         *ClassInfo             `protobuf:"bytes,2,opt,name=class,proto3" json:"class,omitempty"`
	Courses       []*CourseInfo          `protobuf:"bytes,3,rep,name=courses,proto3" json:"courses,omitempty"`
	Address       *AddressInfo           `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	Role          *UserRole              `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	Certificates  []*Certificate         `protobuf:"bytes,6,rep,name=certificates,proto3" json:"certificates,omitempty"`
	Degrees       []*Degree              `protobuf:"bytes,7,rep,name=degrees,proto3" json:"degrees,omitempty"`
	Departments   []*Department          `protobuf:"bytes,8,rep,name=departments,proto3" json:"departments,omitempty"`
	Positions     []*EmployeePosition    `protobuf:"bytes,9,rep,name=positions,proto3" json:"positions,omitempty"`
	Subjects      []*SubjectInfo         `protobuf:"bytes,10,rep,name=subjects,proto3" json:"subjects,omitempty"`
	Roles         []*UserRole            `protobuf:"bytes,11,rep,name=roles,proto3" json:"roles,omitempty"`
	Faculty       *FacultyInfo           `protobuf:"bytes,12,opt,name=faculty,proto3" json:"faculty,omitempty"`
	Schools       []*SchoolInfo          `protobuf:"bytes,13,rep,name=schools,proto3" json:"schools,omitempty"`
	Classes       []*ClassInfo           `protobuf:"bytes,14,rep,name=classes,proto3" json:"classes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{12}
}

func (x *UserInfo) GetSchool() *SchoolInfo {
	if x != nil {
		return x.School
	}
	return nil
}

func (x *UserInfo) GetClass() *ClassInfo {
	if x != nil {
		return x.Class
	}
	return nil
}

func (x *UserInfo) GetCourses() []*CourseInfo {
	if x != nil {
		return x.Courses
	}
	return nil
}

func (x *UserInfo) GetAddress() *AddressInfo {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *UserInfo) GetRole() *UserRole {
	if x != nil {
		return x.Role
	}
	return nil
}

func (x *UserInfo) GetCertificates() []*Certificate {
	if x != nil {
		return x.Certificates
	}
	return nil
}

func (x *UserInfo) GetDegrees() []*Degree {
	if x != nil {
		return x.Degrees
	}
	return nil
}

func (x *UserInfo) GetDepartments() []*Department {
	if x != nil {
		return x.Departments
	}
	return nil
}

func (x *UserInfo) GetPositions() []*EmployeePosition {
	if x != nil {
		return x.Positions
	}
	return nil
}

func (x *UserInfo) GetSubjects() []*SubjectInfo {
	if x != nil {
		return x.Subjects
	}
	return nil
}

func (x *UserInfo) GetRoles() []*UserRole {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *UserInfo) GetFaculty() *FacultyInfo {
	if x != nil {
		return x.Faculty
	}
	return nil
}

func (x *UserInfo) GetSchools() []*SchoolInfo {
	if x != nil {
		return x.Schools
	}
	return nil
}

func (x *UserInfo) GetClasses() []*ClassInfo {
	if x != nil {
		return x.Classes
	}
	return nil
}

type ListUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUser) Reset() {
	*x = ListUser{}
	mi := &file_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUser) ProtoMessage() {}

func (x *ListUser) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUser.ProtoReflect.Descriptor instead.
func (*ListUser) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{13}
}

func (x *ListUser) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

type UserIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserIDRequest) Reset() {
	*x = UserIDRequest{}
	mi := &file_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserIDRequest) ProtoMessage() {}

func (x *UserIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserIDRequest.ProtoReflect.Descriptor instead.
func (*UserIDRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{14}
}

func (x *UserIDRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserResponse) Reset() {
	*x = UserResponse{}
	mi := &file_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResponse) ProtoMessage() {}

func (x *UserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResponse.ProtoReflect.Descriptor instead.
func (*UserResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{15}
}

func (x *UserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *UserResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	TotalCount    int64                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsersResponse) Reset() {
	*x = UsersResponse{}
	mi := &file_user_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsersResponse) ProtoMessage() {}

func (x *UsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsersResponse.ProtoReflect.Descriptor instead.
func (*UsersResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{16}
}

func (x *UsersResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *UsersResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type UserLoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	RoleId        int32                  `protobuf:"varint,2,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	RoleName      string                 `protobuf:"bytes,3,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	RoleIds       []int32                `protobuf:"varint,5,rep,packed,name=role_ids,json=roleIds,proto3" json:"role_ids,omitempty"`
	RoleNames     []string               `protobuf:"bytes,6,rep,name=role_names,json=roleNames,proto3" json:"role_names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserLoginResponse) Reset() {
	*x = UserLoginResponse{}
	mi := &file_user_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLoginResponse) ProtoMessage() {}

func (x *UserLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLoginResponse.ProtoReflect.Descriptor instead.
func (*UserLoginResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{17}
}

func (x *UserLoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *UserLoginResponse) GetRoleId() int32 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *UserLoginResponse) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *UserLoginResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *UserLoginResponse) GetRoleIds() []int32 {
	if x != nil {
		return x.RoleIds
	}
	return nil
}

func (x *UserLoginResponse) GetRoleNames() []string {
	if x != nil {
		return x.RoleNames
	}
	return nil
}

type EmptyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyResponse) Reset() {
	*x = EmptyResponse{}
	mi := &file_user_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyResponse) ProtoMessage() {}

func (x *EmptyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyResponse.ProtoReflect.Descriptor instead.
func (*EmptyResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{18}
}

type ChangePasswordRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OldPassword     string                 `protobuf:"bytes,1,opt,name=old_password,json=oldPassword,proto3" json:"old_password,omitempty"`
	NewPassword     string                 `protobuf:"bytes,2,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	ConfirmPassword string                 `protobuf:"bytes,3,opt,name=confirm_password,json=confirmPassword,proto3" json:"confirm_password,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ChangePasswordRequest) Reset() {
	*x = ChangePasswordRequest{}
	mi := &file_user_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordRequest) ProtoMessage() {}

func (x *ChangePasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePasswordRequest.ProtoReflect.Descriptor instead.
func (*ChangePasswordRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{19}
}

func (x *ChangePasswordRequest) GetOldPassword() string {
	if x != nil {
		return x.OldPassword
	}
	return ""
}

func (x *ChangePasswordRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

func (x *ChangePasswordRequest) GetConfirmPassword() string {
	if x != nil {
		return x.ConfirmPassword
	}
	return ""
}

type UserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	MainTeacher   bool                   `protobuf:"varint,4,opt,name=main_teacher,json=mainTeacher,proto3" json:"main_teacher,omitempty"`
	TypeTeacher   int32                  `protobuf:"varint,5,opt,name=type_teacher,json=typeTeacher,proto3" json:"type_teacher,omitempty"`
	IsFailed      bool                   `protobuf:"varint,6,opt,name=is_failed,json=isFailed,proto3" json:"is_failed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRequest) Reset() {
	*x = UserRequest{}
	mi := &file_user_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRequest) ProtoMessage() {}

func (x *UserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRequest.ProtoReflect.Descriptor instead.
func (*UserRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{20}
}

func (x *UserRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserRequest) GetMainTeacher() bool {
	if x != nil {
		return x.MainTeacher
	}
	return false
}

func (x *UserRequest) GetTypeTeacher() int32 {
	if x != nil {
		return x.TypeTeacher
	}
	return 0
}

func (x *UserRequest) GetIsFailed() bool {
	if x != nil {
		return x.IsFailed
	}
	return false
}

type UserCourseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserRequest         `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	RoleId        int32                  `protobuf:"varint,2,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserCourseRequest) Reset() {
	*x = UserCourseRequest{}
	mi := &file_user_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCourseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCourseRequest) ProtoMessage() {}

func (x *UserCourseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCourseRequest.ProtoReflect.Descriptor instead.
func (*UserCourseRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{21}
}

func (x *UserCourseRequest) GetUsers() []*UserRequest {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *UserCourseRequest) GetRoleId() int32 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

type UserClassRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserRequest         `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	RoleId        int32                  `protobuf:"varint,2,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserClassRequest) Reset() {
	*x = UserClassRequest{}
	mi := &file_user_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserClassRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserClassRequest) ProtoMessage() {}

func (x *UserClassRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserClassRequest.ProtoReflect.Descriptor instead.
func (*UserClassRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{22}
}

func (x *UserClassRequest) GetUsers() []*UserRequest {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *UserClassRequest) GetRoleId() int32 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

// Forgot Password Messages
type ForgotPasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForgotPasswordRequest) Reset() {
	*x = ForgotPasswordRequest{}
	mi := &file_user_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForgotPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForgotPasswordRequest) ProtoMessage() {}

func (x *ForgotPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForgotPasswordRequest.ProtoReflect.Descriptor instead.
func (*ForgotPasswordRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{23}
}

func (x *ForgotPasswordRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type ForgotPasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForgotPasswordResponse) Reset() {
	*x = ForgotPasswordResponse{}
	mi := &file_user_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForgotPasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForgotPasswordResponse) ProtoMessage() {}

func (x *ForgotPasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForgotPasswordResponse.ProtoReflect.Descriptor instead.
func (*ForgotPasswordResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{24}
}

func (x *ForgotPasswordResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ForgotPasswordResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ResetPasswordRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Token           string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	NewPassword     string                 `protobuf:"bytes,2,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	ConfirmPassword string                 `protobuf:"bytes,3,opt,name=confirm_password,json=confirmPassword,proto3" json:"confirm_password,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ResetPasswordRequest) Reset() {
	*x = ResetPasswordRequest{}
	mi := &file_user_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPasswordRequest) ProtoMessage() {}

func (x *ResetPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPasswordRequest.ProtoReflect.Descriptor instead.
func (*ResetPasswordRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{25}
}

func (x *ResetPasswordRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ResetPasswordRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

func (x *ResetPasswordRequest) GetConfirmPassword() string {
	if x != nil {
		return x.ConfirmPassword
	}
	return ""
}

type ResetPasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetPasswordResponse) Reset() {
	*x = ResetPasswordResponse{}
	mi := &file_user_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPasswordResponse) ProtoMessage() {}

func (x *ResetPasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPasswordResponse.ProtoReflect.Descriptor instead.
func (*ResetPasswordResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{26}
}

func (x *ResetPasswordResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ResetPasswordResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FullName      string                 `protobuf:"bytes,1,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,3,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	RoleId        int32                  `protobuf:"varint,4,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	MemberType    string                 `protobuf:"bytes,5,opt,name=member_type,json=memberType,proto3" json:"member_type,omitempty"`
	Password      string                 `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	Username      string                 `protobuf:"bytes,7,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_user_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{27}
}

func (x *RegisterRequest) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *RegisterRequest) GetRoleId() int32 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *RegisterRequest) GetMemberType() string {
	if x != nil {
		return x.MemberType
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type LogoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutResponse) Reset() {
	*x = LogoutResponse{}
	mi := &file_user_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutResponse) ProtoMessage() {}

func (x *LogoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutResponse.ProtoReflect.Descriptor instead.
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{28}
}

func (x *LogoutResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LogoutResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\x12\x04prot\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x11certificate.proto\x1a\fdegree.proto\x1a\x10department.proto\x1a\x17employee_position.proto\"A\n" +
	"\rUsernameExits\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05exits\x18\x02 \x01(\bR\x05exits\"\xee\x01\n" +
	"\vSessionInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x0e\n" +
	"\x02ip\x18\x03 \x01(\tR\x02ip\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x04 \x01(\tR\tuserAgent\x124\n" +
	"\aexpires\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\aexpires\x125\n" +
	"\blogin_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\aloginAt\x12\x1d\n" +
	"\n" +
	"is_current\x18\a \x01(\bR\tisCurrent\"<\n" +
	"\vListSession\x12-\n" +
	"\bsessions\x18\x01 \x03(\v2\x11.prot.SessionInfoR\bsessions\".\n" +
	"\bUserRole\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xbf\x06\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12+\n" +
	"\tuser_info\x18\x02 \x01(\v2\x0e.prot.UserInfoR\buserInfo\x12\x1e\n" +
	"\n" +
	"identifier\x18\x03 \x01(\tR\n" +
	"identifier\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x06 \x01(\tR\aaddress\x12\x14\n" +
	"\x05email\x18\a \x01(\tR\x05email\x12!\n" +
	"\fphone_number\x18\b \x01(\tR\vphoneNumber\x12\x16\n" +
	"\x06status\x18\t \x01(\bR\x06status\x12\x1b\n" +
	"\tparent_id\x18\n" +
	" \x01(\x03R\bparentId\x12\x1b\n" +
	"\trole_name\x18\v \x01(\tR\broleName\x12\x1a\n" +
	"\bpassword\x18\f \x01(\tR\bpassword\x12\x17\n" +
	"\arole_id\x18\r \x01(\x03R\x06roleId\x12\x16\n" +
	"\x06avatar\x18\x0e \x01(\tR\x06avatar\x12\"\n" +
	"\rdate_of_birth\x18\x0f \x01(\tR\vdateOfBirth\x12 \n" +
	"\vdescription\x18\x10 \x01(\tR\vdescription\x12!\n" +
	"\fmain_teacher\x18\x11 \x01(\bR\vmainTeacher\x12!\n" +
	"\ftype_teacher\x18\x12 \x01(\x05R\vtypeTeacher\x12\x12\n" +
	"\x04code\x18\x13 \x01(\tR\x04code\x12\x1d\n" +
	"\n" +
	"created_at\x18\x14 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x15 \x01(\tR\tupdatedAt\x12\x1f\n" +
	"\vmember_type\x18\x16 \x01(\tR\n" +
	"memberType\x124\n" +
	"\x16is_independent_student\x18\x17 \x01(\bR\x14isIndependentStudent\x12*\n" +
	"\x11is_failed_subject\x18\x18 \x01(\bR\x0fisFailedSubject\x12\x1d\n" +
	"\n" +
	"total_star\x18\x19 \x01(\x03R\ttotalStar\x12\x1b\n" +
	"\ttotal_exp\x18\x1a \x01(\x01R\btotalExp\x12\x1b\n" +
	"\tis_failed\x18\x1b \x01(\bR\bisFailed\"Y\n" +
	"\tClassInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12(\n" +
	"\x06school\x18\x03 \x01(\v2\x10.prot.SchoolInfoR\x06school\"0\n" +
	"\n" +
	"SchoolInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"5\n" +
	"\x0fUserProgramInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x84\x01\n" +
	"\n" +
	"CourseInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\fobject_title\x18\x03 \x01(\tR\vobjectTitle\x12/\n" +
	"\aprogram\x18\x04 \x01(\v2\x15.prot.UserProgramInfoR\aprogram\"1\n" +
	"\vSubjectInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"1\n" +
	"\vFacultyInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xbb\x01\n" +
	"\vAddressInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12#\n" +
	"\rprovince_code\x18\x02 \x01(\tR\fprovinceCode\x12\x1b\n" +
	"\tward_code\x18\x03 \x01(\tR\bwardCode\x12#\n" +
	"\rprovince_name\x18\x04 \x01(\tR\fprovinceName\x12\x1b\n" +
	"\tward_name\x18\x05 \x01(\tR\bwardName\x12\x18\n" +
	"\aaddress\x18\x06 \x01(\tR\aaddress\"\xfa\x04\n" +
	"\bUserInfo\x12(\n" +
	"\x06school\x18\x01 \x01(\v2\x10.prot.SchoolInfoR\x06school\x12%\n" +
	"\x05class\x18\x02 \x01(\v2\x0f.prot.ClassInfoR\x05class\x12*\n" +
	"\acourses\x18\x03 \x03(\v2\x10.prot.CourseInfoR\acourses\x12+\n" +
	"\aaddress\x18\x04 \x01(\v2\x11.prot.AddressInfoR\aaddress\x12\"\n" +
	"\x04role\x18\x05 \x01(\v2\x0e.prot.UserRoleR\x04role\x125\n" +
	"\fcertificates\x18\x06 \x03(\v2\x11.prot.CertificateR\fcertificates\x12&\n" +
	"\adegrees\x18\a \x03(\v2\f.prot.DegreeR\adegrees\x122\n" +
	"\vdepartments\x18\b \x03(\v2\x10.prot.DepartmentR\vdepartments\x124\n" +
	"\tpositions\x18\t \x03(\v2\x16.prot.EmployeePositionR\tpositions\x12-\n" +
	"\bsubjects\x18\n" +
	" \x03(\v2\x11.prot.SubjectInfoR\bsubjects\x12$\n" +
	"\x05roles\x18\v \x03(\v2\x0e.prot.UserRoleR\x05roles\x12+\n" +
	"\afaculty\x18\f \x01(\v2\x11.prot.FacultyInfoR\afaculty\x12*\n" +
	"\aschools\x18\r \x03(\v2\x10.prot.SchoolInfoR\aschools\x12)\n" +
	"\aclasses\x18\x0e \x03(\v2\x0f.prot.ClassInfoR\aclasses\",\n" +
	"\bListUser\x12 \n" +
	"\x05users\x18\x01 \x03(\v2\n" +
	".prot.UserR\x05users\"\x1f\n" +
	"\rUserIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"H\n" +
	"\fUserResponse\x12\x1e\n" +
	"\x04user\x18\x01 \x01(\v2\n" +
	".prot.UserR\x04user\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"R\n" +
	"\rUsersResponse\x12 \n" +
	"\x05users\x18\x01 \x03(\v2\n" +
	".prot.UserR\x05users\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x03R\n" +
	"totalCount\"\xad\x01\n" +
	"\x11UserLoginResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x17\n" +
	"\arole_id\x18\x02 \x01(\x05R\x06roleId\x12\x1b\n" +
	"\trole_name\x18\x03 \x01(\tR\broleName\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x19\n" +
	"\brole_ids\x18\x05 \x03(\x05R\aroleIds\x12\x1d\n" +
	"\n" +
	"role_names\x18\x06 \x03(\tR\troleNames\"\x0f\n" +
	"\rEmptyResponse\"\x88\x01\n" +
	"\x15ChangePasswordRequest\x12!\n" +
	"\fold_password\x18\x01 \x01(\tR\voldPassword\x12!\n" +
	"\fnew_password\x18\x02 \x01(\tR\vnewPassword\x12)\n" +
	"\x10confirm_password\x18\x03 \x01(\tR\x0fconfirmPassword\"\xb0\x01\n" +
	"\vUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12!\n" +
	"\fmain_teacher\x18\x04 \x01(\bR\vmainTeacher\x12!\n" +
	"\ftype_teacher\x18\x05 \x01(\x05R\vtypeTeacher\x12\x1b\n" +
	"\tis_failed\x18\x06 \x01(\bR\bisFailed\"U\n" +
	"\x11UserCourseRequest\x12'\n" +
	"\x05users\x18\x01 \x03(\v2\x11.prot.UserRequestR\x05users\x12\x17\n" +
	"\arole_id\x18\x02 \x01(\x05R\x06roleId\"T\n" +
	"\x10UserClassRequest\x12'\n" +
	"\x05users\x18\x01 \x03(\v2\x11.prot.UserRequestR\x05users\x12\x17\n" +
	"\arole_id\x18\x02 \x01(\x05R\x06roleId\"3\n" +
	"\x15ForgotPasswordRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"L\n" +
	"\x16ForgotPasswordResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"z\n" +
	"\x14ResetPasswordRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12!\n" +
	"\fnew_password\x18\x02 \x01(\tR\vnewPassword\x12)\n" +
	"\x10confirm_password\x18\x03 \x01(\tR\x0fconfirmPassword\"K\n" +
	"\x15ResetPasswordResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xd9\x01\n" +
	"\x0fRegisterRequest\x12\x1b\n" +
	"\tfull_name\x18\x01 \x01(\tR\bfullName\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12!\n" +
	"\fphone_number\x18\x03 \x01(\tR\vphoneNumber\x12\x17\n" +
	"\arole_id\x18\x04 \x01(\x05R\x06roleId\x12\x1f\n" +
	"\vmember_type\x18\x05 \x01(\tR\n" +
	"memberType\x12\x1a\n" +
	"\bpassword\x18\x06 \x01(\tR\bpassword\x12\x1a\n" +
	"\busername\x18\a \x01(\tR\busername\"D\n" +
	"\x0eLogoutResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessageB\rZ\vbe-cleverschool/protb\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_user_proto_goTypes = []any{
	(*UsernameExits)(nil),          // 0: prot.UsernameExits
	(*SessionInfo)(nil),            // 1: prot.SessionInfo
	(*ListSession)(nil),            // 2: prot.ListSession
	(*UserRole)(nil),               // 3: prot.UserRole
	(*User)(nil),                   // 4: prot.User
	(*ClassInfo)(nil),              // 5: prot.ClassInfo
	(*SchoolInfo)(nil),             // 6: prot.SchoolInfo
	(*UserProgramInfo)(nil),        // 7: prot.UserProgramInfo
	(*CourseInfo)(nil),             // 8: prot.CourseInfo
	(*SubjectInfo)(nil),            // 9: prot.SubjectInfo
	(*FacultyInfo)(nil),            // 10: prot.FacultyInfo
	(*AddressInfo)(nil),            // 11: prot.AddressInfo
	(*UserInfo)(nil),               // 12: prot.UserInfo
	(*ListUser)(nil),               // 13: prot.ListUser
	(*UserIDRequest)(nil),          // 14: prot.UserIDRequest
	(*UserResponse)(nil),           // 15: prot.UserResponse
	(*UsersResponse)(nil),          // 16: prot.UsersResponse
	(*UserLoginResponse)(nil),      // 17: prot.UserLoginResponse
	(*EmptyResponse)(nil),          // 18: prot.EmptyResponse
	(*ChangePasswordRequest)(nil),  // 19: prot.ChangePasswordRequest
	(*UserRequest)(nil),            // 20: prot.UserRequest
	(*UserCourseRequest)(nil),      // 21: prot.UserCourseRequest
	(*UserClassRequest)(nil),       // 22: prot.UserClassRequest
	(*ForgotPasswordRequest)(nil),  // 23: prot.ForgotPasswordRequest
	(*ForgotPasswordResponse)(nil), // 24: prot.ForgotPasswordResponse
	(*ResetPasswordRequest)(nil),   // 25: prot.ResetPasswordRequest
	(*ResetPasswordResponse)(nil),  // 26: prot.ResetPasswordResponse
	(*RegisterRequest)(nil),        // 27: prot.RegisterRequest
	(*LogoutResponse)(nil),         // 28: prot.LogoutResponse
	(*timestamppb.Timestamp)(nil),  // 29: google.protobuf.Timestamp
	(*Certificate)(nil),            // 30: prot.Certificate
	(*Degree)(nil),                 // 31: prot.Degree
	(*Department)(nil),             // 32: prot.Department
	(*EmployeePosition)(nil),       // 33: prot.EmployeePosition
}
var file_user_proto_depIdxs = []int32{
	29, // 0: prot.SessionInfo.expires:type_name -> google.protobuf.Timestamp
	29, // 1: prot.SessionInfo.login_at:type_name -> google.protobuf.Timestamp
	1,  // 2: prot.ListSession.sessions:type_name -> prot.SessionInfo
	12, // 3: prot.User.user_info:type_name -> prot.UserInfo
	6,  // 4: prot.ClassInfo.school:type_name -> prot.SchoolInfo
	7,  // 5: prot.CourseInfo.program:type_name -> prot.UserProgramInfo
	6,  // 6: prot.UserInfo.school:type_name -> prot.SchoolInfo
	5,  // 7: prot.UserInfo.class:type_name -> prot.ClassInfo
	8,  // 8: prot.UserInfo.courses:type_name -> prot.CourseInfo
	11, // 9: prot.UserInfo.address:type_name -> prot.AddressInfo
	3,  // 10: prot.UserInfo.role:type_name -> prot.UserRole
	30, // 11: prot.UserInfo.certificates:type_name -> prot.Certificate
	31, // 12: prot.UserInfo.degrees:type_name -> prot.Degree
	32, // 13: prot.UserInfo.departments:type_name -> prot.Department
	33, // 14: prot.UserInfo.positions:type_name -> prot.EmployeePosition
	9,  // 15: prot.UserInfo.subjects:type_name -> prot.SubjectInfo
	3,  // 16: prot.UserInfo.roles:type_name -> prot.UserRole
	10, // 17: prot.UserInfo.faculty:type_name -> prot.FacultyInfo
	6,  // 18: prot.UserInfo.schools:type_name -> prot.SchoolInfo
	5,  // 19: prot.UserInfo.classes:type_name -> prot.ClassInfo
	4,  // 20: prot.ListUser.users:type_name -> prot.User
	4,  // 21: prot.UserResponse.user:type_name -> prot.User
	4,  // 22: prot.UsersResponse.users:type_name -> prot.User
	20, // 23: prot.UserCourseRequest.users:type_name -> prot.UserRequest
	20, // 24: prot.UserClassRequest.users:type_name -> prot.UserRequest
	25, // [25:25] is the sub-list for method output_type
	25, // [25:25] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	file_certificate_proto_init()
	file_degree_proto_init()
	file_department_proto_init()
	file_employee_position_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}

