// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: week.proto

package prot

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Week struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Year          int32                  `protobuf:"varint,2,opt,name=year,proto3" json:"year,omitempty"`
	WeekNumber    int32                  `protobuf:"varint,3,opt,name=week_number,json=weekNumber,proto3" json:"week_number,omitempty"`
	StartDate     string                 `protobuf:"bytes,4,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,5,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Number        int32                  `protobuf:"varint,8,opt,name=number,proto3" json:"number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Week) Reset() {
	*x = Week{}
	mi := &file_week_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Week) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Week) ProtoMessage() {}

func (x *Week) ProtoReflect() protoreflect.Message {
	mi := &file_week_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Week.ProtoReflect.Descriptor instead.
func (*Week) Descriptor() ([]byte, []int) {
	return file_week_proto_rawDescGZIP(), []int{0}
}

func (x *Week) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Week) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *Week) GetWeekNumber() int32 {
	if x != nil {
		return x.WeekNumber
	}
	return 0
}

func (x *Week) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *Week) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *Week) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Week) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Week) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

type WeekInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Year          int32                  `protobuf:"varint,2,opt,name=year,proto3" json:"year,omitempty"`
	WeekNumber    int32                  `protobuf:"varint,3,opt,name=week_number,json=weekNumber,proto3" json:"week_number,omitempty"`
	StartDate     string                 `protobuf:"bytes,4,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,5,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WeekInfo) Reset() {
	*x = WeekInfo{}
	mi := &file_week_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeekInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeekInfo) ProtoMessage() {}

func (x *WeekInfo) ProtoReflect() protoreflect.Message {
	mi := &file_week_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeekInfo.ProtoReflect.Descriptor instead.
func (*WeekInfo) Descriptor() ([]byte, []int) {
	return file_week_proto_rawDescGZIP(), []int{1}
}

func (x *WeekInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *WeekInfo) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *WeekInfo) GetWeekNumber() int32 {
	if x != nil {
		return x.WeekNumber
	}
	return 0
}

func (x *WeekInfo) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *WeekInfo) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

type WeeksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Weeks         []*Week                `protobuf:"bytes,1,rep,name=weeks,proto3" json:"weeks,omitempty"`
	TotalCount    uint64                 `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WeeksResponse) Reset() {
	*x = WeeksResponse{}
	mi := &file_week_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeeksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeeksResponse) ProtoMessage() {}

func (x *WeeksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_week_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeeksResponse.ProtoReflect.Descriptor instead.
func (*WeeksResponse) Descriptor() ([]byte, []int) {
	return file_week_proto_rawDescGZIP(), []int{2}
}

func (x *WeeksResponse) GetWeeks() []*Week {
	if x != nil {
		return x.Weeks
	}
	return nil
}

func (x *WeeksResponse) GetTotalCount() uint64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

var File_week_proto protoreflect.FileDescriptor

const file_week_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"week.proto\x12\x04prot\"\xdb\x01\n" +
	"\x04Week\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04year\x18\x02 \x01(\x05R\x04year\x12\x1f\n" +
	"\vweek_number\x18\x03 \x01(\x05R\n" +
	"weekNumber\x12\x1d\n" +
	"\n" +
	"start_date\x18\x04 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x05 \x01(\tR\aendDate\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\x12\x16\n" +
	"\x06number\x18\b \x01(\x05R\x06number\"\x89\x01\n" +
	"\bWeekInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04year\x18\x02 \x01(\x05R\x04year\x12\x1f\n" +
	"\vweek_number\x18\x03 \x01(\x05R\n" +
	"weekNumber\x12\x1d\n" +
	"\n" +
	"start_date\x18\x04 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x05 \x01(\tR\aendDate\"R\n" +
	"\rWeeksResponse\x12 \n" +
	"\x05weeks\x18\x01 \x03(\v2\n" +
	".prot.WeekR\x05weeks\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x04R\n" +
	"totalCountB\rZ\vbe-lms/protb\x06proto3"

var (
	file_week_proto_rawDescOnce sync.Once
	file_week_proto_rawDescData []byte
)

func file_week_proto_rawDescGZIP() []byte {
	file_week_proto_rawDescOnce.Do(func() {
		file_week_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_week_proto_rawDesc), len(file_week_proto_rawDesc)))
	})
	return file_week_proto_rawDescData
}

var file_week_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_week_proto_goTypes = []any{
	(*Week)(nil),          // 0: prot.Week
	(*WeekInfo)(nil),      // 1: prot.WeekInfo
	(*WeeksResponse)(nil), // 2: prot.WeeksResponse
}
var file_week_proto_depIdxs = []int32{
	0, // 0: prot.WeeksResponse.weeks:type_name -> prot.Week
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_week_proto_init() }
func file_week_proto_init() {
	if File_week_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_week_proto_rawDesc), len(file_week_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_week_proto_goTypes,
		DependencyIndexes: file_week_proto_depIdxs,
		MessageInfos:      file_week_proto_msgTypes,
	}.Build()
	File_week_proto = out.File
	file_week_proto_goTypes = nil
	file_week_proto_depIdxs = nil
}
