package resources

import (
	"be-cleverschool/models"
	"be-cleverschool/prot"
)

type NoticeResource interface {
	FormatNotice(notice *models.Notice) *prot.Notice
	FormatNotices(notices []*models.Notice) []*prot.Notice
	FormatModelNotice(notice *prot.Notice) *models.Notice
}

type NoticeResourceImpl struct{}

func NewNoticeResource() NoticeResource {
	return &NoticeResourceImpl{}
}

func (r *NoticeResourceImpl) FormatNotice(notice *models.Notice) *prot.Notice {
	if notice == nil {
		return nil
	}

	var cover, description, content string
	if notice.Cover != nil {
		cover = *notice.Cover
	}
	if notice.Description != nil {
		description = *notice.Description
	}
	if notice.Content != nil {
		content = *notice.Content
	}

	var createdBy, updatedBy int64
	if notice.CreatedBy != nil {
		createdBy = *notice.CreatedBy
	}
	if notice.UpdatedBy != nil {
		updatedBy = *notice.UpdatedBy
	}

	var logs []*prot.NotificationLog
	for _, l := range notice.NotificationLogs {
		logs = append(logs, &prot.NotificationLog{
			Id:       l.ID,
			NoticeId: l.NoticeID,
			Status:   l.Status,
			Data: &prot.NotificationData{
				Value:        l.Data.DataValue,
				Type:         l.Data.Type,
				SuccessCount: l.Data.SuccessCount,
				FailedCount:  l.Data.FailedCount,
				Error:        l.Data.Error,
			},
			CreatedAt: l.CreatedAt.Format("2006-01-02 15:04:05"),
			SentAt:    l.SentAt.Format("2006-01-02 15:04:05"),
		})
	}

	return &prot.Notice{
		Id:          notice.ID,
		Cover:       cover,
		Title:       notice.Title,
		Description: description,
		Content:     content,
		CreatedAt:   notice.CreatedAt.Format("2006-01-02 15:04:05"),
		CreatedBy:   createdBy,
		UpdatedAt:   notice.UpdatedAt.Format("2006-01-02 15:04:05"),
		UpdatedBy:   updatedBy,
		Status:      notice.Status,
		Type:        notice.Type,
		Logs:        logs,
	}
}

func (r *NoticeResourceImpl) FormatNotices(notices []*models.Notice) []*prot.Notice {
	result := make([]*prot.Notice, 0, len(notices))
	for _, n := range notices {
		if formatted := r.FormatNotice(n); formatted != nil {
			result = append(result, formatted)
		}
	}
	return result
}

func (r *NoticeResourceImpl) FormatModelNotice(notice *prot.Notice) *models.Notice {
	if notice == nil {
		return nil
	}

	var cover, description, content *string
	var createdBy, updatedBy *int64

	if notice.Cover != "" {
		cover = &notice.Cover
	}
	if notice.Description != "" {
		description = &notice.Description
	}
	if notice.Content != "" {
		content = &notice.Content
	}
	if notice.CreatedBy != 0 {
		createdBy = &notice.CreatedBy
	}
	if notice.UpdatedBy != 0 {
		updatedBy = &notice.UpdatedBy
	}

	// Default type to "system" if empty
	noticeType := notice.Type
	if noticeType == "" {
		noticeType = models.NoticeTypeSystem
	}

	return &models.Notice{
		// ID will be auto-generated by database, don't set it from request
		Cover:       cover,
		Title:       notice.Title,
		Description: description,
		Content:     content,
		CreatedBy:   createdBy,
		UpdatedBy:   updatedBy,
		Status:      notice.Status,
		Type:        noticeType,
	}
}

