ALTER TABLE h5p_contents
ADD COLUMN IF NOT EXISTS sort_position INT,
ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP,
ADD COLUMN IF NOT EXISTS created_by BIGINT,
ADD COLUMN IF NOT EXISTS updated_by BIGINT,
ADD COLUMN IF NOT EXISTS deleted_by BIGINT;
