ALTER TABLE courses
ADD COLUMN start_date DATE NOT NULL DEFAULT CURRENT_DATE,
ADD COLUMN end_date DATE NOT NULL DEFAULT CURRENT_DATE;

ALTER TABLE courses
DROP COLUMN IF EXISTS duration;

ALTER TABLE courses
ADD COLUMN duration INTEGER;

