DROP TYPE IF EXISTS join_level_enum CASCADE;
DROP TYPE IF EXISTS question_form_enum CASCADE;
DROP TYPE IF EXISTS course_state CASCADE;
DROP TYPE IF EXISTS display_enum CASCADE;
DROP TYPE IF EXISTS question_type_enum CASCADE;
DROP TYPE IF EXISTS level_enum CASCADE;
DROP TYPE IF EXISTS kind_enum CASCADE;
DROP EXTENSION IF EXISTS unaccent;
