DROP TABLE IF EXISTS lesson_dependencies CASCADE;
DROP TABLE IF EXISTS lesson_ref_skills CASCADE;
DROP TABLE IF EXISTS lesson_ref_topics CASCADE;
DROP TABLE IF EXISTS lesson_ref_tags CASCADE;
DROP TABLE IF EXISTS skills CASCADE;
DROP TABLE IF EXISTS topics CASCADE;
DROP TABLE IF EXISTS tags CASCADE;
