DROP TABLE IF EXISTS cloned_questions CASCADE;
DROP TABLE IF EXISTS exercise_ref_lessons CASCADE;
DROP TABLE IF EXISTS homework_ref_lessons CASCADE;
DROP TABLE IF EXISTS exam_ref_lessons CASCADE;
DROP TABLE IF EXISTS exercises CASCADE;
DROP TABLE IF EXISTS homeworks CASCADE;
DROP TABLE IF EXISTS exams CASCADE;
