DROP TABLE IF EXISTS lesson_schedules CASCADE;
DROP TABLE IF EXISTS weeks CASCADE;
DROP TABLE IF EXISTS course_ref_study_shifts CASCADE;
DROP TABLE IF EXISTS study_shifts CASCADE;
DROP TABLE IF EXISTS course_ref_semesters CASCADE;
DROP TABLE IF EXISTS semester_ref_holidays CASCADE;
DROP TABLE IF EXISTS holidays CASCADE;
DROP TABLE IF EXISTS semesters CASCADE;
