DROP TABLE IF EXISTS lesson_completions CASCADE;
DROP TABLE IF EXISTS history_uses CASCADE;
DROP TABLE IF EXISTS password_resets CASCADE;
DROP TABLE IF EXISTS feedbacks CASCADE;
DROP TABLE IF EXISTS medias CASCADE;
