DROP TABLE IF EXISTS scorm_sessions CASCADE;
DROP TABLE IF EXISTS scorm_cmi CASCADE;
DROP TABLE IF EXISTS scorm_attempts CASCADE;
DROP TABLE IF EXISTS scorm_activities CASCADE;
DROP TABLE IF EXISTS h5p_content_user_data CASCADE;
DROP TABLE IF EXISTS h5p_content_scores CASCADE;
DROP TABLE IF EXISTS h5p_contents CASCADE;
