ALTER TABLE source_questions
    ADD COLUMN status SMALLINT NOT NULL DEFAULT 1;

ALTER TABLE departments
    ADD COLUMN status SMALLINT NOT NULL DEFAULT 1;

ALTER TABLE degrees
    ADD COLUMN status SMALLINT NOT NULL DEFAULT 1;

ALTER TABLE certificates
    DROP COLUMN IF EXISTS status;

ALTER TABLE certificates
    ADD COLUMN status SMALLINT NOT NULL DEFAULT 1;

ALTER TABLE employee_positions
    ADD COLUMN status SMALLINT NOT NULL DEFAULT 1;

ALTER TABLE roles
    ADD COLUMN status SMALLINT NOT NULL DEFAULT 1;

ALTER TABLE schools
    ADD COLUMN status SMALLINT NOT NULL DEFAULT 1;

ALTER TABLE question_attributes
    ADD COLUMN status SMALLINT NOT NULL DEFAULT 1;