ALTER TABLE IF EXISTS users
DROP COLUMN IF EXISTS avatar_info;

ALTER TABLE IF EXISTS certificates
DROP COLUMN IF EXISTS file_info;

ALTER TABLE IF EXISTS courses
DROP COLUMN IF EXISTS image_info;

ALTER TABLE IF EXISTS degrees
DROP COLUMN IF EXISTS file_info;

ALTER TABLE IF EXISTS exam_question_user_manual_scoring
DROP COLUMN IF EXISTS file_info;

ALTER TABLE IF EXISTS exams
DROP COLUMN IF EXISTS cover_image_info;

ALTER TABLE IF EXISTS homework_question_user_manual_scoring
DROP COLUMN IF EXISTS file_info;

ALTER TABLE IF EXISTS homeworks
DROP COLUMN IF EXISTS cover_image_info;

ALTER TABLE IF EXISTS lesson_plan_parts
DROP COLUMN IF EXISTS link_info;

ALTER TABLE IF EXISTS lesson_plans
DROP COLUMN IF EXISTS cover_image_info;

ALTER TABLE IF EXISTS level_tests
DROP COLUMN IF EXISTS cover_image_info;

ALTER TABLE IF EXISTS schools
DROP COLUMN IF EXISTS logo_info;

ALTER TABLE IF EXISTS skills
DROP COLUMN IF EXISTS image_info;

ALTER TABLE IF EXISTS tags
DROP COLUMN IF EXISTS image_info;

ALTER TABLE IF EXISTS topics
DROP COLUMN IF EXISTS image_info;

ALTER TABLE IF EXISTS questions
DROP COLUMN IF EXISTS file_info;

ALTER TABLE IF EXISTS answer_groups
DROP COLUMN IF EXISTS file_info;

ALTER TABLE IF EXISTS answer_coordinates
DROP COLUMN IF EXISTS media_info;

ALTER TABLE IF EXISTS answer_matchings
DROP COLUMN IF EXISTS file_info;

ALTER TABLE IF EXISTS answer_positions
DROP COLUMN IF EXISTS media_info;

ALTER TABLE IF EXISTS answers
DROP COLUMN IF EXISTS file_info;

ALTER TABLE IF EXISTS group_answers
DROP COLUMN IF EXISTS file_info;

ALTER TABLE IF EXISTS answer_matchings
DROP COLUMN IF EXISTS matching_file_info;

ALTER TABLE IF EXISTS questions
ADD COLUMN IF NOT EXISTS media_info JSONB;

ALTER TABLE IF EXISTS answer_groups
ADD COLUMN IF NOT EXISTS media_info JSONB;

ALTER TABLE IF EXISTS answer_coordinates
ADD COLUMN IF NOT EXISTS media_info JSONB;

ALTER TABLE IF EXISTS answer_matchings
ADD COLUMN IF NOT EXISTS media_info JSONB;

ALTER TABLE IF EXISTS answer_positions
ADD COLUMN IF NOT EXISTS media_info JSONB;

ALTER TABLE IF EXISTS answers
ADD COLUMN IF NOT EXISTS media_info JSONB;

ALTER TABLE IF EXISTS group_answers
ADD COLUMN IF NOT EXISTS media_info JSONB;

ALTER TABLE IF EXISTS answer_matchings
ADD COLUMN IF NOT EXISTS matching_media_info JSONB;
