ALTER TABLE IF EXISTS users
DROP COLUMN IF EXISTS avatar;

ALTER TABLE IF EXISTS certificates
DROP COLUMN IF EXISTS file_url;

ALTER TABLE IF EXISTS courses
DROP COLUMN IF EXISTS image;

ALTER TABLE IF EXISTS degrees
DROP COLUMN IF EXISTS file_url;

ALTER TABLE IF EXISTS exam_question_user_manual_scoring
DROP COLUMN IF EXISTS file_url;

ALTER TABLE IF EXISTS exams
DROP COLUMN IF EXISTS cover_image;

ALTER TABLE IF EXISTS homework_question_user_manual_scoring
DROP COLUMN IF EXISTS file_url;

ALTER TABLE IF EXISTS homeworks
DROP COLUMN IF EXISTS cover_image;

ALTER TABLE IF EXISTS lesson_plan_parts
DROP COLUMN IF EXISTS link;

ALTER TABLE IF EXISTS lesson_plans
DROP COLUMN IF EXISTS cover_image;

ALTER TABLE IF EXISTS level_tests
DROP COLUMN IF EXISTS cover_image;

ALTER TABLE IF EXISTS schools
DROP COLUMN IF EXISTS logo;

ALTER TABLE IF EXISTS skills
DROP COLUMN IF EXISTS image_url;

ALTER TABLE IF EXISTS tags
DROP COLUMN IF EXISTS image_url;

ALTER TABLE IF EXISTS topics
DROP COLUMN IF EXISTS image_url;

ALTER TABLE IF EXISTS questions
DROP COLUMN IF EXISTS file_url;

ALTER TABLE IF EXISTS answer_groups
DROP COLUMN IF EXISTS file_url;

ALTER TABLE IF EXISTS answer_coordinates
DROP COLUMN IF EXISTS media_url;

ALTER TABLE IF EXISTS answer_matchings
DROP COLUMN IF EXISTS file_url;

ALTER TABLE IF EXISTS answer_positions
DROP COLUMN IF EXISTS media_url;

ALTER TABLE IF EXISTS answers
DROP COLUMN IF EXISTS file_url;

ALTER TABLE IF EXISTS group_answers
DROP COLUMN IF EXISTS file_url;

ALTER TABLE IF EXISTS answer_matchings
DROP COLUMN IF EXISTS matching_file_url;

ALTER TABLE IF EXISTS lesson_plan_parts
DROP COLUMN IF EXISTS cover_image;
