-- DO $$
-- BEGIN
--     -- Nếu cột id chưa có default thì set default
--     IF NOT EXISTS (
--         SELECT 1
--         FROM pg_attrdef d
--         JOIN pg_attribute a ON a.attrelid = d.adrelid AND a.attnum = d.adnum
--         WHERE a.attrelid = 'h5p_contents'::regclass
--           AND a.attname = 'id'
--     ) THEN
--         -- Nếu sequence chưa tồn tại thì tạo
--         IF NOT EXISTS (
--             SELECT 1 FROM pg_class WHERE relname = 'h5p_contents_id_seq'
--         ) THEN
--             CREATE SEQUENCE h5p_contents_id_seq;
--         END IF;

--         ALTER TABLE h5p_contents
--             ALTER COLUMN id SET DEFAULT nextval('h5p_contents_id_seq');
--     END IF;
-- END$$;

-- SELECT setval(
--     pg_get_serial_sequence('h5p_contents', 'id'),
--     COALESCE((SELECT MAX(id) FROM h5p_contents), 0) + 1,
--     false
-- );
