ALTER TABLE exams ADD COLUMN IF NOT EXISTS is_random_question BOOLEAN DEFAULT FALSE;

ALTER TABLE homeworks ADD COLUMN IF NOT EXISTS is_random_question BOOLEAN DEFAULT FALSE;

ALTER TABLE exercises ADD COLUMN IF NOT EXISTS is_random_question BOOLEAN DEFAULT FALSE;
