ALTER TABLE IF EXISTS homework_users
    DROP COLUMN IF EXISTS rate;

ALTER TABLE IF EXISTS exam_users
    DROP COLUMN IF EXISTS rate;

ALTER TABLE IF EXISTS exercise_users
    DROP COLUMN IF EXISTS rate;

ALTER TABLE IF EXISTS contest_round_users
    DROP COLUMN IF EXISTS rate;

